// Root有限工程控制：只创建自有小JSON，不读取历史库、不运行产品或规模。
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {readOwnerAcceptedHistoricalScale,OWNER_STAGE_SCALE_FAILURES} from '../mbrs003-owner-stage-scale.mjs';
const STATUS='OWNER_ACCEPTED_HISTORICAL_SCALE_WITH_CARRYOVER';
const readerCodes=['REVOKED','SOURCE_ROOT_OFFLINE','OUTSIDE_ROOT','MISSING','CONTENT_CHANGED','IO_ERROR','BUDGET_EXCEEDED','PARSE_FAILED','UNSUPPORTED','TIMEOUT','WORKER_START_TIMEOUT','CANCELLED','CLOSED','QUEUE_FULL','WORKER_FAILED','LEASE_RELEASE_FAILED','ADMISSION_FAILED'];
const catalogCodes=['CATALOG_METADATA_INVALID','CATALOG_FIELD_INVALID_TITLE','CATALOG_FIELD_INVALID_ARTIST','CATALOG_FIELD_INVALID_ALBUM','CATALOG_FIELD_INVALID_YEAR','CATALOG_FIELD_INVALID_DISC','CATALOG_FIELD_INVALID_TRACK'];
function fixture(){
 assert.ok(process.env.TMPDIR&&path.isAbsolute(process.env.TMPDIR),'Root须提供受控TMPDIR');
 const root=fs.mkdtempSync(path.join(fs.realpathSync(process.env.TMPDIR),'mbrs003-owner-stage-'));fs.chmodSync(root,0o700);fs.mkdirSync(path.join(root,'evidence'),{mode:0o700});
 const data={result:{schema:'mbrs003.digital-audio-scale-observation.v3',status:'FAILURE',count:300000,timedOut:false,metrics:{readerCalls:300000,ok:299975,failures:25,stages:[{}, {},{name:'new-job-after-cancel-completes-first-corpus',phase:'completed',progress:{visited:'300000',accepted:'299975',rejected:'25'}}]}},gate:{exitCode:1,timedOut:false,signal:null},diagnostic:{committedFileCount:300000,accepted:299975,rejected:25,committedBatchCount:1501,readerFailureCodeCounts:Object.fromEntries(readerCodes.map(k=>[k,k==='TIMEOUT'?20:k==='WORKER_START_TIMEOUT'?5:0])),catalogFailureCodeCounts:Object.fromEntries(catalogCodes.map(k=>[k,0])),unknownCodeCount:0,coverageAndConsistency:{metadataCoverageComplete:true,countsMatchExpected:true,checkpointChainVerified:true,batchItemPairingVerified:true,physicalCause:'UNKNOWN',scalePass:false,whole003Pass:false}},diagnosticClosure:{schema:'mbrs003.root.actual-tool-execution-closure.v1',status:'ROOT_ACTUAL_TOOL_RETURN_WAIT_STDIO_CLOSED',component:'CLOSED_NEW06_COMMITTED_FAILURE_CODES_PRODUCER04',actualWrapperExitCode:0,actualWrapperWaitCompleted:true,actualWrapperStdiosClosed:true,actualChildWaitCompleted:true,actualArchiveWaitCompleted:true,archiveExitCode:0,classifiedRejectedCount:25,safeKnownCodeCounts:{TIMEOUT:20,WORKER_START_TIMEOUT:5},unknownCodeCount:0,physicalCause:'UNKNOWN',itemIdentifiers:'UNKNOWN_NOT_EXPORTED',originalDatabaseSQLiteOpened:false,newScanStarted:false,ReaderStarted:false,WorkerStarted:false,scalePass:false,whole003Pass:false}};
 const decision={schema:'mbrs003.owner-stage-scale-acceptance.v1',status:STATUS,accepted:true,rerunCurrent100k300k:false,currentFullScalePass:false,currentFullScaleObserved:false,newScaleRunStarted:false,newScaleRoundAuthorized:false,authority:'OWNER_DIRECT_MESSAGE_IN_CURRENT_CHAT',physicalCause:'UNKNOWN',historicalTechnicalStatus:'FAILURE_PRESERVED',historicalStagesFourAndFive:'NOT_RUN_PRESERVED',finalRealLibraryAcceptance:'DEFERRED_UNTIL_COMPLETE_PRODUCT',historicalCounts:{visited:300000,accepted:299975,rejected:25,timeout:20,workerStartTimeout:5},historicalEvidence:{}};
 function write(relative,value){const file=path.join(root,relative),bytes=Buffer.from(JSON.stringify(value));fs.writeFileSync(file,bytes,{flag:'wx',mode:0o600});return {path:relative,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')}}
 function save(){
  for(const role of ['result','gate','diagnostic']){const ref=write('evidence/'+role+'.json',data[role]);decision.historicalEvidence[role]={...ref,originalRef:{...ref,path:'/synthetic-history/'+role+'.json'}}}
  data.diagnosticClosure.diagnosticRef={...decision.historicalEvidence.diagnostic.originalRef};const ref=write('evidence/diagnosticClosure.json',data.diagnosticClosure);decision.historicalEvidence.diagnosticClosure={...ref,originalRef:{...ref,path:'/synthetic-history/diagnosticClosure.json'}};
  return {mode:STATUS,currentFullScalePass:false,finalRealLibraryAcceptance:'DEFERRED_UNTIL_COMPLETE_PRODUCT',decisionRef:write('decision.json',decision)};
 }
 return {root,data,decision,save,write,cleanup(){fs.rmSync(root,{recursive:true,force:true})}};
}
const budget={check(){}};
async function accepted(mutate=()=>{}){const f=fixture();try{mutate(f);const spec=f.save();return await readOwnerAcceptedHistoricalScale(spec,f.root,budget)}finally{f.cleanup()}}
async function rejected(before,after=()=>{},code){const f=fixture();try{before(f);const spec=f.save();after(f,spec);await assert.rejects(()=>readOwnerAcceptedHistoricalScale(spec,f.root,budget),e=>OWNER_STAGE_SCALE_FAILURES.includes(e.code)&&(!code||e.code===code)&&e.message===e.code)}finally{f.cleanup()}}

test('Owner接受遗留只返回接受状态，当前规模与执行标志保持false',async()=>{const v=await accepted();assert.equal(v.status,STATUS);assert.equal(v.fullScalePass,false);assert.equal(v.currentFullScaleObserved,false);assert.equal(v.noScaleExecutionInGate,true);assert.equal(v.physicalCause,'UNKNOWN');assert.equal(v.historicalCounts.rejected,25)});
test('Owner未接受或缺失：不能借历史失败放行',async()=>{await rejected(f=>{f.decision.accepted=false});await rejected(f=>{delete f.decision.accepted});await rejected(()=>{},(_f,s)=>{delete s.decisionRef},'OWNER_STAGE_SCALE_REFERENCE_INVALID')});
test('禁止把接受遗留写成当前fullScalePASS或许可重测',async()=>{await rejected(f=>{f.decision.currentFullScalePass=true});await rejected(f=>{f.decision.rerunCurrent100k300k=true});await rejected(f=>{f.decision.fullScalePass=true});await rejected(f=>{f.decision.currentFullScaleObserved=true});await rejected(f=>{f.decision.newScaleRunStarted=true});await rejected(f=>{f.decision.newScaleRoundAuthorized=true});await rejected(()=>{},(_f,s)=>{s.currentFullScalePass=true});await rejected(f=>{f.decision.authority='UNKNOWN'})});
test('Owner声明的历史数量不能漂移',async()=>{await rejected(f=>{f.decision.historicalCounts.accepted=300000});await rejected(f=>{f.decision.historicalCounts.timeout=19})});
test('历史result必须真失败且第三阶段确实完成指定总量',async()=>{await rejected(f=>{f.data.result.status='PASS'});await rejected(f=>{f.data.result.metrics.stages[2].progress.rejected='0'});await rejected(f=>{f.data.result.metrics.stages[2].phase='running'})});
test('Node Gate必须自然1，不能借超时、signal或0覆盖',async()=>{await rejected(f=>{f.data.gate.exitCode=0});await rejected(f=>{f.data.gate.timedOut=true});await rejected(f=>{f.data.gate.signal=15})});
test('诊断分类与闭合互指不能被错误或未闭合值替代',async()=>{await rejected(f=>{f.data.diagnostic.unknownCodeCount=1});await rejected(f=>{f.data.diagnostic.readerFailureCodeCounts.TIMEOUT=19});await rejected(f=>{f.data.diagnosticClosure.actualWrapperStdiosClosed=false});await rejected(f=>{f.data.diagnosticClosure.actualArchiveWaitCompleted=false});await rejected(()=>{},(f,s)=>{const decision=JSON.parse(fs.readFileSync(path.join(f.root,'decision.json')));decision.historicalEvidence.diagnostic.originalRef.path='/different-original.json';fs.unlinkSync(path.join(f.root,'decision.json'));s.decisionRef=f.write('decision.json',decision)})});
test('冻结文件字节和SHA拒绝事后改变',async()=>{await rejected(()=>{},f=>{fs.appendFileSync(path.join(f.root,'evidence/result.json'),' ')},'OWNER_STAGE_SCALE_FILE_INVALID');await rejected(()=>{},(f,s)=>{s.decisionRef.sha256='0'.repeat(64)},'OWNER_STAGE_SCALE_FILE_CHANGED')});
test('相对路径escape/绝对路径与文件或祖先symlink全部拒绝',async()=>{await rejected(()=>{},(_f,s)=>{s.decisionRef.path='../decision.json'},'OWNER_STAGE_SCALE_PATH_INVALID');await rejected(()=>{},(f,s)=>{s.decisionRef.path=path.join(f.root,'decision.json')},'OWNER_STAGE_SCALE_PATH_INVALID');await rejected(()=>{},f=>{fs.renameSync(path.join(f.root,'evidence'),path.join(f.root,'real-evidence'));fs.symlinkSync('real-evidence',path.join(f.root,'evidence'))},'OWNER_STAGE_SCALE_PATH_INVALID');await rejected(()=>{},f=>{fs.renameSync(path.join(f.root,'evidence/gate.json'),path.join(f.root,'evidence/real-gate.json'));fs.symlinkSync('real-gate.json',path.join(f.root,'evidence/gate.json'))},'OWNER_STAGE_SCALE_PATH_INVALID')});
test('单件256KiB上限和已过预算必须在准入前拒绝',async()=>{await rejected(()=>{},(_f,s)=>{s.decisionRef.bytes=256*1024+1},'OWNER_STAGE_SCALE_REFERENCE_INVALID');const f=fixture();try{const spec=f.save();await assert.rejects(()=>readOwnerAcceptedHistoricalScale(spec,f.root,{check(){throw new Error('不导出原错误')}}),{code:'OWNER_STAGE_SCALE_BUDGET_EXPIRED'})}finally{f.cleanup()}});
