import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import {mkdir,rename,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {audioFixture,loadFreshMetadataReader} from '../helpers/mbrs003-audio-fixtures.js';
import {authorizeSourceDirectory,readonlySourceCandidateMetadata} from '../../src/recording/source-files.js';
import {createCollectionRepository} from '../../src/collection/repository.js';
import {createLocalScanCoordinator} from '../../src/collection/local-scan-coordinator.js';
import {createScanReadAdmission} from '../../src/library/scan-read-admission.js';
import type {DatasetProjectionPort,DatasetProjectionCommand,DatasetProjectionCommandResults,DatasetProjectionCommandPayloads} from '../../src/collection/dataset-owner-protocol.js';
import type {MetadataReaderLifecycle} from '../../src/library/metadata-reader-types.js';

test('MBRS003 relocation：真实外部改名经原moveAsset确认后增量复扫保留唯一资产曲目及raw人工覆盖',{timeout:60_000},async t=>{
  const fixture=await audioFixture(t),directory=path.join(fixture.directory,'rename-media');
  await mkdir(directory,{mode:0o700});
  const oldRelative='原曲.wav',newRelative='外部改名.wav';
  await writeFile(path.join(directory,oldRelative),await fixture.bytes('core-wav'),{flag:'wx',mode:0o600});
  const datasetId=randomUUID(),repository=createCollectionRepository({filePath:path.join(fixture.directory,'rename.sqlite')});
  const source=repository.sources.authorize(randomUUID(),await authorizeSourceDirectory(directory));
  const root=repository.localCatalog.registerRoot({commandId:randomUUID(),sourceRootId:source.id,role:'library'});
  const context={epoch:randomUUID(),datasetId},admission=createScanReadAdmission({isBusy:()=>false});
  const projection:DatasetProjectionPort={async call<K extends DatasetProjectionCommand>(command:K,payload:DatasetProjectionCommandPayloads[K]):Promise<DatasetProjectionCommandResults[K]>{
    let result:unknown;
    if(command === 'scanReadAcquire') result=admission.acquire(context);
    else if(command === 'scanReadWatchRevocation') result=await admission.watchRevocation(context,(payload as {permitId:string}).permitId);
    else if(command === 'scanReadRelease') result=admission.release(context,(payload as {permitId:string}).permitId);
    else throw new Error('此测试仅接真实扫描准入本体。');
    return result as DatasetProjectionCommandResults[K];
  }};
  const events:MetadataReaderLifecycle[]=[],reader=(await loadFreshMetadataReader()).createMetadataReader({onLifecycle:e=>events.push(e)});
  const coordinator=createLocalScanCoordinator({repository,datasetId,assertCurrent:()=>{repository.list({offset:0,limit:1});},projection,reader});
  t.after(async()=>{await coordinator.close();admission.close();repository.close();});
  const first=coordinator.start({commandId:randomUUID(),libraryRootId:root.id,expectedRootRevision:root.revision});
  await coordinator.privateWait(first.jobId);
  assert.equal(coordinator.get(first.jobId).phase,'completed');
  assert.deepEqual(coordinator.get(first.jobId).progress,{visited:'1',accepted:'1',rejected:'0'});
  const firstPage=repository.localCatalog.pageTracks({offset:0,limit:200});assert.equal(firstPage.total,1);
  const track=firstPage.items[0]!,asset=repository.localCatalog.asset(track.assetId);
assert.equal(asset.sampleFrames,null);assert.equal(asset.timebaseHz,null);assert.equal(track.segment,null);
  const raw=repository.localCatalog.metadata(track.id);
  assert.ok(raw.raw.title && raw.raw.artist && raw.raw.album,'真实WAV标签已解析，不能用空raw假称保留');
  const override=repository.localCatalog.overrideMetadata({commandId:randomUUID(),trackId:track.id,expectedRevision:null,fields:{title:'固定人工标题'}});
  const originalState=repository.localScan.privateFileState(root.id,oldRelative);assert.ok(originalState);
  const before=await readonlySourceCandidateMetadata(source,oldRelative);
  await rename(path.join(directory,oldRelative),path.join(directory,newRelative));
  const after=await readonlySourceCandidateMetadata(source,newRelative);
  assert.deepEqual(after.signature.split(':').slice(0,4),before.signature.split(':').slice(0,4),'真实rename保留dev/ino/size/mtime，仅作为可信候选事实');
  await assert.rejects(readonlySourceCandidateMetadata(source,oldRelative));
  const commandId=randomUUID(),moved=repository.localCatalog.moveAsset({commandId,assetId:asset.id,expectedLocationRevision:asset.locationRevision,expectedRootRevision:root.revision,relative:newRelative});
  assert.equal(moved.id,asset.id);assert.equal(moved.fileRevision,asset.fileRevision);assert.equal(moved.locationRevision,'2');
  assert.equal(moved.sourceRootId,source.id);assert.equal(repository.localCatalog.root(root.id).revision,root.revision);
  assert.deepEqual(repository.localCatalog.track(track.id),track);
  assert.deepEqual(repository.localCatalog.metadata(track.id).raw,raw.raw);assert.deepEqual(repository.localCatalog.metadata(track.id).override,override);
  assert.deepEqual(repository.localScan.privateFileState(root.id,oldRelative),originalState,'历史file-state键与原事实不移除、不改写');
  assert.equal(repository.localCatalog.receipt(commandId)?.operation,'move-asset');
  const second=coordinator.start({commandId:randomUUID(),libraryRootId:root.id,expectedRootRevision:root.revision});
  await coordinator.privateWait(second.jobId);
  assert.equal(coordinator.get(second.jobId).phase,'completed');assert.deepEqual(coordinator.get(second.jobId).progress,{visited:'1',accepted:'1',rejected:'0'});
  assert.equal(events.filter(e=>e.type === 'worker-start').length,events.filter(e=>e.type === 'worker-exit').length);
  assert.equal(events.filter(e=>e.type === 'lease-acquired').length,events.filter(e=>e.type === 'lease-released').length);
  const page=repository.localCatalog.pageTracks({offset:0,limit:200});
  assert.equal(page.total,1,'唯一目标：已确认current locator的复扫必须复用已有asset/track，不按新relative再造对象');
  assert.equal(page.items[0]!.id,track.id);assert.equal(page.items[0]!.assetId,asset.id);
  assert.deepEqual(repository.localCatalog.metadata(track.id).raw,raw.raw);assert.deepEqual(repository.localCatalog.metadata(track.id).override,override);
  assert.equal(repository.localCatalog.metadata(track.id).effective.title,'固定人工标题');
  assert.deepEqual(repository.localScan.privateFileState(root.id,oldRelative),originalState);
  const currentState=repository.localScan.privateFileState(root.id,newRelative);assert.ok(currentState);
  assert.equal(currentState.value.assetId,asset.id);assert.equal(currentState.value.trackId,track.id);
assert.equal(repository.localCatalog.asset(asset.id).sampleFrames,null);assert.equal(repository.localCatalog.asset(asset.id).timebaseHz,null);
});
