import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import {mkdir,rename,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {Worker} from 'node:worker_threads';
import * as dto from '@music-bridge/contracts';
import {audioFixture,loadFreshMetadataReader} from '../helpers/mbrs003-audio-fixtures.js';
import {authorizeSourceDirectory,sourceRootAvailability} from '../../src/recording/source-files.js';
import {createCollectionRepository} from '../../src/collection/repository.js';
import {createLocalScanCoordinator} from '../../src/collection/local-scan-coordinator.js';
import {createLocalRelocationCoordinator} from '../../src/collection/local-relocation-coordinator.js';
import {createDatasetOwnerClient} from '../../src/collection/dataset-owner-client.js';
import {createScanReadAdmission} from '../../src/library/scan-read-admission.js';
import type {DatasetProjectionPort,DatasetProjectionCommand,DatasetProjectionCommandResults,DatasetProjectionCommandPayloads} from '../../src/collection/dataset-owner-protocol.js';
function ledger(file:string){const db=new DatabaseSync(file,{readOnly:true,allowExtension:false});try{return db.prepare('SELECT * FROM local_catalog_ledger ORDER BY rowid').all();}finally{db.close();}}
async function unit(t:test.TestContext){const fixture=await audioFixture(t),directory=path.join(fixture.directory,'relocation-media'),file=path.join(fixture.directory,'relocation.sqlite');await mkdir(directory,{mode:0o700});await writeFile(path.join(directory,'old.wav'),await fixture.bytes('core-wav'),{mode:0o600,flag:'wx'});
 const repository=createCollectionRepository({filePath:file}),source=repository.sources.authorize(randomUUID(),await authorizeSourceDirectory(directory)),root=repository.localCatalog.registerRoot({commandId:randomUUID(),sourceRootId:source.id,role:'library'}),datasetId=randomUUID(),context={epoch:randomUUID(),datasetId},admission=createScanReadAdmission({isBusy:()=>false});
 const projection:DatasetProjectionPort={async call<K extends DatasetProjectionCommand>(command:K,payload:DatasetProjectionCommandPayloads[K]):Promise<DatasetProjectionCommandResults[K]>{let result:unknown;if(command==='scanReadAcquire')result=admission.acquire(context);else if(command==='scanReadWatchRevocation')result=await admission.watchRevocation(context,(payload as {permitId:string}).permitId);else if(command==='scanReadRelease')result=admission.release(context,(payload as {permitId:string}).permitId);else throw new Error('仅真实扫描准入本体');return result as DatasetProjectionCommandResults[K];}};
 const scan=createLocalScanCoordinator({repository,datasetId,assertCurrent:()=>{repository.list({offset:0,limit:1});},projection,reader:(await loadFreshMetadataReader()).createMetadataReader()});
 const service=createLocalRelocationCoordinator({repository,assertCurrent:()=>{repository.list({offset:0,limit:1});},beforeMutation:()=>scan.yieldForMedia()});
 t.after(async()=>{await scan.close();service.close();admission.close();repository.close();});
 const start=scan.start({commandId:randomUUID(),libraryRootId:root.id,expectedRootRevision:root.revision});await scan.privateWait(start.jobId);assert.equal(scan.get(start.jobId).phase,'completed');
 const track=repository.localCatalog.pageTracks({offset:0,limit:200}).items[0]!,asset=repository.localCatalog.asset(track.assetId),selection={assetId:asset.id,expectedFileRevision:asset.fileRevision,expectedLocationRevision:asset.locationRevision,expectedRootRevision:root.revision};
 repository.localCatalog.overrideMetadata({commandId:randomUUID(),trackId:track.id,expectedRevision:null,fields:{title:'保留人工标题'}});const metadata=repository.localCatalog.metadata(track.id);
 return {fixture,directory,file,repository,source,root,scan,service,track,asset,selection,metadata};
}
test('MBRS003 relocation owner：多候选不自动合并，显式确认唯一选择保持raw和人工覆盖且旧候选CAS拒绝',{timeout:60_000},async t=>{
 const f=await unit(t);await rename(path.join(f.directory,'old.wav'),path.join(f.directory,'renamed.wav'));await writeFile(path.join(f.directory,'copy.wav'),await f.fixture.bytes('core-wav'),{mode:0o600,flag:'wx'});
 const before=ledger(f.file),captured=await f.service.capture({...f.selection,absolutePaths:[path.join(f.directory,'renamed.wav'),path.join(f.directory,'copy.wav')]});assert.equal(captured.candidates.length,2);assert.notEqual(captured.candidates[0]!.id,captured.candidates[1]!.id);assert.deepEqual(captured.candidates.map(c=>c.evidence),['same-inode-observation','user-choice']);assert.deepEqual(ledger(f.file),before,'候选捕获无实体/ledger副作用');
 const confirmed={...f.selection,commandId:captured.candidates[0]!.id,userConfirmed:true as const},result=await f.service.confirm(confirmed);assert.equal(result.id,f.asset.id);assert.equal(result.fileRevision,'1');assert.equal(result.locationRevision,'2');assert.equal(f.repository.localCatalog.privateAssetLocator(result.id).relative,'renamed.wav');assert.deepEqual(f.repository.localCatalog.track(f.track.id),f.track);assert.deepEqual(f.repository.localCatalog.metadata(f.track.id),f.metadata);
 await assert.rejects(f.service.confirm({...confirmed,commandId:captured.candidates[1]!.id}));assert.equal(f.repository.localCatalog.pageTracks({offset:0,limit:200}).total,1);assert.equal(ledger(f.file).length,before.length+1);
 const nextSelection={...f.selection,expectedLocationRevision:'2'},next=await f.service.capture({...nextSelection,absolutePaths:[path.join(f.directory,'copy.wav')]});assert.equal(next.candidates[0]!.evidence,'user-choice');const replacement=await f.service.confirm({...nextSelection,commandId:next.candidates[0]!.id,userConfirmed:true});assert.equal(replacement.id,f.asset.id);assert.equal(replacement.fileRevision,'2','无独立同一inode依据时保守换选，不冒保持旧内容修订');assert.equal(replacement.locationRevision,'3');assert.deepEqual(f.repository.localCatalog.metadata(f.track.id),f.metadata);assert.equal(f.repository.localCatalog.pageTracks({offset:0,limit:200}).total,1);
});
test('MBRS003 relocation owner：真实持久receipt冷恢复同完整确认仅返回原结果、改参及新旧许可失效拒绝',{timeout:60_000},async t=>{
 const f=await unit(t);await rename(path.join(f.directory,'old.wav'),path.join(f.directory,'renamed.wav'));const capture=await f.service.capture({...f.selection,absolutePaths:[path.join(f.directory,'renamed.wav')]});const body={...f.selection,commandId:capture.candidates[0]!.id,userConfirmed:true as const};const result=await f.service.confirm(body),before=ledger(f.file);
 await f.scan.close();f.service.close();f.repository.close();const cold=createCollectionRepository({filePath:f.file}),service=createLocalRelocationCoordinator({repository:cold,assertCurrent:()=>{cold.list({offset:0,limit:1});}});t.after(()=>{service.close();cold.close();});
 assert.deepEqual(await service.confirm(body),result);assert.deepEqual(ledger(f.file),before);await assert.rejects(service.confirm({...body,expectedFileRevision:'2'}));assert.deepEqual(ledger(f.file),before);
 cold.sources.revoke({commandId:randomUUID(),id:f.source.id});const views=await service.roots();assert.equal(views[0]!.availability,'REVOKED');assert.equal(cold.localCatalog.pageTracks({offset:0,limit:200}).items[0]!.id,f.track.id);await assert.rejects(service.capture({...f.selection,expectedLocationRevision:'2',absolutePaths:[path.join(f.directory,'renamed.wav')]}));
});
test('MBRS003 relocation owner：跨根remount明确换许可并推进root/file/location修订，显式复扫保留稳定ID及覆盖',{timeout:60_000},async t=>{
 const f=await unit(t),newDirectory=path.join(f.fixture.directory,'new-mount');await rename(f.directory,newDirectory);assert.equal(await sourceRootAvailability(f.source),'SOURCE_ROOT_OFFLINE');const target=f.repository.sources.authorize(randomUUID(),await authorizeSourceDirectory(newDirectory));assert.notEqual(target.id,f.source.id);
 const body={commandId:randomUUID(),rootId:f.root.id,expectedRevision:f.root.revision,targetSourceRootId:target.id,userConfirmed:true as const};const root=await f.service.relinkRoot(body);assert.equal(root.id,f.root.id);assert.equal(root.revision,'2');assert.equal(root.sourceRootId,target.id);assert.deepEqual(f.repository.localCatalog.asset(f.asset.id),f.asset,'重关联自身不篡改旧asset快照');assert.deepEqual(f.repository.localCatalog.metadata(f.track.id),f.metadata);
 const scanned=f.scan.start({commandId:randomUUID(),libraryRootId:root.id,expectedRootRevision:root.revision});await f.scan.privateWait(scanned.jobId);assert.equal(f.scan.get(scanned.jobId).phase,'completed');assert.equal(f.repository.localCatalog.pageTracks({offset:0,limit:200}).total,1);assert.equal(f.repository.localCatalog.track(f.track.id).assetId,f.asset.id);const current=f.repository.localCatalog.asset(f.asset.id);assert.equal(current.sourceRootId,target.id);assert.equal(current.rootRevision,'2');assert.equal(current.fileRevision,'2');assert.equal(current.locationRevision,'2');assert.equal(current.sampleFrames,null);assert.equal(current.timebaseHz,null);assert.deepEqual(f.repository.localCatalog.metadata(f.track.id),f.metadata);assert.equal(await sourceRootAvailability(f.repository.sources.root(f.source.id)),'SOURCE_ROOT_OFFLINE');assert.deepEqual(await f.service.relinkRoot(body),root,'冷/重复确认查询原receipt不自动再扫描');
});
test('MBRS003 relocation owner：实际client与Worker可信入口拒普通capture/旧dataset/关闭且严格asset证据不降级',{timeout:60_000},async t=>{
 const f=await unit(t),data=path.join(f.fixture.directory,'worker-data');await mkdir(data,{mode:0o700});const worker=new Worker(new URL('../helpers/dataset-owner-fixture.ts',import.meta.url),{execArgv:['--import','tsx'],workerData:{mode:'scan-real',dataDirectory:data}}),owner=createDatasetOwnerClient({worker,onFatal:()=>{}});t.after(async()=>{if(worker.threadId!==-1)await owner.close();});const identity=await owner.prepare();await owner.commitBoot();
 const request=(command:dto.IpcCommand,payload:unknown,datasetId=identity.datasetId):dto.IpcRequest=>({version:1,id:randomUUID(),command,payload,expectedDatasetId:datasetId});const cap=await owner.dispatch(request('recordingSources.authorize',{commandId:randomUUID(),absolutePath:f.directory})) as dto.SourceRoot;const root=await owner.dispatchInternal!(request('localRelocation.registerRoot',{commandId:randomUUID(),sourceRootId:cap.id})) as dto.LibraryRoot;assert.equal(root.sourceRootId,cap.id);
 await assert.rejects(owner.dispatch(request('localRelocation.capture',{...f.selection,absolutePaths:[path.join(f.directory,'old.wav')]})));await assert.rejects(owner.dispatch(request('localRelocation.roots',{},randomUUID())));await assert.rejects(owner.dispatch(request('localRelocation.confirm',{...f.selection,commandId:randomUUID(),userConfirmed:true,path:'/禁止'})));assert.equal((await owner.dispatch(request('localRelocation.roots',{})) as dto.LocalRootView[])[0]!.root.id,root.id);await owner.close();assert.equal(worker.threadId,-1);await assert.rejects(owner.dispatch(request('localRelocation.roots',{})));
 const exact=f.repository.localCatalog.registerAsset({commandId:randomUUID(),libraryRootId:f.root.id,expectedRootRevision:'1',relative:'strict.wav',sha256:'a'.repeat(64),sampleFrames:'100',timebaseHz:44100});assert.equal(f.repository.localCatalog.privateAssetHasExactEvidence(exact.id),true);await assert.rejects(f.service.capture({assetId:exact.id,expectedFileRevision:'1',expectedLocationRevision:'1',expectedRootRevision:'1',absolutePaths:[path.join(f.directory,'old.wav')]}));const rootBefore=f.repository.localCatalog.root(f.root.id);await assert.rejects(f.service.relinkRoot({commandId:randomUUID(),rootId:f.root.id,expectedRevision:'1',targetSourceRootId:f.source.id,userConfirmed:true}));assert.deepEqual(f.repository.localCatalog.root(f.root.id),rootBefore);
});
