packages:
  - apps/*
  - packages/*

patchedDependencies:
  electron-vite@5.0.0: patches/electron-vite@5.0.0.patch

overrides:
  '@neteasecloudmusicapienhanced/api@4.40.1>axios': '1.20.0'
  '@neteasecloudmusicapienhanced/unblockmusic-utils@0.4.4>axios': '1.20.0'
  'get-uri@6.0.5>basic-ftp': '6.2.1'
