packages:
  - apps/*
  - packages/*

patchedDependencies:
  '@neteasecloudmusicapienhanced/api@4.40.1': patches/@neteasecloudmusicapienhanced__api@4.40.1.patch
  electron-vite@5.0.0: patches/electron-vite@5.0.0.patch

overrides:
  '@neteasecloudmusicapienhanced/api@4.40.1>node-forge': '-'
  '@neteasecloudmusicapienhanced/api@4.40.1>axios': '1.20.0'
  '@neteasecloudmusicapienhanced/unblockmusic-utils@0.4.4>axios': '1.20.0'
  'get-uri@6.0.5>basic-ftp': '6.2.1'
  proxy-addr: '2.0.8'
  source-map-js: '1.2.2'
