export type PublicErrorCode =
  | 'INVALID_IPC_REQUEST'
  | 'UNSUPPORTED_IPC_VERSION'
  | 'UNKNOWN_IPC_COMMAND'
  | 'INVALID_IPC_RESPONSE'
  | 'TIMEOUT'
  | 'NOT_READY'
  | 'AUTH_REQUIRED'
  | 'AUTH_EXPIRED'
  | 'ACCOUNT_PROFILE_UNAVAILABLE'
  | 'DAILY_RECOMMENDATIONS_UNAVAILABLE'
  | 'ROON_CORE_NOT_CONNECTED'
  | 'ROON_LIBRARY_UNAVAILABLE'
  | 'ROON_LIBRARY_REQUEST_FAILED'
  | 'ROON_ZONE_NOT_SELECTED'
  | 'ROON_IMAGE_DECODE_FAILED'
  | 'ROON_ALBUM_HIERARCHY_INVALID'
  | 'ROON_TRACK_ACTION_UNAVAILABLE'
  | 'INTERNAL_ERROR';

export interface PublicError {
  code: PublicErrorCode;
  message: string;
  diagnosticId?: string;
}
