export type PublicErrorCode =
  | 'OUTBOX_SCOPE_MISMATCH'
  | 'INVALID_IPC_REQUEST'
  | 'UNSUPPORTED_IPC_VERSION'
  | 'UNKNOWN_IPC_COMMAND'
  | 'INVALID_IPC_RESPONSE'
  | 'TIMEOUT'
  | 'CANCELLED'
  | 'NOT_READY'
  /** Core已证实本次Begin未提交且没有可能迟到的启动；仅此码允许清除原Begin待确认命令。 */
  | 'ATTEMPT_NOT_ACCEPTED'
  | 'INVENTORY_CONFLICT'
  | 'INVENTORY_UNAVAILABLE'
  | 'AUTH_REQUIRED'
  | 'AUTH_EXPIRED'
  | 'ACCOUNT_PROFILE_UNAVAILABLE'
  | 'DAILY_RECOMMENDATIONS_UNAVAILABLE'
  | 'ROON_CORE_NOT_CONNECTED'
  | 'ROON_TIMEOUT'
  | 'ROON_LIBRARY_UNAVAILABLE'
  | 'ROON_LIBRARY_REQUEST_FAILED'
  | 'ROON_ZONE_NOT_SELECTED'
  | 'ROON_IMAGE_UNAVAILABLE'
  | 'ROON_IMAGE_DECODE_FAILED'
  | 'ROON_ALBUM_HIERARCHY_INVALID'
  | 'ROON_TRACK_ACTION_UNAVAILABLE'
  | 'INTERNAL_ERROR';

export interface PublicError {
  code: PublicErrorCode;
  message: string;
  diagnosticId?: string;
}
