import { isCollectionId, isPhysicalId, isCollectionModel, type CollectionModel } from './collection.js';
import type { Page, PageRequest } from './library.js';

export interface MediaTrackRule { trackId: string; keepWithNext?: boolean; forceSide?: 'A' | 'B'; sideOpener?: boolean; sideCloser?: boolean; gapAfterMs?: number }
/** 人工声明的介质兼容性不是实际输出后端或硬件认证。 */
export interface MediaCompatibility { confirmed: boolean; cassetteTypes: readonly ('I' | 'II' | 'III' | 'IV')[]; dat: boolean }
export interface MediaLayoutSpec { format: 'cassette' | 'dat'; splitAfter: number; leadInMs: number; tailMs: number; defaultGapMs: number; rules: readonly MediaTrackRule[]; compatibility: MediaCompatibility }
export type MediaSourceBasis = 'roon-estimate' | 'verified-sources' | 'unavailable';
export interface MediaTimingTrack { trackId: string; durationMs?: number; basis: MediaSourceBasis }
export interface MediaPlannedTrack { trackId: string; startMs?: number; endMs?: number; gapAfterMs: number }
export interface MediaSide { name: 'A' | 'B' | 'Program'; tracks: readonly MediaPlannedTrack[]; durationMs?: number; musicMs?: number; gapMs: number; leadInMs: number; tailMs: number }
export interface MediaLayout { timebase: 'milliseconds'; executionReady: false; sides: readonly MediaSide[]; constraints: readonly string[] }
export type MediaCandidateReason = 'capacity-unknown' | 'duration-unknown' | 'too-short' | 'compatibility-unknown' | 'incompatible' | 'collector-protected' | 'sealed-protected' | 'minimum-reserve' | 'source-unavailable' | 'layout-conflict';
export interface MediaCandidate { skuId: string; model: CollectionModel; lengthMinutes: number | null; packaging: 'opened' | 'sealed'; availableCount: number; reservableCount: number; fit: 'fits' | 'too-short' | 'unknown'; compatibility: 'confirmed' | 'unknown' | 'incompatible'; reasons: readonly MediaCandidateReason[]; status: 'recommended' | 'pending' | 'excluded' }
export interface MediaPreview { draftId: string; draftRevision: number; inputFingerprint: string; sourceBasis: MediaSourceBasis; layout: MediaLayout; candidates: Page<MediaCandidate> }
export interface MediaReservation { physicalId: string; modelId: string; skuId: string; packaging: 'opened' | 'sealed' }
export interface MediaPlan { id: string; draftId: string; draftRevision: number; revision: number; spec: MediaLayoutSpec; layout: MediaLayout; sourceBasis: MediaSourceBasis; inputFingerprint: string; reservation?: MediaReservation; requiresReview: boolean; executionReady: false }
export interface PreviewMediaRequest { draftId: string; spec: MediaLayoutSpec; page: PageRequest }
export interface SaveMediaPlanRequest { commandId: string; draftId: string; expectedDraftRevision: number; inputFingerprint: string; spec: MediaLayoutSpec; planId?: string; expectedRevision?: number }
export interface ReserveMediaRequest { commandId: string; planId: string; expectedRevision: number; skuId: string; packaging: 'opened' | 'sealed'; userConfirmed: true }
export interface ReleaseMediaRequest { commandId: string; planId: string; expectedRevision: number; userConfirmed: true }
export interface MediaPlanningPublicApi {
  listMediaPlans(draftId: string): Promise<{ draftId: string; plans: readonly MediaPlan[] }>;
  getMediaPlan(id: string): Promise<MediaPlan>;
  previewMediaPlan(request: PreviewMediaRequest): Promise<MediaPreview>;
  balanceMediaPlan(draftId: string, spec: MediaLayoutSpec): Promise<{ splitAfter: number }>;
  saveMediaPlan(request: SaveMediaPlanRequest): Promise<MediaPlan>;
  reserveMediaPlan(request: ReserveMediaRequest): Promise<MediaPlan>;
  releaseMediaPlan(request: ReleaseMediaRequest): Promise<MediaPlan>;
}
const record = (v: unknown): v is Record<string, unknown> => typeof v === 'object' && v !== null && !Array.isArray(v);
const keys = (v: Record<string, unknown>, allowed: readonly string[]): boolean => Object.keys(v).every(k => allowed.includes(k));
const integer = (v: unknown, min = 0, max = 20_000_000_000): v is number => typeof v === 'number' && Number.isSafeInteger(v) && v >= min && v <= max;
const one = (v: unknown, list: readonly string[]): boolean => typeof v === 'string' && list.includes(v);
const fingerprint = (v: unknown): v is string => typeof v === 'string' && /^[a-f0-9]{64}$/u.test(v);
function isRule(v: unknown): v is MediaTrackRule { return record(v) && keys(v, ['trackId', 'keepWithNext', 'forceSide', 'sideOpener', 'sideCloser', 'gapAfterMs']) && isCollectionId(v.trackId) && ['keepWithNext', 'sideOpener', 'sideCloser'].every(k => v[k] === undefined || typeof v[k] === 'boolean') && (v.forceSide === undefined || one(v.forceSide, ['A', 'B'])) && (v.gapAfterMs === undefined || integer(v.gapAfterMs, 0, 60_000)); }
export function isMediaLayoutSpec(v: unknown): v is MediaLayoutSpec {
  return record(v) && keys(v, ['format', 'splitAfter', 'leadInMs', 'tailMs', 'defaultGapMs', 'rules', 'compatibility']) && one(v.format, ['cassette', 'dat']) && integer(v.splitAfter, v.format === 'dat' ? 0 : 1, v.format === 'dat' ? 0 : 200) && integer(v.leadInMs, 0, 600_000) && integer(v.tailMs, 0, 600_000) && integer(v.defaultGapMs, 0, 60_000) && Array.isArray(v.rules) && v.rules.length <= 200 && v.rules.every(isRule) && new Set(v.rules.map(r => (r as MediaTrackRule).trackId)).size === v.rules.length && record(v.compatibility) && keys(v.compatibility, ['confirmed', 'cassetteTypes', 'dat']) && typeof v.compatibility.confirmed === 'boolean' && typeof v.compatibility.dat === 'boolean' && Array.isArray(v.compatibility.cassetteTypes) && v.compatibility.cassetteTypes.length <= 4 && v.compatibility.cassetteTypes.every(t => one(t, ['I', 'II', 'III', 'IV'])) && new Set(v.compatibility.cassetteTypes).size === v.compatibility.cassetteTypes.length;
}
export function isPreviewMediaRequest(v: unknown): v is PreviewMediaRequest { return record(v) && keys(v, ['draftId', 'spec', 'page']) && isCollectionId(v.draftId) && isMediaLayoutSpec(v.spec) && record(v.page) && keys(v.page, ['offset', 'limit']) && integer(v.page.offset, 0, 1_000_000) && integer(v.page.limit, 1, 100); }
export function isSaveMediaPlanRequest(v: unknown): v is SaveMediaPlanRequest { return record(v) && keys(v, ['commandId', 'draftId', 'expectedDraftRevision', 'inputFingerprint', 'spec', 'planId', 'expectedRevision']) && isCollectionId(v.commandId) && isCollectionId(v.draftId) && integer(v.expectedDraftRevision, 1) && fingerprint(v.inputFingerprint) && isMediaLayoutSpec(v.spec) && (v.planId === undefined ? v.expectedRevision === undefined : isCollectionId(v.planId) && integer(v.expectedRevision, 1)); }
export function isReserveMediaRequest(v: unknown): v is ReserveMediaRequest { return record(v) && keys(v, ['commandId', 'planId', 'expectedRevision', 'skuId', 'packaging', 'userConfirmed']) && isCollectionId(v.commandId) && isCollectionId(v.planId) && isCollectionId(v.skuId) && integer(v.expectedRevision, 1) && one(v.packaging, ['opened', 'sealed']) && v.userConfirmed === true; }
export function isReleaseMediaRequest(v: unknown): v is ReleaseMediaRequest { return record(v) && keys(v, ['commandId', 'planId', 'expectedRevision', 'userConfirmed']) && isCollectionId(v.commandId) && isCollectionId(v.planId) && integer(v.expectedRevision, 1) && v.userConfirmed === true; }
export function isMediaLayout(v: unknown): v is MediaLayout {
  return record(v) && keys(v, ['timebase', 'executionReady', 'sides', 'constraints']) && v.timebase === 'milliseconds' && v.executionReady === false && Array.isArray(v.constraints) && v.constraints.length <= 400 && v.constraints.every(c => typeof c === 'string' && c.length > 0 && c.length <= 240) && Array.isArray(v.sides) && v.sides.length >= 1 && v.sides.length <= 2 && v.sides.every(side => record(side) && keys(side, ['name', 'tracks', 'durationMs', 'musicMs', 'gapMs', 'leadInMs', 'tailMs']) && one(side.name, ['A', 'B', 'Program']) && ['durationMs', 'musicMs'].every(k => side[k] === undefined || integer(side[k])) && integer(side.gapMs) && integer(side.leadInMs) && integer(side.tailMs) && Array.isArray(side.tracks) && side.tracks.length <= 200 && side.tracks.every(t => record(t) && keys(t, ['trackId', 'startMs', 'endMs', 'gapAfterMs']) && isCollectionId(t.trackId) && (t.startMs === undefined || integer(t.startMs)) && (t.endMs === undefined || integer(t.endMs)) && integer(t.gapAfterMs, 0, 60_000)));
}
function isReservation(v: unknown): v is MediaReservation { return record(v) && keys(v, ['physicalId', 'modelId', 'skuId', 'packaging']) && isPhysicalId(v.physicalId) && isCollectionId(v.modelId) && isCollectionId(v.skuId) && one(v.packaging, ['opened', 'sealed']); }
export function isMediaPlan(v: unknown): v is MediaPlan { return record(v) && keys(v, ['id', 'draftId', 'draftRevision', 'revision', 'spec', 'layout', 'sourceBasis', 'inputFingerprint', 'reservation', 'requiresReview', 'executionReady']) && isCollectionId(v.id) && isCollectionId(v.draftId) && integer(v.draftRevision, 1) && integer(v.revision, 1) && isMediaLayoutSpec(v.spec) && isMediaLayout(v.layout) && one(v.sourceBasis, ['roon-estimate', 'verified-sources', 'unavailable']) && fingerprint(v.inputFingerprint) && (v.reservation === undefined || isReservation(v.reservation)) && typeof v.requiresReview === 'boolean' && v.executionReady === false; }
export function isMediaCandidate(v: unknown): v is MediaCandidate { return record(v) && keys(v, ['skuId', 'model', 'lengthMinutes', 'packaging', 'availableCount', 'reservableCount', 'fit', 'compatibility', 'reasons', 'status']) && isCollectionId(v.skuId) && isCollectionModel(v.model) && (v.lengthMinutes === null || integer(v.lengthMinutes, 1, 360)) && one(v.packaging, ['opened', 'sealed']) && integer(v.availableCount, 1) && integer(v.reservableCount, 0, v.availableCount as number) && one(v.fit, ['fits', 'too-short', 'unknown']) && one(v.compatibility, ['confirmed', 'unknown', 'incompatible']) && one(v.status, ['recommended', 'pending', 'excluded']) && Array.isArray(v.reasons) && v.reasons.length <= 12 && v.reasons.every(r => one(r, ['capacity-unknown', 'duration-unknown', 'too-short', 'compatibility-unknown', 'incompatible', 'collector-protected', 'sealed-protected', 'minimum-reserve', 'source-unavailable', 'layout-conflict'])); }
export function isMediaPreview(v: unknown, isPage: (value: unknown) => boolean): v is MediaPreview { return record(v) && keys(v, ['draftId', 'draftRevision', 'inputFingerprint', 'sourceBasis', 'layout', 'candidates']) && isCollectionId(v.draftId) && integer(v.draftRevision, 1) && fingerprint(v.inputFingerprint) && one(v.sourceBasis, ['roon-estimate', 'verified-sources', 'unavailable']) && isMediaLayout(v.layout) && isPage(v.candidates); }
