import { MOBILE_CODEC_LIMITS, MOBILE_COMMON_SCHEMAS, isMobileId, isMobileSource, mobileCanonicalJson, mobileDataSnapshot, mobileFailure, mobileInteger, mobileOk, mobileRecord, mobileSchemaSnapshot, mobileUtf8Bytes } from './mobile-common.js';
import type { MobileCodecLimits, MobileDecodeResult, MobileId, MobileResourceCodecContext, MobileResourceContextBasis, MobileRevision, MobileSchemaRegistry, MobileSessionScope, MobileSource } from './mobile-common.js';
import { MOBILE_CATALOG_SCHEMAS, mobileTrackIdentity, mobileTrackSelectionEquals } from './mobile-catalog.js';
import type { MobileAlbum, MobileTrack, MobileTrackSelection } from './mobile-catalog.js';
import { mobileResourceCodecContextValid } from './mobile-resource.js';

/** 类型及形状来自 sealed 26ef98 的 UI schema；权威版本、CAS 和源事实另由服务提供。 */
export type MobileUIFeatureState = "ready" | "unsupported" | "loginRequired" | "unavailable";
export type MobileUIContentCapabilities = { version:"1.0.0"; addedAlbums:MobileUIFeatureState; neteaseDailyRecommendations:MobileUIFeatureState; lyrics:MobileUIFeatureState; resourceFormatBitDepth?:boolean; resourceDsdToPcm?:boolean; neteaseLikedPlaylist?:(MobileUIFeatureState); personalFavorites?:(MobileUIFeatureState); personalPlaylists?:(MobileUIFeatureState); neteaseRecommendedPlaylists?:(MobileUIFeatureState); neteaseNewAlbums?:(MobileUIFeatureState); neteaseCharts?:(MobileUIFeatureState); neteasePersonalFM?:(MobileUIFeatureState) };
export type MobileUIAlbumRecord = (MobileAlbum) & ({ year?:number | null; audioFormat?:string | null; addedAt?:string | null });
export type MobileAddedAlbumRecord = (MobileUIAlbumRecord) & ({ source?:"local"; addedAt:string });
export type MobileAddedAlbumPage = { items:(MobileAddedAlbumRecord)[]; nextCursor:string | null; libraryRevision:string };
export type MobileDailyRecommendationFeed = { source:"netease"; recommendationDate:string; timeZone:string; feedRevision:string; items:((MobileTrack) & ({ source?:"netease" }))[] };
export type MobileLyricLine = { id:string; text:string; secondaryText?:string | null; startMs?:number | null };
interface MobileLyricsIdentity { trackId:MobileId; source:MobileSource; versionId:MobileId; contentRevision:MobileRevision }
export type MobileLyricsContent = MobileLyricsIdentity & (
  | {status:'ready';lyricRevision:MobileRevision;synchronized:boolean;lines:MobileLyricLine[]}
  | {status:'missing' | 'instrumental';lyricRevision?:null;synchronized:false;lines:[]}
);
export type MobileNeteaseLikedPlaylist = { source:"netease"; playlistId:string; accountDomain:string; playlistRevision:string; title:string; trackCount:number; artworkId?:string };
export type MobileNeteaseLikedPlaylistTrackPage = { source:"netease"; playlistId:string; accountDomain:string; playlistRevision:string; trackCount:number; items:((MobileTrack) & ({ source?:"netease" }))[]; nextCursor:string | null };
export type MobileFavoriteAlbumIdentity = { albumId:string; source:"local" | "netease" };
export type MobileFavoriteTrackSelection = { trackId:string; versionId:string; contentRevision:string; source:"local" | "netease" };
export interface MobileFavoriteAlbumRecord { album:MobileUIAlbumRecord; albumFavorite:boolean; favoriteTracks:MobileFavoriteTrackSelection[] }
export type MobileFavoriteAlbumPage = { accountDomain:string; favoritesRevision:string; items:(MobileFavoriteAlbumRecord)[]; nextCursor:string | null };
export type MobileFavoriteAlbumTrackPage = { accountDomain:string; favoritesRevision:string; favorite:(MobileFavoriteAlbumRecord) | (null); items:(MobileTrack)[]; nextCursor:string | null; identity:MobileFavoriteAlbumIdentity };
export type MobileFavoriteAlbumState = { accountDomain:string; favoritesRevision:string; identity:MobileFavoriteAlbumIdentity; favorite:(MobileFavoriteAlbumRecord) | (null) };
export type MobileSetAlbumFavoriteRequest = { source:"local" | "netease"; isFavorite:boolean; accountDomain:string; expectedRevision:string };
export type MobileSetTrackFavoriteRequest = { source:"local" | "netease"; isFavorite:boolean; accountDomain:string; expectedRevision:string; albumId:string; versionId:string; contentRevision:string };
export type MobilePersonalPlaylistIcon = "music.note" | "heart.fill" | "star.fill" | "headphones" | "sparkles" | "waveform";
export type MobilePersonalPlaylistDraft = { title:string; icon:MobilePersonalPlaylistIcon; description:string };
export interface MobilePersonalPlaylistRecord { playlistId:MobileId; title:string; icon:MobilePersonalPlaylistIcon; description:string; trackCount:number; playlistRevision:MobileRevision; coverArtworkId?:MobileId | null }
export type MobilePersonalPlaylistPage = { accountDomain:string; collectionRevision:string; items:(MobilePersonalPlaylistRecord)[]; nextCursor:string | null };
export type MobilePersonalPlaylistTrackPage = { accountDomain:string; playlist:MobilePersonalPlaylistRecord; items:(MobileTrack)[]; nextCursor:string | null };
export type MobilePersonalPlaylistReceipt = { accountDomain:string; collectionRevision:string; playlist:MobilePersonalPlaylistRecord };
export type MobileCreatePersonalPlaylistRequest = { accountDomain:string; expectedCollectionRevision:string; draft:MobilePersonalPlaylistDraft; initialTrack?:(MobileFavoriteTrackSelection) | (null) };
export type MobileAddPersonalPlaylistTrackRequest = { accountDomain:string; expectedRevision:string; selection:MobileFavoriteTrackSelection };
export type MobileDiscoveryCollectionRecord = { id:string; kind:"playlist" | "chart"; title:string; artworkId:string | null; trackCount:number; collectionRevision:string };
export type MobileDiscoveryCollectionPage = { accountDomain:string; feedRevision:string; items:(MobileDiscoveryCollectionRecord)[]; nextCursor:string | null };
export type MobileDiscoveryAlbumPage = { accountDomain:string; feedRevision:string; items:((MobileUIAlbumRecord) & ({ source?:"netease" }))[]; nextCursor:string | null };
export type MobileDiscoveryCollectionTrackPage = { accountDomain:string; collection:MobileDiscoveryCollectionRecord; items:((MobileTrack) & ({ source?:"netease" }))[]; nextCursor:string | null };
export type MobileDiscoveryFMFeed = { accountDomain:string; batchRevision:string; items:((MobileTrack) & ({ source?:"netease" }))[] };
export const MOBILE_CONTENT_SCHEMAS: MobileSchemaRegistry = {
  ...MOBILE_COMMON_SCHEMAS, ...MOBILE_CATALOG_SCHEMAS,
  UIFeatureState:{"type":"string","enum":["ready","unsupported","loginRequired","unavailable"]},
  UIContentCapabilities:{"type":"object","required":["version","addedAlbums","neteaseDailyRecommendations","lyrics"],"properties":{"version":{"const":"1.0.0"},"addedAlbums":{"$ref":"#/components/schemas/UIFeatureState"},"neteaseDailyRecommendations":{"$ref":"#/components/schemas/UIFeatureState"},"lyrics":{"$ref":"#/components/schemas/UIFeatureState"},"resourceFormatBitDepth":{"type":"boolean"},"resourceDsdToPcm":{"type":"boolean","default":false,"description":"可选且不可null，缺省false。仅真实DSD源读取、转换器和受限缓存全部可用时为true；与resourceFormatBitDepth独立，不授权源写、多档或动态切换。"},"neteaseLikedPlaylist":{"allOf":[{"$ref":"#/components/schemas/UIFeatureState"}]},"personalFavorites":{"allOf":[{"$ref":"#/components/schemas/UIFeatureState"}]},"personalPlaylists":{"allOf":[{"$ref":"#/components/schemas/UIFeatureState"}]},"neteaseRecommendedPlaylists":{"allOf":[{"$ref":"#/components/schemas/UIFeatureState"}]},"neteaseNewAlbums":{"allOf":[{"$ref":"#/components/schemas/UIFeatureState"}]},"neteaseCharts":{"allOf":[{"$ref":"#/components/schemas/UIFeatureState"}]},"neteasePersonalFM":{"allOf":[{"$ref":"#/components/schemas/UIFeatureState"}]}}},
  UIAlbumRecord:{"allOf":[{"$ref":"../openapi.yaml#/components/schemas/Album"},{"type":"object","properties":{"year":{"type":["integer","null"],"minimum":1,"maximum":9999},"audioFormat":{"type":["string","null"],"minLength":1,"maxLength":24,"x-max-utf8-bytes":24},"addedAt":{"type":["string","null"],"format":"date-time","maxLength":64}}}]},
  AddedAlbumRecord:{"allOf":[{"$ref":"#/components/schemas/UIAlbumRecord"},{"type":"object","required":["addedAt"],"properties":{"source":{"const":"local"},"addedAt":{"type":"string","format":"date-time","maxLength":64}}}]},
  AddedAlbumPage:{"type":"object","required":["items","nextCursor","libraryRevision"],"properties":{"items":{"type":"array","maxItems":100,"items":{"$ref":"#/components/schemas/AddedAlbumRecord"}},"nextCursor":{"type":["string","null"],"minLength":1,"maxLength":2048,"x-max-utf8-bytes":2048},"libraryRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"}}},
  DailyRecommendationFeed:{"type":"object","required":["source","recommendationDate","timeZone","feedRevision","items"],"properties":{"source":{"const":"netease"},"recommendationDate":{"type":"string","format":"date","pattern":"^\\d{4}-\\d{2}-\\d{2}$"},"timeZone":{"type":"string"},"feedRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"items":{"type":"array","maxItems":100,"items":{"allOf":[{"$ref":"../openapi.yaml#/components/schemas/Track"},{"properties":{"source":{"const":"netease"}}}]}}}},
  LyricLine:{"type":"object","required":["id","text"],"properties":{"id":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"text":{"type":"string","minLength":1,"maxLength":4096,"x-max-utf8-bytes":4096},"secondaryText":{"type":["string","null"],"maxLength":4096,"x-max-utf8-bytes":4096},"startMs":{"type":["integer","null"],"minimum":0}}},
  LyricsContent:{"type":"object","required":["trackId","source","versionId","contentRevision","status","synchronized","lines"],"properties":{"trackId":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"source":{"type":"string","enum":["local","netease"]},"versionId":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"contentRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"status":{"type":"string","enum":["ready","missing","instrumental"]},"lyricRevision":{"anyOf":[{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},{"type":"null"}]},"synchronized":{"type":"boolean"},"lines":{"type":"array","maxItems":2000,"items":{"$ref":"#/components/schemas/LyricLine"}}},"allOf":[{"if":{"properties":{"status":{"const":"ready"}}},"then":{"required":["lyricRevision"],"properties":{"lyricRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"lines":{"minItems":1}}},"else":{"properties":{"lyricRevision":{"type":"null"},"synchronized":{"const":false},"lines":{"maxItems":0}}}},{"if":{"properties":{"synchronized":{"const":true}}},"then":{"properties":{"lines":{"items":{"required":["startMs"],"properties":{"startMs":{"type":"integer","minimum":0}}}}}},"else":{"properties":{"lines":{"items":{"properties":{"startMs":{"type":"null"}}}}}}}]},
  NeteaseLikedPlaylist:{"type":"object","required":["source","playlistId","accountDomain","playlistRevision","title","trackCount"],"properties":{"source":{"const":"netease"},"playlistId":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"accountDomain":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"playlistRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"title":{"type":"string","minLength":1,"maxLength":1024,"x-max-utf8-bytes":1024},"trackCount":{"type":"integer","minimum":0},"artworkId":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"}}},
  NeteaseLikedPlaylistTrackPage:{"type":"object","required":["source","playlistId","accountDomain","playlistRevision","trackCount","items","nextCursor"],"properties":{"source":{"const":"netease"},"playlistId":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"accountDomain":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"playlistRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"trackCount":{"type":"integer","minimum":0},"items":{"type":"array","maxItems":100,"items":{"allOf":[{"$ref":"../openapi.yaml#/components/schemas/Track"},{"properties":{"source":{"const":"netease"}}}]}},"nextCursor":{"type":["string","null"],"minLength":1,"maxLength":2048,"x-max-utf8-bytes":2048}}},
  FavoriteAlbumIdentity:{"type":"object","required":["albumId","source"],"properties":{"albumId":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"source":{"type":"string","enum":["local","netease"]}},"additionalProperties":false},
  FavoriteTrackSelection:{"type":"object","required":["trackId","versionId","contentRevision","source"],"properties":{"trackId":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"versionId":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"contentRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"source":{"type":"string","enum":["local","netease"]}},"additionalProperties":false},
  FavoriteAlbumRecord:{"type":"object","required":["album","albumFavorite","favoriteTracks"],"properties":{"album":{"$ref":"#/components/schemas/UIAlbumRecord"},"albumFavorite":{"type":"boolean"},"favoriteTracks":{"type":"array","uniqueItems":true,"items":{"$ref":"#/components/schemas/FavoriteTrackSelection"}}},"additionalProperties":false,"allOf":[{"anyOf":[{"properties":{"albumFavorite":{"const":true}}},{"properties":{"favoriteTracks":{"minItems":1}}}]}]},
  FavoriteAlbumPage:{"type":"object","required":["accountDomain","favoritesRevision","items","nextCursor"],"properties":{"accountDomain":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"favoritesRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"items":{"type":"array","maxItems":100,"items":{"$ref":"#/components/schemas/FavoriteAlbumRecord"}},"nextCursor":{"type":["string","null"],"minLength":1,"maxLength":2048,"x-max-utf8-bytes":2048}},"additionalProperties":false},
  FavoriteAlbumTrackPage:{"type":"object","required":["accountDomain","favoritesRevision","favorite","items","nextCursor","identity"],"properties":{"accountDomain":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"favoritesRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"favorite":{"oneOf":[{"$ref":"#/components/schemas/FavoriteAlbumRecord"},{"type":"null"}]},"items":{"type":"array","maxItems":100,"items":{"$ref":"../openapi.yaml#/components/schemas/Track"}},"nextCursor":{"type":["string","null"],"minLength":1,"maxLength":2048,"x-max-utf8-bytes":2048},"identity":{"$ref":"#/components/schemas/FavoriteAlbumIdentity"}},"additionalProperties":false},
  FavoriteAlbumState:{"type":"object","required":["accountDomain","favoritesRevision","identity","favorite"],"properties":{"accountDomain":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"favoritesRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"identity":{"$ref":"#/components/schemas/FavoriteAlbumIdentity"},"favorite":{"oneOf":[{"$ref":"#/components/schemas/FavoriteAlbumRecord"},{"type":"null"}]}},"additionalProperties":false},
  SetAlbumFavoriteRequest:{"type":"object","required":["source","isFavorite","accountDomain","expectedRevision"],"properties":{"source":{"type":"string","enum":["local","netease"]},"isFavorite":{"type":"boolean"},"accountDomain":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"expectedRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"}},"additionalProperties":false},
  SetTrackFavoriteRequest:{"type":"object","required":["source","isFavorite","accountDomain","expectedRevision","albumId","versionId","contentRevision"],"properties":{"source":{"type":"string","enum":["local","netease"]},"isFavorite":{"type":"boolean"},"accountDomain":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"expectedRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"albumId":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"versionId":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"contentRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"}},"additionalProperties":false},
  PersonalPlaylistIcon:{"type":"string","enum":["music.note","heart.fill","star.fill","headphones","sparkles","waveform"]},
  PersonalPlaylistDraft:{"type":"object","required":["title","icon","description"],"properties":{"title":{"type":"string","minLength":1,"maxLength":100,"pattern":"\\S"},"icon":{"$ref":"#/components/schemas/PersonalPlaylistIcon"},"description":{"type":"string","maxLength":500}},"additionalProperties":false},
  PersonalPlaylistRecord:{"type":"object","required":["playlistId","title","icon","description","trackCount","playlistRevision"],"properties":{"playlistId":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"title":{"type":"string","minLength":1,"maxLength":100,"pattern":"\\S"},"icon":{"$ref":"#/components/schemas/PersonalPlaylistIcon"},"description":{"type":"string","maxLength":500},"trackCount":{"type":"integer","minimum":0},"playlistRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"coverArtworkId":{"type":["string","null"],"minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"}},"additionalProperties":false,"allOf":[{"if":{"properties":{"trackCount":{"const":0}},"required":["trackCount"]},"then":{"properties":{"coverArtworkId":{"type":"null"}}}}]},
  PersonalPlaylistPage:{"type":"object","required":["accountDomain","collectionRevision","items","nextCursor"],"properties":{"accountDomain":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"collectionRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"items":{"type":"array","maxItems":100,"items":{"$ref":"#/components/schemas/PersonalPlaylistRecord"}},"nextCursor":{"type":["string","null"],"minLength":1,"maxLength":2048,"x-max-utf8-bytes":2048}},"additionalProperties":false},
  PersonalPlaylistTrackPage:{"type":"object","required":["accountDomain","playlist","items","nextCursor"],"properties":{"accountDomain":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"playlist":{"$ref":"#/components/schemas/PersonalPlaylistRecord"},"items":{"type":"array","maxItems":100,"items":{"$ref":"../openapi.yaml#/components/schemas/Track"}},"nextCursor":{"type":["string","null"],"minLength":1,"maxLength":2048,"x-max-utf8-bytes":2048}},"additionalProperties":false},
  PersonalPlaylistReceipt:{"type":"object","required":["accountDomain","collectionRevision","playlist"],"properties":{"accountDomain":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"collectionRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"playlist":{"$ref":"#/components/schemas/PersonalPlaylistRecord"}},"additionalProperties":false},
  CreatePersonalPlaylistRequest:{"type":"object","required":["accountDomain","expectedCollectionRevision","draft"],"properties":{"accountDomain":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"expectedCollectionRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"draft":{"$ref":"#/components/schemas/PersonalPlaylistDraft"},"initialTrack":{"anyOf":[{"$ref":"#/components/schemas/FavoriteTrackSelection"},{"type":"null"}]}},"additionalProperties":false},
  AddPersonalPlaylistTrackRequest:{"type":"object","required":["accountDomain","expectedRevision","selection"],"properties":{"accountDomain":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"expectedRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"selection":{"$ref":"#/components/schemas/FavoriteTrackSelection"}},"additionalProperties":false},
  DiscoveryCollectionRecord:{"type":"object","required":["id","kind","title","artworkId","trackCount","collectionRevision"],"properties":{"id":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"kind":{"type":"string","enum":["playlist","chart"]},"title":{"type":"string","minLength":1,"maxLength":200,"pattern":"^(?![\\s\\S]*[\\u0000-\\u001F\\u007F-\\u009F])(?=.*\\S)[\\s\\S]+$","x-max-utf8-bytes":1024},"artworkId":{"type":["string","null"],"minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"trackCount":{"type":"integer","minimum":0},"collectionRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"}},"additionalProperties":false},
  DiscoveryCollectionPage:{"type":"object","required":["accountDomain","feedRevision","items","nextCursor"],"properties":{"accountDomain":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"feedRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"items":{"type":"array","maxItems":100,"items":{"$ref":"#/components/schemas/DiscoveryCollectionRecord"}},"nextCursor":{"type":["string","null"],"minLength":1,"maxLength":2048,"x-max-utf8-bytes":2048}},"additionalProperties":false},
  DiscoveryAlbumPage:{"type":"object","required":["accountDomain","feedRevision","items","nextCursor"],"properties":{"accountDomain":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"feedRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"items":{"type":"array","maxItems":100,"items":{"allOf":[{"$ref":"#/components/schemas/UIAlbumRecord"},{"properties":{"source":{"const":"netease"}}}]}},"nextCursor":{"type":["string","null"],"minLength":1,"maxLength":2048,"x-max-utf8-bytes":2048}},"additionalProperties":false},
  DiscoveryCollectionTrackPage:{"type":"object","required":["accountDomain","collection","items","nextCursor"],"properties":{"accountDomain":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"collection":{"$ref":"#/components/schemas/DiscoveryCollectionRecord"},"items":{"type":"array","maxItems":100,"items":{"allOf":[{"$ref":"../openapi.yaml#/components/schemas/Track"},{"properties":{"source":{"const":"netease"}}}]}},"nextCursor":{"type":["string","null"],"minLength":1,"maxLength":2048,"x-max-utf8-bytes":2048}},"additionalProperties":false},
  DiscoveryFMFeed:{"type":"object","required":["accountDomain","batchRevision","items"],"properties":{"accountDomain":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"batchRevision":{"type":"string","minLength":1,"maxLength":160,"pattern":"^[A-Za-z0-9_.:-]+(?![\\s\\S])"},"items":{"type":"array","maxItems":50,"items":{"allOf":[{"$ref":"../openapi.yaml#/components/schemas/Track"},{"properties":{"source":{"const":"netease"}}}]}}},"additionalProperties":false}
};

export interface MobileContentRequestMap {
  favoriteAlbumIdentity:MobileFavoriteAlbumIdentity; favoriteTrackSelection:MobileFavoriteTrackSelection;
  setAlbumFavorite:MobileSetAlbumFavoriteRequest; setTrackFavorite:MobileSetTrackFavoriteRequest;
  personalPlaylistDraft:MobilePersonalPlaylistDraft; createPersonalPlaylist:MobileCreatePersonalPlaylistRequest; addPersonalPlaylistTrack:MobileAddPersonalPlaylistTrackRequest;
}
export interface MobileContentResponseMap {
  uiCapabilities:MobileUIContentCapabilities; uiAlbum:MobileUIAlbumRecord; addedAlbum:MobileAddedAlbumRecord; addedAlbumPage:MobileAddedAlbumPage;
  dailyRecommendationFeed:MobileDailyRecommendationFeed; lyrics:MobileLyricsContent; neteaseLikedPlaylist:MobileNeteaseLikedPlaylist; neteaseLikedPlaylistTrackPage:MobileNeteaseLikedPlaylistTrackPage;
  favoriteAlbumRecord:MobileFavoriteAlbumRecord; favoriteAlbumPage:MobileFavoriteAlbumPage; favoriteAlbumTrackPage:MobileFavoriteAlbumTrackPage; favoriteAlbumState:MobileFavoriteAlbumState;
  personalPlaylist:MobilePersonalPlaylistRecord; personalPlaylistPage:MobilePersonalPlaylistPage; personalPlaylistTrackPage:MobilePersonalPlaylistTrackPage; personalPlaylistReceipt:MobilePersonalPlaylistReceipt;
  discoveryCollection:MobileDiscoveryCollectionRecord; discoveryCollectionPage:MobileDiscoveryCollectionPage; discoveryAlbumPage:MobileDiscoveryAlbumPage; discoveryCollectionTrackPage:MobileDiscoveryCollectionTrackPage; discoveryFMFeed:MobileDiscoveryFMFeed;
}
export const MOBILE_CONTENT_REQUEST_NAMES = {favoriteAlbumIdentity:'FavoriteAlbumIdentity',favoriteTrackSelection:'FavoriteTrackSelection',setAlbumFavorite:'SetAlbumFavoriteRequest',setTrackFavorite:'SetTrackFavoriteRequest',personalPlaylistDraft:'PersonalPlaylistDraft',createPersonalPlaylist:'CreatePersonalPlaylistRequest',addPersonalPlaylistTrack:'AddPersonalPlaylistTrackRequest'} as const;
export const MOBILE_CONTENT_RESPONSE_NAMES = {uiCapabilities:'UIContentCapabilities',uiAlbum:'UIAlbumRecord',addedAlbum:'AddedAlbumRecord',addedAlbumPage:'AddedAlbumPage',dailyRecommendationFeed:'DailyRecommendationFeed',lyrics:'LyricsContent',neteaseLikedPlaylist:'NeteaseLikedPlaylist',neteaseLikedPlaylistTrackPage:'NeteaseLikedPlaylistTrackPage',favoriteAlbumRecord:'FavoriteAlbumRecord',favoriteAlbumPage:'FavoriteAlbumPage',favoriteAlbumTrackPage:'FavoriteAlbumTrackPage',favoriteAlbumState:'FavoriteAlbumState',personalPlaylist:'PersonalPlaylistRecord',personalPlaylistPage:'PersonalPlaylistPage',personalPlaylistTrackPage:'PersonalPlaylistTrackPage',personalPlaylistReceipt:'PersonalPlaylistReceipt',discoveryCollection:'DiscoveryCollectionRecord',discoveryCollectionPage:'DiscoveryCollectionPage',discoveryAlbumPage:'DiscoveryAlbumPage',discoveryCollectionTrackPage:'DiscoveryCollectionTrackPage',discoveryFMFeed:'DiscoveryFMFeed'} as const;
function semanticContent(kind:string,raw:unknown):boolean {
  if (!mobileRecord(raw)) return false;
  const value = raw as Record<string,unknown>;
  if (kind === 'LyricsContent') {
    const lyrics = raw as unknown as MobileLyricsContent;
    if (new Set(lyrics.lines.map(line => line.id)).size !== lyrics.lines.length) return false;
    let before = -1;
    for (const line of lyrics.lines) { if (mobileUtf8Bytes(line.text) > 4096 || line.secondaryText !== undefined && line.secondaryText !== null && mobileUtf8Bytes(line.secondaryText) > 4096) return false; if (lyrics.synchronized) { if (line.startMs === undefined || line.startMs === null || line.startMs < before) return false; before = line.startMs; } }
  }
  if (kind === 'PersonalPlaylistRecord') { const p = raw as unknown as MobilePersonalPlaylistRecord; if (p.trackCount === 0 && p.coverArtworkId !== undefined && p.coverArtworkId !== null) return false; }
  if (kind === 'FavoriteAlbumRecord') { const f = raw as unknown as MobileFavoriteAlbumRecord; if (f.favoriteTracks.some(track => track.source !== f.album.source) || new Set(f.favoriteTracks.map(t => mobileCanonicalJson(t))).size !== f.favoriteTracks.length) return false; }
  if (value.favorite !== undefined && value.favorite !== null && !semanticContent('FavoriteAlbumRecord',value.favorite)) return false;
  if (mobileRecord(value.identity) && mobileRecord(value.favorite) && mobileRecord(value.favorite.album) && (value.favorite.album.id !== value.identity.albumId || value.favorite.album.source !== value.identity.source)) return false;
  const favoriteIdentity = mobileRecord(value.identity) ? value.identity : null;
  if (kind === 'FavoriteAlbumTrackPage' && favoriteIdentity && Array.isArray(value.items) && value.items.some(item => !mobileRecord(item) || item.albumId !== favoriteIdentity.albumId || item.source !== favoriteIdentity.source)) return false;
  if (value.playlist !== undefined && !semanticContent('PersonalPlaylistRecord',value.playlist)) return false;
  if (Array.isArray(value.items)) {
    const items = value.items as unknown as Record<string,unknown>[];
    if (value.nextCursor !== undefined && value.nextCursor !== null && items.length === 0) return false;
    const ids = items.map(item => Object.hasOwn(item,'versionId') ? mobileTrackIdentity(item as unknown as MobileTrack) : typeof item.id === 'string' ? `${String(item.source ?? item.kind ?? '')}:${item.id}` : typeof item.playlistId === 'string' ? item.playlistId : mobileRecord(item.album) ? `${String(item.album.source)}:${String(item.album.id)}` : '');
    if (new Set(ids).size !== ids.length) return false;
    if (kind === 'DailyRecommendationFeed' || kind === 'NeteaseLikedPlaylistTrackPage') { if (new Set(items.map(item => item.id)).size !== items.length) return false; }
    if (kind === 'PersonalPlaylistPage' && items.some(item => !semanticContent('PersonalPlaylistRecord',item)) || kind === 'FavoriteAlbumPage' && items.some(item => !semanticContent('FavoriteAlbumRecord',item))) return false;
    if (typeof value.trackCount === 'number' && items.length > value.trackCount || mobileRecord(value.playlist) && typeof value.playlist.trackCount === 'number' && items.length > value.playlist.trackCount || mobileRecord(value.collection) && typeof value.collection.trackCount === 'number' && items.length > value.collection.trackCount) return false;
  }
  if (kind === 'DailyRecommendationFeed') { try { new Intl.DateTimeFormat('en',{timeZone:value.timeZone as string}); } catch { return false; } }
  if (kind === 'NeteaseLikedPlaylist') { const title = value.title as string; if (!title.trim() || /[\u0000-\u001f\u007f-\u009f]/u.test(title)) return false; }
  return true;
}
export function mobileContentRequestSnapshot<K extends keyof MobileContentRequestMap>(kind:K,raw:unknown,limits:MobileCodecLimits = MOBILE_CODEC_LIMITS):MobileDecodeResult<MobileContentRequestMap[K]> { return mobileSchemaSnapshot(MOBILE_CONTENT_SCHEMAS[MOBILE_CONTENT_REQUEST_NAMES[kind]]!,raw,MOBILE_CONTENT_SCHEMAS,limits,'request'); }
export function mobileContentResponseSnapshot<K extends keyof MobileContentResponseMap>(kind:K,raw:unknown,limits:MobileCodecLimits = MOBILE_CODEC_LIMITS):MobileDecodeResult<MobileContentResponseMap[K]> {
  const result = mobileSchemaSnapshot<MobileContentResponseMap[K]>(MOBILE_CONTENT_SCHEMAS[MOBILE_CONTENT_RESPONSE_NAMES[kind]]!,raw,MOBILE_CONTENT_SCHEMAS,limits);
  return result.ok && !semanticContent(MOBILE_CONTENT_RESPONSE_NAMES[kind],result.value) ? mobileFailure('INVALID_RESPONSE','content') : result;
}
export const isMobileUIContentCapabilities = (raw:unknown):raw is MobileUIContentCapabilities => mobileContentResponseSnapshot('uiCapabilities',raw).ok;
export function mobileResourceContextFromCapabilities(scope:MobileSessionScope,raw:unknown,basis:MobileResourceContextBasis,limits:MobileCodecLimits = MOBILE_CODEC_LIMITS):MobileDecodeResult<MobileResourceCodecContext> {
  const caps = mobileContentResponseSnapshot('uiCapabilities',raw,limits); if (!caps.ok) return caps;
  const context:MobileResourceCodecContext = {...basis,scope,capabilityVersion:'1.0.0',resourceFormatBitDepth:caps.value.resourceFormatBitDepth ?? false,resourceDsdToPcm:caps.value.resourceDsdToPcm ?? false};
  return mobileResourceCodecContextValid(context) ? mobileOk(context) : mobileFailure('CONTEXT_MISMATCH','capabilities');
}
export function mobileUIFeature(capabilities:MobileUIContentCapabilities,key:Exclude<keyof MobileUIContentCapabilities,'version' | 'resourceFormatBitDepth' | 'resourceDsdToPcm'>):MobileUIFeatureState { return capabilities[key] ?? 'unsupported'; }

/** 同账户／修订／来源上下文来自 Owner；不是由返回正文签发认证。 */
export interface MobileContentCursorFacts { serverId:MobileId; deviceId:MobileId; accountDomain:MobileId; revision:MobileRevision; sort:string; parentId:MobileId | null; source:MobileSource | 'all' }
export interface MobileContentReadContext {
  serverId:MobileId; deviceId:MobileId; accountDomain:MobileId;
  source?:MobileSource; selection?:MobileTrackSelection; albumId?:MobileId; playlistId?:MobileId; collectionId?:MobileId; kind?:'playlist' | 'chart'; revision?:MobileRevision;
  limit?:number; pageOffset?:number; previousIdentities?:readonly string[]; previousCursors?:readonly string[]; cursorFacts?:MobileContentCursorFacts; sort?:string;
  playlistFirstTracks?:Readonly<Record<string,MobileTrack | null>>; collection?:MobileDiscoveryCollectionRecord;
  /** 收藏的完整归属关系须由目录同次读取提供，不用标题推断。 */
  trackAlbums?:Readonly<Record<string,MobileId>>;
}
export function validateMobileContentIdentity<K extends keyof MobileContentResponseMap>(kind:K,value:MobileContentResponseMap[K],context:MobileContentReadContext):MobileDecodeResult<MobileContentResponseMap[K]> {
  const captured = mobileContentResponseSnapshot(kind,value); if (!captured.ok) return captured;
  const data = captured.value as unknown as Record<string,unknown>;
  if (![context.serverId,context.deviceId,context.accountDomain].every(isMobileId) || typeof data.accountDomain === 'string' && data.accountDomain !== context.accountDomain) return mobileFailure('CONTEXT_MISMATCH','accountDomain');
  if (context.revision !== undefined) { const revision = data.favoritesRevision ?? data.collectionRevision ?? data.playlistRevision ?? data.feedRevision ?? data.batchRevision ?? data.libraryRevision ?? (mobileRecord(data.playlist) ? data.playlist.playlistRevision : undefined) ?? (mobileRecord(data.collection) ? data.collection.collectionRevision : undefined); if (revision !== undefined && revision !== context.revision) return mobileFailure('SOURCE_CHANGED','revision'); }
  if (context.source !== undefined && typeof data.source === 'string' && data.source !== context.source) return mobileFailure('SOURCE_CHANGED','source');
  if (kind === 'lyrics' && (!context.selection || !mobileTrackSelectionEquals({trackId:data.trackId as string,source:data.source as MobileSource,versionId:data.versionId as string,contentRevision:data.contentRevision as string},context.selection))) return mobileFailure('SOURCE_CHANGED','selection');
  const identity = mobileRecord(data.identity) ? data.identity : null;
  if (identity && (context.albumId !== undefined && identity.albumId !== context.albumId || context.source !== undefined && identity.source !== context.source)) return mobileFailure('SOURCE_CHANGED','identity');
  if (context.playlistId !== undefined && (typeof data.playlistId === 'string' ? data.playlistId : mobileRecord(data.playlist) ? data.playlist.playlistId : undefined) !== context.playlistId) return mobileFailure('SOURCE_CHANGED','playlistId');
  if (context.collectionId !== undefined && (!mobileRecord(data.collection) || data.collection.id !== context.collectionId || context.kind !== undefined && data.collection.kind !== context.kind)) return mobileFailure('SOURCE_CHANGED','collection');
  if (context.collection && (!mobileRecord(data.collection) || mobileCanonicalJson(context.collection) !== mobileCanonicalJson(data.collection))) return mobileFailure('SOURCE_CHANGED','collection');
  if (context.cursorFacts) { const f = context.cursorFacts; if (f.serverId !== context.serverId || f.deviceId !== context.deviceId || f.accountDomain !== context.accountDomain || f.revision !== context.revision || f.sort !== context.sort || f.parentId !== (context.albumId ?? context.playlistId ?? context.collectionId ?? null) || f.source !== (context.source ?? 'all')) return mobileFailure('CONTEXT_MISMATCH','cursor'); }
  const validatePlaylist = (playlist:MobilePersonalPlaylistRecord):boolean => {
    if (playlist.trackCount === 0) return playlist.coverArtworkId === undefined || playlist.coverArtworkId === null;
    if (!context.playlistFirstTracks || !Object.hasOwn(context.playlistFirstTracks,playlist.playlistId)) return true;
    const first = context.playlistFirstTracks[playlist.playlistId]; return first !== undefined && first !== null && (playlist.coverArtworkId ?? null) === (first.artworkId ?? null);
  };
  if (kind === 'personalPlaylist' && !validatePlaylist(captured.value as MobilePersonalPlaylistRecord) || mobileRecord(data.playlist) && !validatePlaylist(data.playlist as unknown as MobilePersonalPlaylistRecord)) return mobileFailure('CONTEXT_MISMATCH','coverArtworkId');
  if (Array.isArray(data.items)) {
    const items = data.items as Record<string,unknown>[];
    if (context.limit !== undefined && items.length > context.limit || typeof data.nextCursor === 'string' && context.previousCursors?.includes(data.nextCursor)) return mobileFailure('CONTEXT_MISMATCH','cursor');
    if (kind === 'personalPlaylistPage' && items.some(item => !validatePlaylist(item as unknown as MobilePersonalPlaylistRecord))) return mobileFailure('CONTEXT_MISMATCH','coverArtworkId');
    const ids = items.map(item => Object.hasOwn(item,'versionId') ? mobileTrackIdentity(item as unknown as MobileTrack) : `${String(item.source ?? item.kind ?? '')}:${String(item.id ?? item.playlistId ?? (mobileRecord(item.album) ? item.album.id : ''))}`);
    if (context.previousIdentities && ids.some(id => context.previousIdentities!.includes(id))) return mobileFailure('CONTEXT_MISMATCH','items');
    if (items.some(item => typeof item.albumId === 'string' && context.albumId !== undefined && item.albumId !== context.albumId || typeof item.source === 'string' && context.source !== undefined && item.source !== context.source)) return mobileFailure('SOURCE_CHANGED','items');
    const total = data.trackCount ?? (mobileRecord(data.playlist) ? data.playlist.trackCount : undefined) ?? (mobileRecord(data.collection) ? data.collection.trackCount : undefined);
    if (context.pageOffset !== undefined && typeof total === 'number' && (context.pageOffset + items.length > total || data.nextCursor === null && context.pageOffset + items.length !== total)) return mobileFailure('SOURCE_CHANGED','trackCount');
  }
  const favorites = (data.favorite === null ? [] : mobileRecord(data.favorite) ? [data.favorite] : kind === 'favoriteAlbumRecord' ? [data] : kind === 'favoriteAlbumPage' && Array.isArray(data.items) ? data.items as Record<string,unknown>[] : []);
  for (const favorite of favorites) { const album = favorite.album; if (context.trackAlbums && mobileRecord(album) && Array.isArray(favorite.favoriteTracks) && favorite.favoriteTracks.some(track => mobileRecord(track) && context.trackAlbums![mobileCanonicalJson(track)] !== album.id)) return mobileFailure('CONTEXT_MISMATCH','favoriteTracks'); }
  return captured;
}

export type MobileContentMutation = MobileSetAlbumFavoriteRequest | MobileSetTrackFavoriteRequest | MobileCreatePersonalPlaylistRequest | MobileAddPersonalPlaylistTrackRequest;
export interface MobileContentMutationContext { accountDomain:MobileId; revision:MobileRevision; source?:MobileSource; selection?:MobileTrackSelection; albumId?:MobileId }
export function validateMobileContentCas(raw:MobileContentMutation,context:MobileContentMutationContext):MobileDecodeResult<MobileContentMutation> {
  const captured = mobileDataSnapshot(raw, MOBILE_CODEC_LIMITS,'request'); if (!captured.ok || !mobileRecord(captured.value)) return mobileFailure('INVALID_REQUEST','mutation');
  const data = captured.value;
  const kind = Object.hasOwn(data,'draft') ? 'createPersonalPlaylist' : Object.hasOwn(data,'selection') ? 'addPersonalPlaylistTrack' : Object.hasOwn(data,'albumId') ? 'setTrackFavorite' : 'setAlbumFavorite';
  const typed = mobileContentRequestSnapshot(kind,data); if (!typed.ok) return typed;
  if (!isMobileId(context.accountDomain) || !isMobileId(context.revision) || data.accountDomain !== context.accountDomain) return mobileFailure('CONTEXT_MISMATCH','accountDomain');
  if ((data.expectedCollectionRevision ?? data.expectedRevision) !== context.revision) return mobileFailure('REVISION_CONFLICT','expectedRevision');
  const selection = mobileRecord(data.selection) ? data.selection : mobileRecord(data.initialTrack) ? data.initialTrack : null;
  if (context.source !== undefined && (data.source ?? selection?.source) !== context.source || context.albumId !== undefined && data.albumId !== undefined && data.albumId !== context.albumId) return mobileFailure('SOURCE_CHANGED','source');
  if (context.selection && !mobileTrackSelectionEquals(selection === null ? {trackId:context.selection.trackId,source:data.source as MobileSource,versionId:data.versionId as string,contentRevision:data.contentRevision as string} : selection as unknown as MobileTrackSelection,context.selection)) return mobileFailure('SOURCE_CHANGED','selection');
  return mobileOk(typed.value);
}
export function mapMobilePersonalPlaylistDraft(raw:MobilePersonalPlaylistDraft):MobileDecodeResult<MobilePersonalPlaylistDraft> {
  const captured = mobileContentRequestSnapshot('personalPlaylistDraft',raw); if (!captured.ok) return captured;
  return mobileContentRequestSnapshot('personalPlaylistDraft',{title:captured.value.title.trim(),icon:captured.value.icon,description:captured.value.description.trim()});
}
export interface MobilePersonalPlaylistProjection { playlist:MobilePersonalPlaylistRecord; firstTrack:MobileTrack | null }
export function mapMobilePersonalPlaylist(projection:MobilePersonalPlaylistProjection):MobileDecodeResult<MobilePersonalPlaylistRecord> {
  const p = mobileDataSnapshot(projection); if (!p.ok || !mobileRecord(p.value)) return mobileFailure('INVALID_RESPONSE','playlist');
  const value = p.value as unknown as MobilePersonalPlaylistProjection;
  const record = mobileContentResponseSnapshot('personalPlaylist',value.playlist); if (!record.ok) return record;
  if (record.value.trackCount > 0 && value.firstTrack === null || record.value.trackCount === 0 && value.firstTrack !== null) return mobileFailure('CONTEXT_MISMATCH','firstTrack');
  const playlist = record.value;
  return mobileContentResponseSnapshot('personalPlaylist',{playlistId:playlist.playlistId,title:playlist.title,icon:playlist.icon,description:playlist.description,trackCount:playlist.trackCount,playlistRevision:playlist.playlistRevision,coverArtworkId:value.firstTrack?.artworkId ?? null});
}
export type MobileLyricsProjection = MobileLyricsContent;
export function mapMobileLyrics(projection:MobileLyricsProjection):MobileDecodeResult<MobileLyricsContent> { return mobileContentResponseSnapshot('lyrics',projection); }
