import assert from 'node:assert/strict';import test from 'node:test';import {DatabaseSync} from 'node:sqlite';import {mkdtemp,readFile,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {createCollectionRepository} from '../src/collection/repository.js';
const facts=(db:DatabaseSync,names:string[])=>names.map(name=>[name,db.prepare(`SELECT * FROM "${name}" ORDER BY rowid`).all()]);
async function fixture(t:test.TestContext){const directory=await mkdtemp(path.join(os.tmpdir(),'musicbridge-print-migration-'));t.after(()=>rm(directory,{recursive:true,force:true}));const filePath=path.join(directory,'collection.sqlite'),db=new DatabaseSync(filePath);db.exec(await readFile(new URL('fixtures/collection-schema20-completed.sql',import.meta.url),'utf8'));assert.equal(db.prepare('PRAGMA user_version').get()!.user_version,20);const names=db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT GLOB 'sqlite_*' ORDER BY name").all().map(r=>String(r.name));const before=facts(db,names);db.close();return {filePath,names,before};}
test('真实20旧v1档案及全部旧列迁移21不变、不自动backfill',async t=>{const f=await fixture(t),repo=createCollectionRepository({filePath:f.filePath});t.after(()=>repo.close());repo.list({offset:0,limit:1});const db=new DatabaseSync(f.filePath);t.after(()=>db.close());assert.equal(db.prepare('PRAGMA user_version').get()!.user_version,21);assert.deepEqual(facts(db,f.names),f.before);assert.equal(db.prepare('SELECT count(*) n FROM recording_print_jobs').get()!.n,0);assert.deepEqual(db.prepare('PRAGMA foreign_key_check').all(),[]);});
test('21迁移提交故障回滚全部新表与schema，原20事实逐列保持后可重试',async t=>{const f=await fixture(t),repo=createCollectionRepository({filePath:f.filePath,beforeCommit(action){if(action==='migrate-recording-prints')throw new Error('合成迁移失败');}});assert.throws(()=>repo.list({offset:0,limit:1}));repo.close();const db=new DatabaseSync(f.filePath);assert.equal(db.prepare('PRAGMA user_version').get()!.user_version,20);assert.deepEqual(facts(db,f.names),f.before);assert.equal(db.prepare("SELECT count(*) n FROM sqlite_schema WHERE name LIKE 'recording_print%'").get()!.n,0);db.close();const retry=createCollectionRepository({filePath:f.filePath});retry.list({offset:0,limit:1});retry.close();});
test('损坏旧20当前内容不能先迁移为21再报错，拒绝时schema和旧列保持',async t=>{
 const f=await fixture(t),db=new DatabaseSync(f.filePath);const trigger=String(db.prepare("SELECT sql FROM sqlite_schema WHERE name='recording_record_current_no_delete'").get()!.sql);db.exec('DROP TRIGGER recording_record_current_no_delete;DELETE FROM recording_record_current;');db.exec(trigger);const before=facts(db,f.names);db.close();
 const repo=createCollectionRepository({filePath:f.filePath});assert.throws(()=>repo.list({offset:0,limit:1}));repo.close();const after=new DatabaseSync(f.filePath);t.after(()=>after.close());assert.equal(after.prepare('PRAGMA user_version').get()!.user_version,20);assert.deepEqual(facts(after,f.names),before);
});
