<script setup lang="ts">
import {nextTick,onBeforeUnmount,onMounted,ref,shallowRef} from 'vue'
import type {MasterVersion} from '@music-bridge/contracts'
import {createMasterArtworkController} from './master-artwork-controller'
const props=defineProps<{master:MasterVersion}>(),emit=defineEmits<{close:[]}>(),dialog=ref<HTMLDialogElement>(),heading=ref<HTMLElement>()
const controller=createMasterArtworkController({api:window.musicBridge,master:props.master,onChange:()=>{state.value={...controller.state}}}),state=shallowRef({...controller.state});let disposed=false
async function act(operation:()=>void|Promise<void>){const origin=document.activeElement;await operation();await nextTick();if(!disposed&&document.activeElement===document.body&&origin)heading.value?.focus({preventScroll:true})}
function close(){if(controller.canClose()){controller.dispose();emit('close')}}
onMounted(()=>{dialog.value?.showModal();heading.value?.focus();void controller.refresh()});onBeforeUnmount(()=>{disposed=true;controller.dispose()})
</script>
<template>
 <dialog ref="dialog" class="print-dialog" aria-label="母版 Artwork" data-testid="master-artwork-panel" @cancel.prevent="close" @close="close">
  <header><h2 ref="heading" tabindex="-1">母版 Artwork</h2><button type="button" :disabled="!controller.canClose()" @click="close">关闭 Artwork</button></header>
  <h3>M{{master.sequence}} · {{master.title}}</h3><p>明确母版 <code>{{master.id}}</code></p><p class="notice">Artwork 属于本份冻结母版。保存新版本不改变旧录音或印刷文件；实物照片不会自动成为 Artwork。</p>
  <p v-if="state.phase==='loading'" role="status">正在读取本母版 Artwork…</p><p v-if="state.phase==='ready'&&!state.current">本母版没有已保存的 Artwork。</p>
  <figure v-if="state.image&&!state.imageFailed"><img class="print-preview" :src="state.image.dataUrl" :width="state.image.width" :height="state.image.height" alt="本母版当前已保存的 Artwork" @error="controller.imageFailed"><figcaption>已保存第 {{state.current?.sequence}} 版 · {{state.current?.createdAt}}</figcaption></figure>
  <button type="button" :disabled="state.phase==='loading'||state.saving||state.picking||!!state.pending" @click="act(controller.refresh)">重新读取 Artwork</button>
  <button type="button" :disabled="state.phase==='loading'||state.saving||state.picking||!!state.pending" @click="act(controller.pick)">{{state.picking?'等待选择图片…':'选择本地 Artwork'}}</button>
  <section v-if="state.staged"><h3>尚未保存的新 Artwork</h3><figure v-if="!state.imageFailed"><img class="print-preview" :src="state.staged.dataUrl" :width="state.staged.width" :height="state.staged.height" alt="尚未保存的母版 Artwork 应用副本" @error="controller.imageFailed"></figure><p>等比例 JPEG 应用副本；不裁剪或修改源文件。</p><label class="print-confirmation"><input type="checkbox" :checked="state.confirmed" :disabled="state.saving||!!state.pending" @change="controller.setConfirmed(($event.target as HTMLInputElement).checked)">我确认把此图保存为这份母版的新 Artwork 版本</label><div class="actions"><button type="button" :disabled="!state.confirmed||state.phase!=='ready'||state.imageFailed||state.saving||!!state.pending" @click="act(controller.save)">保存为新的 Artwork 版本</button><button type="button" :disabled="state.saving||!!state.pending" @click="controller.discard">放弃未保存图片</button></div></section>
  <div v-if="state.pending" class="notice"><p>原保存回执尚未确认；以下操作保留原母版、图片与命令身份。</p><button type="button" :disabled="state.saving" @click="act(controller.retryPending)">重试原保存操作</button><button type="button" :disabled="state.saving" @click="controller.abandonPending">停止本地重试</button></div>
  <p v-if="state.error" role="alert">{{state.error}}</p><p v-if="state.notice" role="status" aria-live="polite">{{state.notice}}</p>
  <details v-if="state.current"><summary>查看已保存版本摘要</summary><p>版本 <code>{{state.current.id}}</code> · {{state.current.width}} × {{state.current.height}} 像素</p><p>JPEG {{state.current.size.toLocaleString('zh-CN')}} 字节 · SHA-256 <code>{{state.current.sha256}}</code></p></details>
 </dialog>
</template>
<style scoped>
.print-dialog{box-sizing:border-box;width:min(880px,calc(100vw - 32px));max-height:calc(100vh - 32px);padding:24px;overflow:auto;border:1px solid var(--mb-glass-border);border-radius:14px;background:var(--mb-bg-base);color:var(--mb-text-primary)}.print-dialog::backdrop{background:#0009}header{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;flex-wrap:wrap}h2,h3,p,figcaption,button,code{min-width:0;overflow-wrap:anywhere}h2{font-size:24px;margin:0 0 16px}h3{font-size:18px}p,figcaption,label{font-size:14px;line-height:1.75}.notice{border-left:3px solid var(--mb-accent);padding-left:14px;margin:18px 0}button{min-height:44px;max-width:100%;box-sizing:border-box;margin:8px 8px 8px 0;padding:10px 12px;border:1px solid var(--mb-glass-border);border-radius:8px;background:var(--mb-bg-base);color:var(--mb-text-primary);font:inherit;font-size:14px;cursor:pointer}button:disabled{opacity:.5;cursor:not-allowed}.actions{display:flex;flex-wrap:wrap;gap:8px}figure{margin:16px 0;min-width:0}img{display:block;max-width:100%;max-height:300px;width:auto;height:auto;object-fit:contain}label{display:flex;align-items:flex-start;gap:10px}input{margin-top:6px}summary{min-height:44px;padding:12px 0;box-sizing:border-box;cursor:pointer}code{font-size:12px;white-space:normal}:focus-visible{outline:2px solid var(--mb-accent);outline-offset:3px}@media(max-width:600px){.print-dialog{padding:16px}}
.print-dialog .print-confirmation{display:flex;flex-direction:row;align-items:flex-start;gap:10px;min-height:44px}.print-dialog .print-confirmation input{box-sizing:border-box;width:18px;min-width:18px;max-width:18px;height:18px;min-height:18px;max-height:18px;padding:0;flex:0 0 18px;accent-color:var(--mb-accent)}.print-dialog .print-preview{max-height:300px;max-width:100%;width:auto;height:auto;object-fit:contain}
</style>
