<script setup lang="ts">
import {nextTick,onBeforeUnmount,onMounted,ref,shallowRef} from 'vue'
import type {RecordingRecordDetail} from '@music-bridge/contracts'
import {createRecordingPrintController} from './recording-print-controller'
const props=defineProps<{detail:RecordingRecordDetail}>(),emit=defineEmits<{close:[]}>(),dialog=ref<HTMLDialogElement>(),heading=ref<HTMLElement>()
const controller=createRecordingPrintController({api:window.musicBridge,detail:props.detail,onChange:()=>{state.value={...controller.state}}}),state=shallowRef({...controller.state});let disposed=false
const labels={pending:'等待自动生成',rendering:'正在生成',failed:'生成失败',ready:'印刷文件已生成'},errors={RENDER_FAILED:'渲染失败',LAYOUT_OVERFLOW:'内容超过本模板容量',RENDER_TIMEOUT:'生成超时',OBJECT_LIMIT:'保存空间预算不足'}
async function act(operation:()=>void|Promise<void>){const origin=document.activeElement;await operation();await nextTick();if(!disposed&&document.activeElement===document.body&&origin)heading.value?.focus({preventScroll:true})}
function close(){if(controller.canClose()){controller.dispose();emit('close')}}
onMounted(()=>{dialog.value?.showModal();heading.value?.focus();void controller.refresh()});onBeforeUnmount(()=>{disposed=true;controller.dispose()})
</script>
<template>
 <dialog ref="dialog" class="print-dialog" aria-label="J-Card 与印刷文件" data-testid="recording-print-panel" @cancel.prevent="close" @close="close">
  <header><h2 ref="heading" tabindex="-1">J-Card 与印刷文件</h2><button type="button" :disabled="!controller.canClose()" @click="close">关闭印刷文件</button></header>
  <h3>{{detail.plan.master.title}}</h3><p>录音档案 <code>{{detail.record.id}}</code> · 实体 {{detail.record.completion.physicalId}}</p><p>历史完成日期 {{detail.record.completion.endedAt}}；不使用今天的型号或 Artwork 补填历史。</p>
  <div class="notice"><p>文件已生成不表示纸张已打印或已装盒。本页不操作打印机；后续改图或模板不改变旧印刷文件。</p><p v-if="detail.record.visuals.artwork.state==='not-captured'">此历史录音未保存 Artwork；实物照片不会替代它。</p></div>
  <p v-if="detail.plan.layout.spec.format==='dat'">DAT 连续节目不适用 Cassette J-Card；不会伪造 A/B 面。</p>
  <p v-else-if="detail.record.schemaVersion===1">此旧档案没有完成时自动打印请求。可依据现有历史事实补建，原缺失状态与档案 Hash 保持不变。</p>
  <p v-else>基础卡片在录音完成时自动排队；读取本页不会重新生成文件。</p>
  <button type="button" :disabled="state.listPhase==='loading'||!controller.canClose()" @click="act(()=>controller.refresh())">刷新印刷文件</button>
  <p v-if="state.listPhase==='loading'" role="status">正在读取印刷文件…</p><p v-if="state.page&&!state.page.total">尚无印刷文件请求。</p>
  <ol v-if="state.page" class="jobs"><li v-for="job in state.page.items" :key="job.id"><h3>{{labels[job.state]}}</h3><p>{{job.request.origin==='completion'?'完成时自动请求':'依据旧档案后补'}} · {{job.request.templateId}} · 修订 {{job.revision}}</p><p v-if="job.errorCode">{{errors[job.errorCode]}}；录音档案仍已保存，重试不重新录音。</p><button v-if="job.artifactId" type="button" :disabled="!controller.canClose()" :aria-label="`查看印刷文件 ${job.artifactId}`" @click="act(()=>controller.select(job.artifactId!))">查看印刷文件 {{job.artifactId}}</button><button v-if="job.state==='failed'" type="button" :disabled="!state.confirmed||!controller.canClose()" @click="act(()=>controller.retry(job.id))">重试生成原卡片</button></li></ol>
  <nav v-if="state.page" class="actions" aria-label="印刷文件分页"><button type="button" :disabled="!state.page.offset||state.listPhase==='loading'||!controller.canClose()" @click="act(()=>controller.refresh(state.page!.offset-25))">上一页印刷文件</button><button type="button" :disabled="!state.page.hasMore||state.listPhase==='loading'||!controller.canClose()" @click="act(()=>controller.refresh(state.page!.offset+25))">下一页印刷文件</button></nav>
  <section v-if="detail.plan.layout.spec.format==='cassette'"><label class="print-confirmation"><input type="checkbox" :checked="state.confirmed" :disabled="!controller.canClose()" @change="controller.setConfirmed(($event.target as HTMLInputElement).checked)">我确认仅按本次历史事实补建或重试原打印请求，不改写录音档案</label><button v-if="detail.record.schemaVersion===1" type="button" :disabled="!state.confirmed||!controller.canClose()" @click="act(controller.request)">依据现有历史事实补建基础卡片</button></section>
  <div v-if="state.pending" class="notice"><p>打印操作回执尚未确认；保留原命令与事实身份。</p><button type="button" :disabled="state.sending" @click="act(controller.retryPending)">重试原打印操作</button><button type="button" :disabled="state.sending" @click="controller.abandonPending">停止本地重试</button></div>
  <p v-if="state.error" role="alert">{{state.error}}</p><p v-if="state.detailPhase==='loading'" role="status">正在读取所选印刷文件与预览…</p><p v-if="state.detailError" role="alert">{{state.detailError}} <button type="button" :disabled="!controller.canClose()" @click="act(()=>controller.select(state.selectedId))">重试此印刷文件</button></p>
  <section v-if="state.result&&state.detailPhase==='ready'" data-testid="recording-print-detail"><h3>所选历史印刷文件</h3><p>JP0 · {{state.result.artifact.geometry.widthMm}} × {{state.result.artifact.geometry.heightMm}} mm · {{state.result.artifact.pageCount}} 页。续页与卡面尺寸相同，不表示一张卡能容纳所有内容。</p><figure><img class="print-preview" :src="state.result.preview.dataUrl" :width="state.result.preview.width" :height="state.result.preview.height" alt="所选历史 J-Card 的排版预览" @error="controller.previewFailed"><figcaption>排版预览；不是对实际 PDF 的独立核验。</figcaption></figure><h4>{{state.result.facts.title}}</h4><p>脊文字：{{state.result.facts.spine}} · 完成日期 {{state.result.facts.displayDateUtc}} UTC</p><p>历史型号：{{state.result.facts.tapeModel.state==='known'?`${state.result.facts.tapeModel.descriptor.brand} ${state.result.facts.tapeModel.descriptor.name}`:'未知'}}</p><section v-for="side in state.result.facts.sides" :key="side.side"><h4>{{side.side}} 面 · {{(side.durationMs/1000).toLocaleString('zh-CN')}} 秒（实际整面）</h4><p v-if="!side.tracks.length">空面，无曲目。</p><ol><li v-for="track in side.tracks" :key="track.trackId">{{track.position}} · {{track.title}} · {{track.artist??'艺术家未知'}}</li></ol></section><button type="button" :disabled="!controller.canClose()" @click="act(controller.exportPdf)">导出 PDF</button><details><summary>查看文件与冻结输入摘要</summary><p>Artifact <code>{{state.result.artifact.id}}</code></p><p>PDF SHA-256 <code>{{state.result.artifact.pdfSha256}}</code> · {{state.result.artifact.size.toLocaleString('zh-CN')}} 字节</p><p>输入 Hash <code>{{state.result.artifact.inputHash}}</code></p></details></section>
  <p v-if="state.notice" role="status" aria-live="polite">{{state.notice}}</p>
 </dialog>
</template>
<style scoped>
.print-dialog{box-sizing:border-box;width:min(880px,calc(100vw - 32px));max-height:calc(100vh - 32px);padding:24px;overflow:auto;border:1px solid var(--mb-glass-border);border-radius:14px;background:var(--mb-bg-base);color:var(--mb-text-primary)}.print-dialog::backdrop{background:#0009}header{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;flex-wrap:wrap}h2,h3,p,li,figcaption,button,code{min-width:0;overflow-wrap:anywhere}h2{font-size:24px;margin:0 0 16px}h3{font-size:18px}p,li,figcaption,label{font-size:14px;line-height:1.75}.notice{border-left:3px solid var(--mb-accent);padding-left:14px;margin:18px 0}button{min-height:44px;max-width:100%;box-sizing:border-box;margin:8px 8px 8px 0;padding:10px 12px;border:1px solid var(--mb-glass-border);border-radius:8px;background:var(--mb-bg-base);color:var(--mb-text-primary);font:inherit;font-size:14px;cursor:pointer}button:disabled{opacity:.5;cursor:not-allowed}.actions{display:flex;flex-wrap:wrap;gap:8px}.jobs{list-style:none;padding:0}.jobs>li{border-bottom:1px solid var(--mb-glass-border);padding:12px 0}figure{margin:16px 0;min-width:0}img{display:block;max-width:100%;max-height:360px;width:auto;height:auto;object-fit:contain}label{display:flex;align-items:flex-start;gap:10px}input{margin-top:6px}summary{min-height:44px;padding:12px 0;box-sizing:border-box;cursor:pointer}code{font-size:12px;white-space:normal}:focus-visible{outline:2px solid var(--mb-accent);outline-offset:3px}@media(max-width:600px){.print-dialog{padding:16px}}
.print-dialog .print-confirmation{display:flex;flex-direction:row;align-items:flex-start;gap:10px;min-height:44px}.print-dialog .print-confirmation input{box-sizing:border-box;width:18px;min-width:18px;max-width:18px;height:18px;min-height:18px;max-height:18px;padding:0;flex:0 0 18px;accent-color:var(--mb-accent)}.print-dialog .print-preview{max-height:360px;max-width:100%;width:auto;height:auto;object-fit:contain}
</style>
