import { withLocalFactsMutation } from '../stream/local-source-fence.js';
import {randomUUID} from 'node:crypto';
import path from 'node:path';
import * as dto from '@music-bridge/contracts';
import type {CollectionRepository} from './repository.js';
import {sourceRootAvailability,sourceRelativePath,readonlySourceCandidateMetadata,type RootCapability} from '../recording/source-files.js';

interface Captured {selection:dto.LocalRelocationSelection;relative:string;signature:string;sourceRootId:string;rootId:string;view:dto.LocalRelocationCandidate}
/** 只有原SourceStore给出许可；候选缓存不赋予新许可，冷恢复仅查询原catalog持久回执。 */
export function createLocalRelocationCoordinator(options:{repository:CollectionRepository;assertCurrent():void;assertReady?():void;beforeMutation?():Promise<void>}){
 const catalog=options.repository.localCatalog,candidates=new Map<string,Captured>();let closed=false;
 function check(){options.assertCurrent();options.assertReady?.();if(closed)throw new Error('重定位owner已关闭。');}
 function source(id:string):RootCapability{const s=options.repository.sources.root(id);if(!s||s.id!==id||typeof s.path!=='string'||!path.isAbsolute(s.path)||typeof s.authorized!=='boolean'||typeof s.label!=='string'||!['dev','ino'].every(k=>typeof s[k as 'dev'|'ino']==='string'&&/^(0|[1-9][0-9]{0,31}|-[1-9][0-9]{0,30})$/u.test(s[k as 'dev'|'ino'])))throw new Error('SourceStore根结构无效。');return s;}
 async function online(id:string){const s=source(id);if(await sourceRootAvailability(s)!=='ONLINE')throw new Error('源目录离线或许可已撤销，现有对象保留。');check();return s;}
 const overlap=(a:string,b:string)=>a===b||a.startsWith(b+path.sep)||b.startsWith(a+path.sep);
 function outsideOtherRoots(cap:RootCapability,except?:string){for(const root of catalog.roots()){if(root.id===except)continue;const existing=source(root.sourceRootId);if(overlap(cap.path,existing.path))throw new Error('库根重叠会产生多个独立候选，不能自动合并。');}}
 function locate(selection:dto.LocalRelocationSelection){const found=catalog.privateAssetLocator(selection.assetId),root=catalog.root(found.asset.libraryRootId);if(found.asset.fileRevision!==selection.expectedFileRevision||found.asset.locationRevision!==selection.expectedLocationRevision||root.revision!==selection.expectedRootRevision||found.asset.sourceRootId!==root.sourceRootId||found.asset.rootRevision!==root.revision)throw new Error('资产或根关联已改变，请重新捕获候选。');if(catalog.privateAssetHasExactEvidence(found.asset.id))throw new Error('精确录音/片段资产需要原严格证据重定位，不接受普通扫描候选。');return {...found,root};}
 const sameSelection=(a:dto.LocalRelocationSelection,b:dto.LocalRelocationSelection)=>a.assetId===b.assetId&&a.expectedFileRevision===b.expectedFileRevision&&a.expectedLocationRevision===b.expectedLocationRevision&&a.expectedRootRevision===b.expectedRootRevision;
 return {
  async roots():Promise<dto.LocalRootView[]>{check();const result=[];for(const root of catalog.roots()){const cap=source(root.sourceRootId);result.push({root,label:cap.label,availability:await sourceRootAvailability(cap)});}check();if(!dto.isLocalRelocationCommandResult('localRelocation.roots',result))throw new Error('本地根公开结果无效。');return result;},
  async registerRoot(request:dto.LocalRelocationCommandPayloads['localRelocation.registerRoot']){check();if(!dto.isLocalRelocationCommandPayload('localRelocation.registerRoot',request))throw new Error('根注册请求无效。');const prior=catalog.privateReceiptRequest(request.commandId);if(prior){if(prior.operation!=='register-root'||prior.request.sourceRootId!==request.sourceRootId||prior.request.role!=='library'||!dto.isLibraryRoot(prior.result))throw new Error('操作编号不能复用其他根注册请求。');return prior.result;}const cap=await online(request.sourceRootId);outsideOtherRoots(cap);await options.beforeMutation?.();check();return catalog.registerRoot({...request,role:'library'});},
  async capture(request:dto.LocalRelocationCommandPayloads['localRelocation.capture']):Promise<dto.LocalRelocationCandidates>{check();if(!dto.isLocalRelocationCommandPayload('localRelocation.capture',request))throw new Error('可信候选请求无效。');if(candidates.size+request.absolutePaths.length>200)throw new Error('候选缓存达到200，需要重新打开工作库后再捕获。');const {asset,root}=locate(request),cap=await online(root.sourceRootId);const existing=options.repository.localScan.privateFileState(root.id,catalog.privateAssetLocator(asset.id).relative);const result:dto.LocalRelocationCandidates={assetId:asset.id,candidates:[]},pending:Captured[]=[];
   for(const absolute of request.absolutePaths){const relative=sourceRelativePath(cap,absolute).split(path.sep).join('/');const metadata=await readonlySourceCandidateMetadata(cap,relative);check();const label=relative.split('/').join(' › ');const view:dto.LocalRelocationCandidate={id:randomUUID(),fileName:path.basename(relative),relativeLabel:label,size:metadata.size,modifiedAt:metadata.modifiedAt,evidence:existing?.value.signature.split(':').slice(0,4).join(':')===metadata.signature.split(':').slice(0,4).join(':')?'same-inode-observation':'user-choice'};if(!dto.isLocalRelocationCandidates({assetId:asset.id,candidates:[view]}))throw new Error('候选标签超出公开预算，未截断。');pending.push({selection:{assetId:asset.id,expectedFileRevision:asset.fileRevision,expectedLocationRevision:asset.locationRevision,expectedRootRevision:root.revision},relative,signature:metadata.signature,sourceRootId:cap.id,rootId:root.id,view});result.candidates.push(view);}
   locate(request);for(const entry of pending)candidates.set(entry.view.id,entry);return result;
  },
  async confirm(request:dto.LocalRelocationConfirm):Promise<dto.AudioAsset>{check();if(!dto.isLocalRelocationConfirm(request))throw new Error('必须明确确认逻辑候选。');const prior=catalog.privateReceiptRequest(request.commandId);if(prior){if((prior.operation!=='move-asset'&&prior.operation!=='replace-asset')||prior.request.assetId!==request.assetId||prior.request.expectedLocationRevision!==request.expectedLocationRevision||prior.request.expectedRootRevision!==request.expectedRootRevision||!dto.isAudioAsset(prior.result)||(prior.operation==='move-asset'?prior.result.fileRevision!==request.expectedFileRevision:prior.request.expectedFileRevision!==request.expectedFileRevision))throw new Error('同操作编号不能改变完整确认请求。');return prior.result;}
   const selected=candidates.get(request.commandId);if(!selected||!sameSelection(selected.selection,request))throw new Error('候选已失效，不能从公开路径或同名文件重建。');const found=locate(request),cap=await online(found.root.sourceRootId);if(cap.id!==selected.sourceRootId||found.root.id!==selected.rootId)throw new Error('来源许可关联已改变。');const observation=await readonlySourceCandidateMetadata(cap,selected.relative);if(observation.signature!==selected.signature)throw new Error('候选文件在确认前已改变。');await options.beforeMutation?.();check();locate(request);if((await readonlySourceCandidateMetadata(cap,selected.relative)).signature!==selected.signature)throw new Error('候选文件在等待扫描quiet时已改变。');const base={commandId:request.commandId,assetId:request.assetId,expectedLocationRevision:request.expectedLocationRevision,expectedRootRevision:request.expectedRootRevision,relative:selected.relative};
   // 独立inode观察可确认改名；人工换选不同文件只作保守replacement，不能保持旧内容修订冒相同文件。
   const result=await withLocalFactsMutation(()=>selected.view.evidence==='same-inode-observation'?catalog.moveAsset(base):catalog.replaceAsset({...base,libraryRootId:found.root.id,expectedFileRevision:request.expectedFileRevision,sha256:null,sampleFrames:null,timebaseHz:null}),async()=>{check();locate(request);if((await readonlySourceCandidateMetadata(cap,selected.relative)).signature!==selected.signature)throw new Error('派发quiet后候选文件已改变。');check();});candidates.delete(request.commandId);return result;
  },
  async relinkRoot(request:dto.LocalRootRelink):Promise<dto.LibraryRoot>{check();if(!dto.isLocalRootRelink(request))throw new Error('根重关联必须明确确认。');const prior=catalog.privateReceiptRequest(request.commandId);if(prior){if(prior.operation!=='relink-root'||prior.request.rootId!==request.rootId||prior.request.expectedRevision!==request.expectedRevision||prior.request.sourceRootId!==request.targetSourceRootId||!dto.isLibraryRoot(prior.result))throw new Error('根重关联操作编号不能改参。');return prior.result;}const root=catalog.root(request.rootId);if(root.revision!==request.expectedRevision)throw new Error('根修订已改变。');if(catalog.privateRootHasExactAssets(root.id))throw new Error('此根含严格内容/精确片段事实，不能以普通目录选择替代其重新证明。');const cap=await online(request.targetSourceRootId);outsideOtherRoots(cap,root.id);await options.beforeMutation?.();check();await online(cap.id);return withLocalFactsMutation(()=>catalog.relinkRoot({commandId:request.commandId,rootId:root.id,expectedRevision:request.expectedRevision,sourceRootId:cap.id,role:root.role}),async()=>{check();await online(cap.id);check();});},
  close(){closed=true;candidates.clear();},
 };
}
export type LocalRelocationCoordinator=ReturnType<typeof createLocalRelocationCoordinator>;
