<script setup lang="ts">
import { computed, nextTick, ref, watch } from 'vue'
import type { CanonicalReference } from '@music-bridge/contracts'
import CollectionReferenceImage from './CollectionReferenceImage.vue'
import CassetteCatalogDetail from './CassetteCatalogDetail.vue'
import { cassetteModelGroupKey, filterCassetteCatalog, groupCassetteCatalog, hasReferenceImage, type CassetteCatalogModelGroup, type PublishedCassetteReference, type ReferenceCatalogSelection } from './reference-images'

const props = defineProps<{ items: readonly PublishedCassetteReference[]; loading: boolean; error: string }>()
const emit = defineEmits<{ refresh: []; importArchive: []; manage: [selection?: ReferenceCatalogSelection]; openModel: [modelId: string]; receive: [reference: CanonicalReference] }>()
const query = ref(''), brand = ref(''), iec = ref(''), offset = ref(0), selectedKey = ref('')
const selectedBrand = ref(''), selectedModelKey = ref('')
const heading = ref<HTMLHeadingElement>()
const pageSize = 48
const itemKey = (item: PublishedCassetteReference) => `${item.revisionId}/${item.reference.referenceId}`
const brands = computed(() => [...new Set(props.items.map(item => item.reference.brand))].sort((a, b) => a.localeCompare(b, 'zh-CN')))
const filtered = computed(() => filterCassetteCatalog(props.items, { query: query.value, brand: brand.value, iec: iec.value }))
const groups = computed(() => groupCassetteCatalog(props.items))
const currentBrand = computed(() => groups.value.find(group => group.brand === selectedBrand.value))
const currentModel = computed(() => currentBrand.value?.models.find(group => group.key === selectedModelKey.value))
const selected = computed(() => props.items.find(item => itemKey(item) === selectedKey.value))
const hasFilter = computed(() => !!(query.value.trim() || brand.value || iec.value))
const visibleRows = computed(() => hasFilter.value ? filtered.value : currentModel.value?.items ?? [])
const page = computed(() => visibleRows.value.slice(offset.value, offset.value + pageSize))
const breadcrumbBrand = computed(() => selected.value?.reference.brand ?? currentBrand.value?.brand)
const breadcrumbModel = computed(() => selected.value ? groups.value.find(group => group.brand === selected.value!.reference.brand)?.models.find(group => group.key === cassetteModelGroupKey(selected.value!.reference)) : currentModel.value)
const missingPrimaryCount = computed(() => props.items.filter(item => !hasReferenceImage(item.reference)).length)
let detailOrigin: HTMLElement | undefined
function focusHeading(): void { void nextTick(() => { heading.value?.focus({ preventScroll: true }); heading.value?.scrollIntoView({ block: 'start', behavior: 'auto' }) }) }
function openDetail(item: PublishedCassetteReference): void { detailOrigin = document.activeElement as HTMLElement; selectedKey.value = itemKey(item) }
function closeDetail(): void {
  const key = selectedKey.value; selectedKey.value = ''
  void nextTick(() => { const target = detailOrigin?.isConnected ? detailOrigin : document.querySelector<HTMLElement>(`[data-catalog-reference="${key}"]`); (target ?? heading.value)?.focus({ preventScroll: true }) })
}
function clearFilters(): void { query.value = ''; brand.value = ''; iec.value = '' }
function showBrands(): void { clearFilters(); selectedKey.value = ''; selectedBrand.value = ''; selectedModelKey.value = ''; offset.value = 0; focusHeading() }
function showBrand(value: string): void { clearFilters(); selectedKey.value = ''; selectedBrand.value = value; selectedModelKey.value = ''; offset.value = 0; focusHeading() }
function showModel(group: CassetteCatalogModelGroup): void { clearFilters(); selectedKey.value = ''; selectedBrand.value = group.brand; selectedModelKey.value = group.key; offset.value = 0; focusHeading() }
const iecLabel = (value: string) => value === 'unknown' ? '带型未知' : value === 'dat' ? 'DAT' : `IEC ${value}`
const groupPreview = (group: CassetteCatalogModelGroup) => group.items.find(item => hasReferenceImage(item.reference)) ?? group.items[0]!
function ownershipLabel(item: PublishedCassetteReference): string {
  return item.current?.state === 'owned' ? '已确认拥有' : item.current?.state === 'missing' ? '已核对缺少' : '拥有情况未知'
}
watch([query, brand, iec], () => { offset.value = 0 })
watch(visibleRows, items => { if (offset.value >= items.length) offset.value = 0 })
</script>

<template>
  <nav class="catalog-breadcrumb" aria-label="磁带资料层级"><button type="button" @click="showBrands">全部品牌</button><template v-if="breadcrumbBrand"><span aria-hidden="true">/</span><button type="button" @click="showBrand(breadcrumbBrand)">{{ breadcrumbBrand }}</button></template><template v-if="breadcrumbModel"><span aria-hidden="true">/</span><button type="button" @click="showModel(breadcrumbModel)">{{ breadcrumbModel.model }} · {{ iecLabel(breadcrumbModel.iec) }}</button></template><template v-if="selected"><span aria-hidden="true">/</span><span>{{ selected.reference.era || '原书年份未知' }} · {{ selected.reference.edition || '版次未知' }}</span></template><template v-else-if="hasFilter"><span aria-hidden="true">/</span><span>搜索结果</span></template></nav>
  <CassetteCatalogDetail v-if="selected" :item="selected" @close="closeDetail" @review="emit('manage', $event)" @open-model="emit('openModel', $event)" @receive="emit('receive', $event)" />
  <section v-else class="cassette-catalog" aria-labelledby="cassette-catalog-title">
    <header class="catalog-heading"><div><p class="catalog-kicker">参考目录 · 原书资料</p><h2 id="cassette-catalog-title" ref="heading" tabindex="-1">{{ hasFilter ? '磁带资料搜索' : currentModel ? `${currentModel.brand} ${currentModel.model}` : currentBrand ? `${currentBrand.brand} 型号` : '全部磁带资料' }}</h2><p>{{ hasFilter ? '搜索结果可直接查看具体资料，无需逐层查找。' : currentModel ? '按原书标注年份与版次查看；未知年代也保留独立资料入口。' : currentBrand ? '选择型号，再看不同原书年份与版次的资料。' : '从品牌到型号，再到原书年份与版次；也可以直接搜索。' }}</p></div><div class="catalog-actions"><button type="button" :disabled="loading" @click="emit('refresh')">{{ loading ? '读取中…' : '刷新资料' }}</button><button type="button" @click="emit('manage')">参考目录与版次</button><button class="primary" type="button" aria-haspopup="dialog" @click="emit('importArchive')">导入完整资料 ZIP</button></div></header>
    <form class="catalog-filters" aria-label="搜索全部磁带资料" @submit.prevent="offset = 0"><label class="query"><span>关键词</span><input v-model="query" maxlength="120" placeholder="品牌、型号、版次、原书说明…"></label><label><span>品牌</span><select v-model="brand"><option value="">所有品牌</option><option v-for="value in brands" :key="value" :value="value">{{ value }}</option></select></label><label><span>带型</span><select v-model="iec"><option value="">所有带型</option><option v-for="value in ['I', 'II', 'III', 'IV']" :key="value" :value="value">IEC {{ value }}</option><option value="dat">DAT</option><option value="unknown">带型未知</option></select></label><button v-if="hasFilter" type="button" @click="clearFilters">清除筛选</button></form>
    <div class="catalog-summary"><p>{{ hasFilter ? `筛选结果 ${filtered.length} / ${items.length}` : currentModel ? `${currentModel.items.length} 条原书年份 / 版次资料` : currentBrand ? `${currentBrand.models.length} 组型号 · ${currentBrand.referenceCount} 条资料` : `${groups.length} 个品牌 · 已发布 ${items.length} 条磁带资料` }}<span v-if="missingPrimaryCount"> · 全目录 {{ missingPrimaryCount }} 条主图尚缺</span></p><p>资料与我的库存分别管理</p></div>
    <p v-if="loading" role="status">正在读取已发布磁带资料…</p><p v-if="error" class="error" role="alert">{{ error }} <button type="button" @click="emit('refresh')">重试资料</button></p>
    <div v-if="!hasFilter && !currentBrand && groups.length" class="catalog-grid brand-grid"><article v-for="group in groups" :key="group.brand" class="catalog-tile"><button class="catalog-card brand-card" type="button" @click="showBrand(group.brand)"><strong>{{ group.brand }}</strong><span>{{ group.models.length }} 组型号 · {{ group.referenceCount }} 条磁带资料</span><small>查看品牌型号 →</small></button></article></div>
    <div v-else-if="!hasFilter && currentBrand && !currentModel" class="catalog-grid"><article v-for="group in currentBrand.models" :key="group.key" class="catalog-tile"><button class="catalog-card" type="button" @click="showModel(group)"><div class="catalog-card-media"><CollectionReferenceImage :reference="groupPreview(group).reference" /><span class="image-source">{{ hasReferenceImage(groupPreview(group).reference) ? '原书资料示例图' : '主图尚缺 · 资料组保留' }}</span></div><div class="catalog-card-body"><strong>{{ group.model }}</strong><span>{{ iecLabel(group.iec) }} · {{ group.series || '系列未提供' }}</span><small>{{ group.items.length }} 条原书年份 / 版次资料</small></div></button></article></div>
    <div v-else-if="page.length" class="catalog-grid"><article v-for="item in page" :key="itemKey(item)" class="catalog-tile"><button class="catalog-card" type="button" :data-catalog-reference="itemKey(item)" @click="openDetail(item)"><div class="catalog-card-media"><CollectionReferenceImage :reference="item.reference" /><span class="image-source">{{ hasReferenceImage(item.reference) ? '原书资料图' : '主图尚缺' }}</span></div><div class="catalog-card-body"><strong>{{ item.reference.brand }} {{ item.reference.model }}</strong><span>原书标注年份：{{ item.reference.era || '未知' }}</span><span>资料版次：{{ item.reference.edition || '未知' }} · {{ iecLabel(item.reference.iec) }}</span><small>{{ item.source.title }} · {{ item.reference.pages.join('、') || '页码未提供' }}</small><span class="ownership">{{ ownershipLabel(item) }}</span></div></button></article></div>
    <div v-else-if="!loading && !error" class="catalog-empty"><h3>{{ hasFilter ? '没有符合筛选的磁带资料' : '尚未发布磁带资料' }}</h3><p>{{ hasFilter ? '换个关键词、品牌或带型试试。' : '导入完整磁带资料 ZIP 后即可浏览原书资料、图片与来源。已有库存仍保留在“我的磁带”。' }}</p><button v-if="hasFilter" type="button" @click="clearFilters">清除筛选</button><button v-else class="primary" type="button" @click="emit('importArchive')">导入完整资料 ZIP</button></div>
    <nav v-if="visibleRows.length > pageSize" class="catalog-pagination" aria-label="磁带资料分页"><button type="button" :disabled="offset === 0" @click="offset = Math.max(0, offset - pageSize)">上一页</button><span>{{ Math.floor(offset / pageSize) + 1 }} / {{ Math.ceil(visibleRows.length / pageSize) }}</span><button type="button" :disabled="offset + pageSize >= visibleRows.length" @click="offset += pageSize">下一页</button></nav>
  </section>
</template>

<style scoped>
.cassette-catalog { min-width: 0; color: var(--collection-text); font-size: 13px; line-height: 1.7; } .catalog-heading { display: flex; align-items: flex-start; justify-content: space-between; flex-wrap: wrap; gap: 20px; margin: 20px 0 24px; } .catalog-kicker { margin: 0 0 6px; color: var(--collection-accent); font-size: 11px; letter-spacing: .1em; } h2 { margin: 0; font-size: 28px; line-height: 1.4; letter-spacing: -.035em; } h3 { margin: 0; font-size: 19px; } p { color: var(--collection-muted); } .catalog-heading p:last-child { margin: 10px 0 0; }
.catalog-breadcrumb { display: flex; align-items: center; flex-wrap: wrap; gap: 7px; margin: 0 0 14px; color: var(--collection-muted); font-size: 12px; } .catalog-breadcrumb button { min-height: 32px; padding: 4px 3px; border: 0; background: transparent; color: var(--collection-accent); } .catalog-card.brand-card { gap: 12px; padding: 24px; min-height: 170px; justify-content: center; } .brand-card > strong { font-size: 27px; line-height: 1.3; } .brand-card > span, .brand-card > small { color: var(--collection-muted); font-size: 12px; }
.catalog-actions { display: flex; flex-wrap: wrap; align-items: center; gap: 10px; } button { min-height: 42px; padding: 9px 13px; border: 1px solid var(--collection-line); border-radius: 8px; background: var(--collection-surface); color: var(--collection-text); font: inherit; cursor: pointer; } button:disabled { opacity: .5; cursor: default; } .primary { border-color: var(--collection-accent); color: var(--collection-accent); font-weight: 650; }
.catalog-filters { display: flex; align-items: flex-end; flex-wrap: wrap; gap: 12px; } label { display: grid; gap: 5px; flex: 1 1 140px; min-width: 0; } label.query { flex: 3 1 300px; } label > span { font-size: 12px; color: var(--collection-muted); } input, select { box-sizing: border-box; width: 100%; min-width: 0; min-height: 42px; padding: 9px 12px; border: 1px solid var(--collection-line); border-radius: 8px; background: var(--collection-surface); color: var(--collection-text); font: inherit; } input::placeholder { color: var(--collection-muted); }
.catalog-summary { display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 6px 16px; margin: 14px 0 18px; font-size: 12px; } .catalog-summary p { margin: 0; }
.catalog-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(min(280px, 100%), 1fr)); gap: 28px; } .catalog-tile { min-width: 0; border: 1px solid var(--collection-line); border-radius: 13px; background: var(--collection-surface); overflow: hidden; } .catalog-card { display: flex; flex-direction: column; width: 100%; height: 100%; min-width: 0; padding: 0; border: 0; border-radius: 0; background: transparent; text-align: left; }
.catalog-card-media { position: relative; width: 100%; aspect-ratio: 8 / 5; background: var(--collection-media); overflow: hidden; } .catalog-card-media :deep(.reference-image) { height: 100%; min-height: 0; background: transparent; } .image-source { position: absolute; right: 9px; bottom: 7px; padding: 2px 5px; border-radius: 3px; background: var(--collection-surface); color: var(--collection-muted); font-size: 10px; } .catalog-card-body { box-sizing: border-box; display: grid; gap: 6px; width: 100%; padding: 12px; } .catalog-card-body strong { font-size: 16px; line-height: 1.4; overflow-wrap: anywhere; } .catalog-card-body > span, small { font-size: 12px; color: var(--collection-muted); overflow-wrap: anywhere; } small { font-size: 11px; } .catalog-card-body .ownership { color: var(--collection-accent); font-size: 11px; }
.catalog-empty { display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 260px; padding: 28px; border: 1px dashed var(--collection-line); border-radius: 12px; text-align: center; background: var(--collection-subtle); } .catalog-empty p { max-width: 480px; } .catalog-pagination { display: flex; justify-content: center; align-items: center; gap: 20px; margin: 24px 0 0; } .error { border-left: 3px solid var(--collection-accent); padding: 10px 14px; }
:where(button, input, select, h2):focus-visible { outline: 2px solid var(--collection-accent); outline-offset: 3px; } .catalog-card:focus-visible { outline-offset: -4px; } button:active:not(:disabled) { transform: scale(.98); } @media (hover: hover) and (pointer: fine) { .catalog-tile:hover { border-color: var(--collection-accent); } }
@container (max-width: 820px) { .catalog-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 20px; } } @container (max-width: 480px) { .catalog-grid { grid-template-columns: minmax(0, 1fr); } .catalog-actions { width: 100%; } h2 { font-size: 25px; } }
</style>
