<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, shallowRef, triggerRef, watch } from 'vue'
import type { WantEntry, WantPriority, CollectionLengthQuantity } from '@music-bridge/contracts'
import { createCollectionProgressController } from './collection-progress-controller'

const emit = defineEmits<{ close: [] }>()
const dialog = ref<HTMLDialogElement>()
const controller = createCollectionProgressController({ api: window.musicBridge, onChange: () => triggerRef(state) })
const state = shallowRef(controller.state)
const navigationBlocked = computed(() => state.value.busy || !!state.value.pendingLabel)
const blocked = computed(() => navigationBlocked.value || state.value.sourcesLoading || state.value.wantsLoading)
const current = computed(() => state.value.progressFresh && !!state.value.progress?.isCurrentRevision)
const saveConfirmed = ref(false), captureConfirmed = ref(false), retryConfirmed = ref(false), cancelConfirmed = ref(false), closeRequested = ref(false)
const cancelTarget = ref<WantEntry>()
const groupBy = ref<'overall' | 'brands' | 'series'>('overall')
const sources = computed(() => [...new Map((state.value.sources?.items ?? []).map(source => [source.bookId, source])).values()])
const metrics = computed(() => state.value.section === 'history' ? state.value.snapshot?.snapshot : state.value.progress)
const groups = computed(() => !metrics.value ? [] : groupBy.value === 'brands' ? metrics.value.brands.map(group => ({ label: group.brand, counts: group.counts })) : groupBy.value === 'series' ? metrics.value.series.map(group => ({ label: `${group.brand} · ${group.series || '系列未标注'}`, counts: group.counts })) : [{ label: '整本目录', counts: metrics.value.overall }])
const entryPage = computed(() => state.value.section === 'progress' ? state.value.progress?.entries : state.value.section === 'history' ? state.value.snapshot?.entries : undefined)
const priorityLabels = { low: '低', normal: '普通', high: '高' }
const states = { owned: 'Owned · 已拥有', missing: 'Missing · 明确缺失', unknown: 'Unknown · 尚未确认' }
const lengths = (items: readonly CollectionLengthQuantity[]) => items.length ? items.map(item => `${item.lengthMinutes} 分钟 × ${item.quantity} 盘`).join('；') : '没有已确认的持有长度'
function priority(event: Event): void { const value = (event.target as HTMLSelectElement).value; if (['low', 'normal', 'high'].includes(value)) controller.setDraft({ priority: value as WantPriority }) }
function askCancel(entry: WantEntry): void { cancelTarget.value = entry; cancelConfirmed.value = false }
function requestClose(): void { if (!state.value.busy) { if (state.value.draft || state.value.pendingLabel) closeRequested.value = true; else emit('close') } }
watch(() => state.value.intentRevision, () => { saveConfirmed.value = false; captureConfirmed.value = false; cancelConfirmed.value = false; cancelTarget.value = undefined }, { flush: 'sync' })
onMounted(async () => { await nextTick(); dialog.value?.showModal(); dialog.value?.querySelector<HTMLElement>('#collection-progress-title')?.focus({ preventScroll: true }); void controller.start() })
onBeforeUnmount(() => { controller.dispose(); dialog.value?.close() })
</script>

<template>
  <dialog ref="dialog" class="progress-dialog" data-testid="collection-progress-panel" aria-labelledby="collection-progress-title" aria-describedby="collection-progress-boundary" @cancel.prevent="requestClose">
    <header class="heading"><div><p class="kicker">收藏 · 参考目录</p><h2 id="collection-progress-title" tabindex="-1">完成度与求购</h2></div><button :disabled="state.busy" @click="requestClose">关闭</button></header>
    <p id="collection-progress-boundary">一个参考型号与版次计一个完成度单位。求购独立于拥有、缺失和未知，不增加库存、不自动购买。</p>
    <nav class="sections" aria-label="完成度与求购内容"><button :aria-current="state.section === 'progress' ? 'page' : undefined" :disabled="navigationBlocked" @click="controller.setSection('progress')">完成度</button><button :aria-current="state.section === 'wants' ? 'page' : undefined" :disabled="navigationBlocked" @click="controller.setSection('wants')">求购清单</button><button :aria-current="state.section === 'history' ? 'page' : undefined" :disabled="navigationBlocked" @click="controller.setSection('history')">历史</button></nav>
    <p v-if="state.busy" role="status">正在读取或保存，请稍候…</p><p v-if="state.error" class="error" role="alert">{{ state.error }}</p><p v-if="state.notice" class="notice" role="status">{{ state.notice }}</p>
    <section v-if="closeRequested" class="feedback" role="alert"><p>关闭会丢弃尚未保存的编辑。已提交但未确认的命令仍可从全局未确认操作恢复，不会自动重试。</p><div class="actions"><button @click="closeRequested = false">继续编辑</button><button @click="emit('close')">确认关闭</button></div></section>
    <section v-if="state.pendingLabel" class="feedback" aria-label="恢复求购与完成度原操作"><h3>{{ state.pendingLabel }}：等待明确回执</h3><p>保持原工作库、原命令、版本和指纹，不换参数绕过冲突。</p><label class="check"><input v-model="retryConfirmed" type="checkbox" :disabled="state.busy">我已核对结果，确认恢复原操作或退出面板重试</label><div class="actions"><button :disabled="state.busy || !retryConfirmed" @click="controller.retry(true); retryConfirmed = false">重试原操作</button><button :disabled="state.busy || !retryConfirmed" @click="controller.releasePending(true); retryConfirmed = false">退出面板重试</button></div></section>

    <fieldset :disabled="navigationBlocked" class="context"><legend>参考目录上下文</legend><div class="fields"><label>参考书籍<select :value="state.bookId" :disabled="blocked" @change="controller.selectBook(($event.target as HTMLSelectElement).value)"><option value="">请选择已登记书籍</option><option v-for="source in sources" :key="source.bookId" :value="source.bookId">{{ source.title }} · {{ source.bookId }}</option></select></label><label>目录修订<select :value="state.revisionId" :disabled="blocked || !state.catalogHistory" @change="controller.selectRevision(($event.target as HTMLSelectElement).value)"><option value="">请选择目录修订</option><option v-if="state.catalogHistory?.currentRevisionId && !state.catalogHistory.revisions.some(item => item.id === state.catalogHistory?.currentRevisionId)" :value="state.catalogHistory.currentRevisionId">当前修订（读取详情）</option><option v-for="revision in state.catalogHistory?.revisions" :key="revision.id" :value="revision.id">修订 {{ revision.sequence }} · {{ revision.id === state.catalogHistory?.currentRevisionId ? '当前目录' : '旧目录' }} · {{ revision.createdAt }}</option></select></label></div>
      <p v-if="!state.sourcesLoading && !state.sourcesError && state.sources && state.sources.total === 0">尚无参考书籍。请先在“参考目录与版次”中显式登记并发布资料；这里没有预置书籍或图片。</p>
      <div class="actions"><button :disabled="navigationBlocked || state.sourcesLoading" @click="controller.loadSources()">刷新参考来源</button><button :disabled="navigationBlocked || state.sourcesLoading" v-if="state.sources && state.sources.offset > 0" @click="controller.loadSources(Math.max(0, state.sources.offset - 25))">上一页来源</button><button :disabled="navigationBlocked || state.sourcesLoading" v-if="state.sources && state.sources.offset + state.sources.limit < state.sources.total" @click="controller.loadSources(state.sources.offset + 25)">下一页来源</button><button :disabled="blocked" v-if="state.bookId" @click="controller.loadCatalogHistory()">刷新目录修订</button><button :disabled="blocked" v-if="state.catalogHistory && state.catalogHistory.offset > 0" @click="controller.loadCatalogHistory(Math.max(0, state.catalogHistory.offset - 25))">上一页修订</button><button :disabled="blocked" v-if="state.catalogHistory && state.catalogHistory.offset + state.catalogHistory.limit < state.catalogHistory.total" @click="controller.loadCatalogHistory(state.catalogHistory.offset + 25)">下一页修订</button></div>
      <p v-if="state.sourcesLoading" role="status">正在读取参考来源…</p><p v-if="state.sourcesError" class="error" role="alert">{{ state.sourcesError }} <button :disabled="navigationBlocked || state.sourcesLoading" @click="controller.loadSources()">重试参考来源</button></p>
    </fieldset>

    <section v-if="state.section === 'progress'" aria-labelledby="progress-current-title"><h3 id="progress-current-title">当前完成度</h3>
      <p v-if="!state.progress">请选择目录并读取当前事实，尚未读取不等于零拥有。</p>
      <template v-else><p v-if="!state.progress.isCurrentRevision" class="feedback">旧目录的当前事实，不是历史快照。旧目标保留待复核；不能从这里采集新快照或自动迁移求购。</p><p v-else>当前目录修订 {{ state.progress.catalogSequence }} · 当前库存与匹配事实</p><p v-if="!state.progressFresh" class="error">以上是上次读取的资料，当前刷新未完成或已经失效；请重新读取后再提交。</p><p>候选 {{ state.progress.overall.candidate }} · 待复核 {{ state.progress.overall.needsReview }}；均不自动计为 Owned。旧目录求购目标 {{ state.progress.historicalWantedCount }} 条，独立保留，不计入当前 Wanted。</p></template>
      <div class="actions"><button :disabled="blocked || !state.revisionId" @click="controller.loadProgress()">刷新当前完成度</button><button :disabled="blocked || !current" @click="controller.newWant()">新建求购目标</button></div>
      <section v-if="state.progress" class="capture"><h4>采集独立历史快照</h4><p>保存整本目录的当前统计、求购与长度事实，不仅是当前页。保存后不随库存变化更新。</p><code>{{ state.progress.fingerprint }}</code><label class="check"><input v-model="captureConfirmed" type="checkbox" :disabled="blocked || !current">我已核对当前目录与整批事实，确认采集完成度快照</label><button :disabled="blocked || !current || !captureConfirmed" @click="controller.capture(captureConfirmed)">采集完成度快照</button></section>
    </section>

    <section v-if="state.section === 'wants'" aria-labelledby="want-list-title"><h3 id="want-list-title">求购清单</h3><p>Wanted 是独立愿望：已拥有型号仍可求购另一时长或品相。清单跨书籍显示，旧目标不会自动改指向。</p><div class="actions"><button :disabled="navigationBlocked || state.wantsLoading" @click="controller.loadWants()">刷新求购清单</button><button :disabled="blocked" @click="controller.newWant()">新建求购目标</button></div><p v-if="state.wantsLoading" role="status">正在读取求购清单…</p><p v-if="state.wantsError" class="error" role="alert">{{ state.wantsError }} <button :disabled="navigationBlocked || state.wantsLoading" @click="controller.loadWants()">重试求购清单</button></p><template v-if="!state.wantsLoading && !state.wantsError"><p v-if="!state.wants">求购清单尚未刷新，不能据此判断没有目标。</p><p v-else-if="state.wants.total === 0">还没有求购目标。</p></template>
      <div v-if="state.savedWant" class="notice" role="status">{{ state.savedWant.active ? '求购目标已保存' : '求购已取消' }} · 版本 {{ state.savedWant.version }}</div>
      <ul class="records"><li v-for="view in state.wants?.items" :key="view.entry.id"><h4>{{ view.entry.brand }} {{ view.entry.model }} · {{ view.entry.edition || '版次未标注' }}</h4><p>{{ view.entry.active ? '求购中' : '已取消（终态）' }} · 优先级 {{ priorityLabels[view.entry.priority] }} · 版本 {{ view.entry.version }} · {{ view.entry.bookId }}</p><p v-if="view.needsReview" class="notice">旧目录目标待复核：保留原目标与历史，不自动迁移、合并或拆分复制。</p><p>长度 {{ view.entry.targetLengthMinutes === null ? '不限定' : `${view.entry.targetLengthMinutes} 分钟` }} · 包装 {{ view.entry.packagingTarget || '不限定' }} · 品相 {{ view.entry.preferredCondition || '不限定' }}</p><p>价格目标 {{ view.entry.priceTarget ? `${view.entry.priceTarget.currency} ${view.entry.priceTarget.amount}` : '未设置' }}</p><p class="notes">{{ view.entry.notes || '无备注' }}</p><div class="actions"><button :disabled="blocked || !view.entry.active" @click="controller.editWant(view)">编辑此求购</button><button :disabled="blocked || !view.entry.active" @click="askCancel(view.entry)">取消此求购</button><button :disabled="blocked" @click="controller.loadWantHistory(view.entry.id)">查看求购历史</button></div></li></ul>
      <div v-if="state.wants && state.wants.total > state.wants.limit" class="actions"><button :disabled="navigationBlocked || state.wantsLoading || state.wants.offset === 0" @click="controller.loadWants(Math.max(0, state.wants.offset - 25))">上一页求购</button><button :disabled="navigationBlocked || state.wantsLoading || !state.wants.hasMore" @click="controller.loadWants(state.wants.offset + 25)">下一页求购</button></div>
      <section v-if="cancelTarget" class="feedback"><h4>取消 {{ cancelTarget.brand }} {{ cancelTarget.model }} 的求购</h4><p>保留历史，不撤销或减少库存。取消后不能复活此记录。</p><label class="check"><input v-model="cancelConfirmed" type="checkbox" :disabled="blocked">我确认取消这个求购目标</label><button :disabled="blocked || !cancelConfirmed" @click="controller.cancelWant(cancelTarget, cancelConfirmed)">确认取消求购</button></section>
      <form v-if="state.draft" class="editor" @submit.prevent="controller.saveWant(saveConfirmed)"><h4>{{ state.draft.id ? '编辑求购目标' : '新增求购目标' }}</h4><p v-if="state.draft.previousTarget">原目标：{{ state.draft.previousTarget }}。请在上方明确选择当前目录，并重新选择下面的目标参考项。</p><p v-if="!current" class="notice">请先选择并读取当前目录修订；旧目录不能作为新保存目标。</p><fieldset :disabled="blocked"><legend>目标与偏好</legend><div class="fields"><label>目标参考项<select :value="state.draft.referenceId" :disabled="!current" @change="controller.setDraft({ referenceId: ($event.target as HTMLSelectElement).value })"><option value="">请选择当前目录参考项</option><option v-for="item in state.catalog?.revision.items" :key="item.referenceId" :value="item.referenceId">{{ item.brand }} {{ item.model }} · {{ item.edition || '版次未标注' }} · {{ item.referenceId }}</option></select></label><label>优先级<select :value="state.draft.priority" @change="priority"><option value="low">低</option><option value="normal">普通</option><option value="high">高</option></select></label><label>目标长度（分钟，可留空）<input :value="state.draft.targetLength" inputmode="numeric" @input="controller.setDraft({ targetLength: ($event.target as HTMLInputElement).value })"></label><label>偏好包装<input :value="state.draft.packagingTarget" maxlength="200" @input="controller.setDraft({ packagingTarget: ($event.target as HTMLInputElement).value })"></label><label>偏好品相<input :value="state.draft.preferredCondition" maxlength="200" @input="controller.setDraft({ preferredCondition: ($event.target as HTMLInputElement).value })"></label></div><div class="fields"><label>价格币种（可选，三位大写）<input :value="state.draft.currency" maxlength="3" placeholder="例如 CNY" @input="controller.setDraft({ currency: ($event.target as HTMLInputElement).value })"></label><label>精确价格金额（可选）<input :value="state.draft.amount" inputmode="decimal" placeholder="例如 12.3400" @input="controller.setDraft({ amount: ($event.target as HTMLInputElement).value })"></label></div><p class="hint">币种和金额同时填写或同时留空；金额保留原十进制文字，不换汇、不转浮点。</p><label>求购备注<textarea :value="state.draft.notes" rows="3" maxlength="4000" @input="controller.setDraft({ notes: ($event.target as HTMLTextAreaElement).value })" /></label></fieldset><label class="check"><input v-model="saveConfirmed" type="checkbox" :disabled="blocked || !current">我已核对目标目录与参考项，确认仅保存求购，不更改库存</label><div class="actions"><button class="primary" type="submit" :disabled="blocked || !current || !state.draft.referenceId || !saveConfirmed">保存求购目标</button><button type="button" :disabled="blocked" @click="controller.abandonDraft()">放弃本次编辑</button></div></form>
    </section>

    <section v-if="state.section === 'history'" aria-labelledby="progress-history-title"><h3 id="progress-history-title">历史记录</h3><p>完成度快照和求购版本各自保留；读取历史不采用当前数量回填。</p><div v-if="state.captured" class="notice">快照已保存 · {{ state.captured.createdAt }} <button :disabled="blocked" @click="controller.loadSnapshot(state.captured.id)">查看本次快照</button></div><button :disabled="blocked" @click="controller.loadSnapshots()">读取完成度快照历史</button><p v-if="!state.snapshots">新口径快照列表尚未读取。</p><p v-else-if="state.snapshots.total === 0">尚无新口径完成度快照。</p><ul class="records"><li v-for="snapshot in state.snapshots?.items" :key="snapshot.id"><strong>{{ snapshot.createdAt }} · 目录修订 {{ snapshot.catalogSequence }}</strong><p>{{ snapshot.bookId }} · Owned {{ snapshot.overall.owned }} / {{ snapshot.overall.total }} · Wanted {{ snapshot.overall.wanted }}</p><button :disabled="blocked" @click="controller.loadSnapshot(snapshot.id)">读取此完成度快照</button></li></ul><div v-if="state.snapshots && (state.snapshotPreviousOffset !== undefined || state.snapshots.hasMore)" class="actions"><button :disabled="blocked || state.snapshotPreviousOffset === undefined" @click="controller.previousSnapshots()">上一页快照</button><button :disabled="blocked || !state.snapshots.hasMore" @click="controller.nextSnapshots()">下一页快照</button></div>
      <div v-if="state.snapshot" class="notice"><h4>独立历史快照 · {{ state.snapshot.snapshot.createdAt }}</h4><p>目录修订 {{ state.snapshot.snapshot.catalogSequence }}，以下是采集时点事实，不是当前库存。</p></div>
      <details><summary>旧目录快照（旧口径）</summary><p>先选择书籍，可分页读取目录历史。旧快照的 Wanted 与长度维度未采集，不能显示为零或用当前事实补齐。</p><ul class="records"><li v-for="snapshot in state.catalogHistory?.snapshots" :key="snapshot.id"><span>{{ snapshot.createdAt }} · Owned {{ snapshot.counts.owned }} / {{ snapshot.counts.total }}</span><button :disabled="blocked" @click="controller.loadLegacySnapshot(snapshot.id)">读取旧口径快照</button></li></ul></details>
      <section v-if="state.legacySnapshot" class="feedback"><h4>旧口径历史快照 · {{ state.legacySnapshot.createdAt }}</h4><p>Wanted 与长度维度未采集。此处仅保留原统计。</p><p>Owned {{ state.legacySnapshot.counts.owned }} · Missing {{ state.legacySnapshot.counts.missing }} · Unknown {{ state.legacySnapshot.counts.unknown }} · 总型号 {{ state.legacySnapshot.counts.total }}</p><p>候选 {{ state.legacySnapshot.counts.candidate }} · 待复核 {{ state.legacySnapshot.counts.needsReview }}</p></section>
      <section v-if="state.wantHistory"><h4>求购版本历史</h4><ul class="records"><li v-for="version in state.wantHistory.items" :key="version.version"><strong>版本 {{ version.version }} · {{ version.active ? '求购中' : '已取消' }}</strong><p>{{ version.updatedAt }} · {{ version.brand }} {{ version.model }} · {{ version.edition || '版次未标注' }} · {{ version.referenceId }}</p><p>优先级 {{ priorityLabels[version.priority] }} · 长度 {{ version.targetLengthMinutes === null ? '不限定' : `${version.targetLengthMinutes} 分钟` }} · 包装 {{ version.packagingTarget || '不限定' }} · 品相 {{ version.preferredCondition || '不限定' }}</p><p>价格 {{ version.priceTarget ? `${version.priceTarget.currency} ${version.priceTarget.amount}` : '未设置' }}</p><p class="notes">{{ version.notes || '无备注' }}</p></li></ul><div v-if="state.wantHistoryId" class="actions"><button :disabled="blocked || state.wantHistory.offset === 0" @click="controller.loadWantHistory(state.wantHistoryId, Math.max(0, state.wantHistory.offset - 25))">上一页求购历史</button><button :disabled="blocked || !state.wantHistory.hasMore" @click="controller.loadWantHistory(state.wantHistoryId, state.wantHistory.offset + 25)">下一页求购历史</button></div></section>
    </section>

    <section v-if="metrics && state.section !== 'wants'" class="metrics" aria-label="完成度分组统计"><h3>型号与版次完成度</h3><label>统计分组<select v-model="groupBy"><option value="overall">整体</option><option value="brands">品牌</option><option value="series">系列</option></select></label><p>主完成度 = Owned / 总参考型号。Wanted 单独列出，不加入主分子；Unknown 与 Missing 不合并。</p><table><caption>{{ state.section === 'history' ? '历史时点统计' : '当前事实统计' }}</caption><thead><tr><th scope="col">分组</th><th scope="col">型号总数</th><th scope="col">Owned</th><th scope="col">Missing</th><th scope="col">Unknown</th><th scope="col">Wanted</th></tr></thead><tbody><tr v-for="group in groups" :key="group.label"><th scope="row">{{ group.label }}</th><td>{{ group.counts.total }}</td><td>{{ group.counts.owned }}</td><td>{{ group.counts.missing }}</td><td>{{ group.counts.unknown }}</td><td>{{ group.counts.wanted }} 型号 / {{ group.counts.wantTargetCount }} 目标</td></tr></tbody></table></section>
    <section v-if="entryPage" aria-label="参考项与长度覆盖"><h3>{{ state.section === 'history' ? '历史参考项与长度事实' : '参考项与当前长度覆盖' }}</h3><ul class="records references"><li v-for="entry in entryPage.items" :key="entry.referenceId"><h4>{{ entry.brand }} {{ entry.model }} · {{ entry.edition || '版次未标注' }}</h4><p>{{ entry.series || '系列未标注' }} · {{ states[entry.state] }} · 持有 {{ entry.stockCount }} 盘 · Wanted {{ entry.wantedTargets.length }} 目标</p><p>目录已知长度：{{ entry.knownLengths.length ? entry.knownLengths.map(length => `${length} 分钟`).join(' / ') : '未提供，不能认定 AllLengthsOwned' }}</p><p>已覆盖长度与数量：{{ lengths(entry.ownedLengths) }}</p><p>目录之外的额外长度：{{ entry.extraLengths.length ? lengths(entry.extraLengths) : '无' }}；未知长度 {{ entry.unknownLengthQty }} 盘</p><p>{{ entry.allKnownLengthsOwned && entry.knownLengths.length ? 'AllLengthsOwned · 已覆盖全部已知长度' : '未覆盖全部已知长度，或目录尚无已知长度' }}</p><ul v-if="entry.wantedTargets.length"><li v-for="target in entry.wantedTargets" :key="target.id">求购：{{ priorityLabels[target.priority] }}优先级 · {{ target.targetLengthMinutes === null ? '长度不限' : `${target.targetLengthMinutes} 分钟` }} · {{ target.packagingTarget || '包装不限' }} · {{ target.preferredCondition || '品相不限' }} · {{ target.priceTarget ? `${target.priceTarget.currency} ${target.priceTarget.amount}` : '价格未设置' }}</li></ul><button v-if="state.section === 'progress'" :disabled="blocked || !current" @click="controller.newWant(entry.referenceId)">为此参考项新增求购</button></li></ul><div class="actions"><button :disabled="blocked || entryPage.offset === 0" @click="state.section === 'progress' ? controller.loadProgress(Math.max(0, entryPage.offset - 25)) : state.snapshot && controller.loadSnapshot(state.snapshot.snapshot.id, Math.max(0, entryPage.offset - 25))">上一页参考项</button><span>已读取 {{ entryPage.items.length }} / {{ entryPage.total }} 项</span><button :disabled="blocked || !entryPage.hasMore" @click="state.section === 'progress' ? controller.loadProgress(entryPage.offset + 25) : state.snapshot && controller.loadSnapshot(state.snapshot.snapshot.id, entryPage.offset + 25)">下一页参考项</button></div></section>
  </dialog>
</template>

<style scoped>
.progress-dialog { box-sizing: border-box; width: min(980px, calc(100vw - 32px)); max-height: calc(100dvh - 32px); padding: 24px; overflow-y: auto; color: var(--mb-text-primary); background: var(--mb-bg-base); border: 1px solid var(--mb-glass-border); border-radius: 16px; font-size: 14px; line-height: 1.65; }
.progress-dialog::backdrop { background: #0009; } .heading, .actions, .sections { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; } .heading { justify-content: space-between; } .kicker { color: var(--mb-accent); margin: 0; font-size: 12px; } h2 { margin: 4px 0; font-size: 25px; } h3 { font-size: 18px; margin: 22px 0 12px; } h4 { font-size: 15px; margin: 10px 0; } p { margin: 10px 0; overflow-wrap: anywhere; } .hint { color: var(--mb-text-secondary); font-size: 12px; }
button { min-height: 44px; padding: 8px 13px; border: 1px solid var(--mb-glass-border); border-radius: 8px; color: var(--mb-text-primary); background: var(--mb-glass-clear); font: inherit; cursor: pointer; } button:disabled { opacity: .5; cursor: not-allowed; } button:hover:not(:disabled), .sections button[aria-current] { border-color: var(--mb-accent); } .primary { border-color: var(--mb-accent); } button:focus-visible, input:focus-visible, select:focus-visible, textarea:focus-visible, summary:focus-visible { outline: 2px solid var(--mb-accent); outline-offset: 3px; }
.sections { margin: 20px 0; } fieldset { min-width: 0; padding: 16px; margin: 18px 0; border: 1px solid var(--mb-glass-border); border-radius: 10px; } legend { padding: 0 6px; } .fields { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 14px; } label { display: grid; gap: 6px; font-size: 13px; min-width: 0; } input, select, textarea { box-sizing: border-box; width: 100%; min-width: 0; max-width: 100%; min-height: 44px; padding: 8px; color: var(--mb-text-primary); background: var(--mb-bg-base); border: 1px solid var(--mb-glass-border); border-radius: 7px; font: inherit; } textarea { resize: vertical; } .check { display: flex; align-items: flex-start; gap: 10px; margin: 14px 0; } .check input { flex: 0 0 auto; width: 18px; min-height: 18px; margin-top: 3px; }
.feedback, .capture, .notice, .editor, .records > li { border: 1px solid var(--mb-glass-border); border-radius: 10px; padding: 14px; margin: 14px 0; background: var(--mb-glass-clear); } .notice { color: var(--mb-text-primary); } .error { color: var(--mb-text-primary); border-left: 3px solid var(--mb-accent); padding-left: 12px; } .records { list-style: none; padding: 0; } .notes { white-space: pre-wrap; } code { display: block; overflow-wrap: anywhere; font-size: 12px; } .actions { margin: 12px 0; } details { margin: 18px 0; } summary { cursor: pointer; } table { width: 100%; border-collapse: collapse; table-layout: fixed; font-size: 12px; } th, td { overflow-wrap: anywhere; text-align: left; padding: 9px 6px; border-bottom: 1px solid var(--mb-glass-border); } th:first-child { width: 24%; } caption { text-align: left; color: var(--mb-text-secondary); padding: 10px 0; }
@media (max-width: 760px) { .progress-dialog { padding: 18px; } .fields { grid-template-columns: 1fr; } .heading { align-items: flex-start; } th, td { padding: 8px 3px; } }
</style>
