import assert from 'node:assert/strict';
import test from 'node:test';
import * as c from '@music-bridge/contracts';
import { id, planFixture, mounted } from './helpers/recording-print-ui.js';
const image = { dataUrl: 'data:image/jpeg;base64,/9j/2Q==', width: 1, height: 1 };
function deferred<T>() { let resolve!: (v: T) => void; const promise = new Promise<T>(yes => { resolve = yes; }); return { promise, resolve }; }
function fixture() { const calls: {
    name: string;
    request: unknown;
}[] = []; const master = planFixture().plan.master; const version: c.MasterArtworkVersion = { id: id(81), masterVersionId: master.id, sequence: 1, createdAt: '2026-08-29T00:00:00.000Z', sha256: 'a'.repeat(64), size: 4, width: 1, height: 1, mimeType: 'image/jpeg' }; const api: c.RecordingPrintsPublicApi = { async getMasterArtwork(r) { calls.push({ name: 'get', request: r }); return { masterVersionId: master.id, currentVersion: null, version: null, image: null }; }, async pickMasterArtwork(r) { calls.push({ name: 'pick', request: r }); return { state: 'selected', masterVersionId: master.id, image }; }, async saveMasterArtwork(r) { calls.push({ name: 'save', request: r }); return version; }, async listRecordingPrints() { throw new Error('unused'); }, async requestRecordingPrint() { throw new Error('unused'); }, async retryRecordingPrint() { throw new Error('unused'); }, async getRecordingPrint() { throw new Error('unused'); }, async exportRecordingPrint() { throw new Error('unused'); } }; return { api, master, version, calls }; }
async function controller(f = fixture()) { const m = await import('../src/renderer/src/components/recording/master-artwork-controller.js').catch(() => ({})); assert.ok('createMasterArtworkController' in m); const ctl = (m as typeof import('../src/renderer/src/components/recording/master-artwork-controller.js')).createMasterArtworkController({ api: f.api, master: f.master }); return { ...f, ctl }; }
test('明确Master只读当前Artwork；选图暂存，取消不丢旧待保存图', async () => { const f = await controller(); await f.ctl.refresh(); await f.ctl.pick(); assert.ok(f.ctl.state.staged); assert.equal(f.calls.some(x => x.name === 'save'), false); f.api.pickMasterArtwork = async () => ({ state: 'cancelled' }); await f.ctl.pick(); assert.ok(f.ctl.state.staged); });
test('保存人工确认/CAS，未知回执同DTO重试，不自动换Master', async () => { const f = await controller(); await f.ctl.refresh(); await f.ctl.pick(); await f.ctl.save(); assert.equal(f.calls.some(x => x.name === 'save'), false); f.ctl.setConfirmed(true); f.api.saveMasterArtwork = async (r) => { f.calls.push({ name: 'save', request: r }); throw new Error('/private'); }; await f.ctl.save(); assert.ok(f.ctl.state.pending); assert.equal(f.ctl.canClose(), false); await f.ctl.retryPending(); assert.deepEqual(f.calls.filter(x => x.name === 'save')[0]!.request, f.calls.filter(x => x.name === 'save')[1]!.request); f.ctl.abandonPending(); assert.equal(f.ctl.canClose(), true); });
test('卸载后迟到选图/读图无写入，错误身份/hash不冒充保存成功', async () => { const f = await controller(), wait = deferred<c.PickMasterArtworkResult>(); f.api.pickMasterArtwork = () => wait.promise; const p = f.ctl.pick(); f.ctl.dispose(); wait.resolve({ state: 'selected', masterVersionId: f.master.id, image }); await p; assert.equal(f.ctl.state.staged, undefined); const g = await controller(); await g.ctl.refresh(); await g.ctl.pick(); g.ctl.setConfirmed(true); await g.ctl.save(); assert.ok(g.ctl.state.pending); assert.doesNotMatch(g.ctl.state.notice, /已保存/); assert.equal(g.ctl.state.current, null); });
test('真实Artwork SFC选择和保存分离、取消无成功、明确不可改旧Artifact', async (t) => { const f = fixture(), p = await mounted(t, 'MasterArtworkPanel.vue', f.api, { master: f.master }); assert.match(p.text(), /没有已保存的 Artwork/); assert.match(p.text(), /不改变旧录音/); await p.click('选择本地 Artwork'); assert.match(p.text(), /尚未保存/); assert.equal(p.button('保存为新的 Artwork 版本').props.disabled, true); await p.click('关闭 Artwork'); assert.equal(p.closed(), 1); assert.equal(f.calls.some(x => x.name === 'save'), false); });
test('母版历史每份明确入口，不默认当前Artwork；关闭返回原母版按钮', async (t) => { const f = fixture(), plan = planFixture().plan; const api = { ...f.api, async listMasterVersions() { return { draftId: plan.draftId, masters: [plan.master], layouts: [plan.layout], jobs: [] }; }, async listMediaPlans() { return { draftId: plan.draftId, plans: [] }; } }; const p = await mounted(t, 'MasterVersionsPanel.vue', api, { draft: { id: plan.draftId, title: '合成草稿' } }); assert.equal(f.calls.length, 0); await p.click('管理母版 M1 Artwork'); assert.equal((f.calls[0]!.request as c.GetMasterArtworkRequest).masterVersionId, plan.master.id); await p.click('关闭 Artwork'); assert.equal(p.focused(), p.button('管理母版 M1 Artwork')); });
test('读取当前版本未收口时不能选图使读取代际失效', async () => { const f = await controller(), wait = deferred<c.MasterArtworkResult>(); f.api.getMasterArtwork = () => wait.promise; const read = f.ctl.refresh(); await f.ctl.pick(); assert.equal(f.calls.some(x => x.name === 'pick'), false); wait.resolve({ masterVersionId: f.master.id, currentVersion: null, version: null, image: null }); await read; assert.equal(f.ctl.state.phase, 'ready'); });
test('真实Artwork SFC完整保存验证Hash，disabled失焦恢复且无自动写入', async (t) => { const f = fixture(); f.version.sha256 = await (await import('../src/renderer/src/components/recording/master-artwork-controller.js')).artworkImageSha256(image); const p = await mounted(t, 'MasterArtworkPanel.vue', f.api, { master: f.master }); await p.click('选择本地 Artwork'); await p.confirm(); await p.click('保存为新的 Artwork 版本'); assert.match(p.text(), /新的 Artwork 版本已保存/); assert.equal(f.calls.filter(x => x.name === 'save').length, 1); assert.equal((f.calls.find(x => x.name === 'save')!.request as c.SaveMasterArtworkRequest).expectedVersionId, null); assert.equal((p.focused() as {
    tag: string;
}).tag, 'h2'); });
test('真实Artwork未知回执保留恢复按钮，显式停止重试后才可关闭', async (t) => { const f = fixture(); f.api.saveMasterArtwork = async () => { throw new Error('/private/secret'); }; const p = await mounted(t, 'MasterArtworkPanel.vue', f.api, { master: f.master }); await p.click('选择本地 Artwork'); await p.confirm(); await p.click('保存为新的 Artwork 版本'); assert.equal(p.button('关闭 Artwork').props.disabled, true); assert.equal(p.button('重新读取 Artwork').props.disabled, true); assert.doesNotMatch(p.text(), /private|secret/); await p.click('停止本地重试'); await p.click('关闭 Artwork'); assert.equal(p.closed(), 1); });
