import assert from 'node:assert/strict';
import test from 'node:test';
import * as c from '@music-bridge/contracts';
import { id, planFixture, recordFixture, stateFixture, mounted } from './helpers/recording-print-ui.js';
import { createRecordingPrintRequest } from '../../../packages/bridge-core/src/recording/print-facts.js';
const end = '2026-08-29T00:00:00.000Z', hash = 'a'.repeat(64), image = { dataUrl: 'data:image/jpeg;base64,/9j/2Q==', width: 1, height: 1 };
function deferred<T>() { let resolve!: (v: T) => void, reject!: (e: Error) => void; const promise = new Promise<T>((yes, no) => { resolve = yes; reject = no; }); return { promise, resolve, reject }; }
function fixture() {
    const detail: c.RecordingRecordDetail = { record: recordFixture(), plan: planFixture().plan, current: stateFixture() }, { request, facts } = createRecordingPrintRequest({ id: id(82), record: detail.record, plan: detail.plan, origin: 'historical-backfill', createdAt: end });
    const job: c.RecordingPrintJob = { id: id(83), request, state: 'ready', revision: 3, createdAt: end, updatedAt: end, artifactId: id(86), errorCode: null };
    const result: c.RecordingPrintResult = { artifact: { id: id(86), requestId: request.id, recordingId: detail.record.id, createdAt: end, inputHash: request.inputHash, templateId: 'jp0-basic-v1', templateHash: request.templateHash, rendererVersion: 'test-v1', pdfSha256: hash, size: 100, pageCount: 2, geometry: c.RECORDING_PRINT_GEOMETRY, previewSha256: 'placeholder', previewSize: 4, artwork: facts.artwork }, facts, preview: image };
    const calls: {
        name: string;
        request: unknown;
    }[] = [];
    const api: c.RecordingPrintsPublicApi = { async getMasterArtwork() { return { masterVersionId: id(2), currentVersion: null, version: null, image: null }; }, async pickMasterArtwork() { return { state: 'cancelled' }; }, async saveMasterArtwork() { throw new Error('unused'); }, async listRecordingPrints(r) { calls.push({ name: 'list', request: r }); return { items: [job], offset: 0, limit: 25, total: 1, hasMore: false }; }, async requestRecordingPrint(r) { calls.push({ name: 'request', request: r }); return job; }, async retryRecordingPrint(r) { calls.push({ name: 'retry', request: r }); return { ...job, state: 'pending', revision: 4, artifactId: null }; }, async getRecordingPrint(r) { calls.push({ name: 'get', request: r }); return result; }, async exportRecordingPrint(r) { calls.push({ name: 'export', request: r }); return { state: 'cancelled' }; } };
    return { detail, job, result, api, calls };
}
async function controller(f = fixture()) { const m = await import('../src/renderer/src/components/recording/recording-print-controller.js').catch(() => ({})); assert.ok('createRecordingPrintController' in m); const ctl = (m as typeof import('../src/renderer/src/components/recording/recording-print-controller.js')).createRecordingPrintController({ api: f.api, detail: f.detail }); return { ...f, ctl }; }
test('打印读取不创建/不自动选Artifact；显式get后才能导出', async () => { const f = await controller(); await f.ctl.refresh(); assert.equal(f.ctl.state.selectedId, ''); await f.ctl.exportPdf(); assert.deepEqual(f.calls.map(x => x.name), ['list']); });
test('旧Record补建必须人工确认，失败原DTO重试、不隐式outbox', async () => { const f = await controller(); await f.ctl.request(); assert.equal(f.calls.length, 0); f.ctl.setConfirmed(true); f.api.requestRecordingPrint = async (r) => { f.calls.push({ name: 'request', request: r }); throw new Error('/private/secret'); }; await f.ctl.request(); assert.ok(f.ctl.state.pending); await f.ctl.retryPending(); assert.deepEqual(f.calls[0]!.request, f.calls[1]!.request); assert.doesNotMatch(f.ctl.state.error, /private|secret/); f.ctl.abandonPending(); assert.equal(f.ctl.canClose(), true); });
test('明确Artifact通过Hash核验，导出取消不是成功', async () => { const f = await controller(); f.result.artifact.previewSha256 = await (await import('../src/renderer/src/components/recording/master-artwork-controller.js')).artworkImageSha256(image); await f.ctl.refresh(); await f.ctl.select(id(86)); assert.ok(f.ctl.state.result); await f.ctl.exportPdf(); assert.equal(f.ctl.state.exportPhase, 'cancelled'); assert.ok(f.ctl.state.result); assert.equal(f.calls.filter(x => x.name === 'export').length, 1); });
test('错误Artifact/hash拒绝，保存框未收口不可关闭，卸载忽略迟到', async () => { const f = await controller(); await f.ctl.refresh(); await f.ctl.select(id(86)); assert.equal(f.ctl.state.result, undefined); f.result.artifact.previewSha256 = await (await import('../src/renderer/src/components/recording/master-artwork-controller.js')).artworkImageSha256(image); await f.ctl.select(id(86)); const wait = deferred<c.ExportRecordingPrintResult>(); f.api.exportRecordingPrint = () => wait.promise; const p = f.ctl.exportPdf(); assert.equal(f.ctl.canClose(), false); f.ctl.dispose(); wait.resolve({ state: 'exported', artifactId: id(86), pdfSha256: hash, size: 100 }); await p; assert.notEqual(f.ctl.state.exportPhase, 'exported'); });
test('真实Print SFC显示旧缺失、明确Artifact、导出取消与焦点返回', async (t) => { const f = fixture(); f.result.artifact.previewSha256 = await (await import('../src/renderer/src/components/recording/master-artwork-controller.js')).artworkImageSha256(image); const p = await mounted(t, 'RecordingPrintPanel.vue', f.api, { detail: f.detail }); assert.match(p.text(), /J-Card 与印刷文件/); assert.equal(f.calls.some(x => x.name === 'get'), false); await p.click('查看印刷文件 ' + id(86)); assert.match(p.text(), /排版预览/); await p.click('导出 PDF'); assert.match(p.text(), /已取消导出/); assert.doesNotMatch(p.text(), /PDF 已导出/); await p.click('关闭印刷文件'); assert.equal(p.closed(), 1); });
test('档案详情精确入口不自动取印刷品，关闭回原按钮；v2 Artwork 不称缺失', async (t) => { const f = fixture(); f.detail.record = { ...f.detail.record, schemaVersion: 2, printRequestId: id(82), visuals: { ...f.detail.record.visuals, jCard: { state: 'not-captured', reason: 'not-provided' }, artwork: { state: 'captured', version: { id: id(81), masterVersionId: f.detail.plan.master.id, sequence: 1, createdAt: end, sha256: hash, size: 4, width: 1, height: 1, mimeType: 'image/jpeg' } } } }; const p = await mounted(t, 'RecordingRecordDetail.vue', f.api, { detail: f.detail, state: { visualPhase: 'unread' } }); assert.equal(f.calls.length, 0); assert.match(p.text(), /Artwork：完成时已保存第 1 版/); await p.click('J-Card 与印刷文件'); assert.deepEqual(f.calls.map(x => x.name), ['list']); await p.click('关闭印刷文件'); assert.equal(p.focused(), p.button('J-Card 与印刷文件')); });
test('旧列表迟到不覆盖刷新；旧Artifact迟到不覆盖第二明确选择', async () => { const f = await controller(), list = deferred<c.RecordingPrintsPage>(); f.api.listRecordingPrints = () => list.promise; const old = f.ctl.refresh(); f.api.listRecordingPrints = async () => ({ items: [], offset: 0, limit: 25, total: 0, hasMore: false }); await f.ctl.refresh(); list.resolve({ items: [f.job], offset: 0, limit: 25, total: 1, hasMore: false }); await old; assert.equal(f.ctl.state.page?.total, 0); f.result.artifact.previewSha256 = await (await import('../src/renderer/src/components/recording/master-artwork-controller.js')).artworkImageSha256(image); const other = { ...f.job, id: id(90), artifactId: id(91) }; f.api.listRecordingPrints = async () => ({ items: [f.job, other], offset: 0, limit: 25, total: 2, hasMore: false }); await f.ctl.refresh(); const pending = deferred<c.RecordingPrintResult>(); f.api.getRecordingPrint = r => r.artifactId === id(86) ? pending.promise : Promise.resolve({ ...f.result, artifact: { ...f.result.artifact, id: id(91) } }); const read = f.ctl.select(id(86)); await f.ctl.select(id(91)); pending.resolve(f.result); await read; assert.equal(f.ctl.state.result?.artifact.id, id(91)); });
test('失败Job重试CAS拒绝过期回执，保留原命令；成功后旧列表不倒退', async () => { const f = await controller(); f.job.state = 'failed'; f.job.artifactId = null; f.job.errorCode = 'RENDER_FAILED'; await f.ctl.refresh(); f.ctl.setConfirmed(true); f.api.retryRecordingPrint = async () => structuredClone(f.job); await f.ctl.retry(f.job.id); assert.ok(f.ctl.state.pending); const request = (f.ctl.state.pending as {
    request: c.RetryRecordingPrintRequest;
}).request; assert.equal(request.expectedRevision, 3); f.api.retryRecordingPrint = async () => ({ ...f.job, state: 'pending', revision: 4, errorCode: null }); await f.ctl.retryPending(); assert.equal(f.ctl.state.pending, undefined); await f.ctl.refresh(); assert.equal(f.ctl.state.page?.items[0]?.revision, 4); assert.equal(f.ctl.state.page?.items[0]?.state, 'pending'); });
test('v2不会手动补建，DAT不伪造卡片；错误导出回执不宣称成功', async () => { const f = fixture(); f.detail.record = { ...f.detail.record, schemaVersion: 2, printRequestId: id(82) }; const g = await controller(f); g.ctl.setConfirmed(true); await g.ctl.request(); assert.equal(g.calls.length, 0); const dat = fixture(); dat.detail.plan.layout.spec = { ...dat.detail.plan.layout.spec, format: 'dat' } as c.MediaLayoutSpec; const d = await controller(dat); d.ctl.setConfirmed(true); await d.ctl.request(); assert.equal(d.calls.length, 0); g.result.artifact.previewSha256 = await (await import('../src/renderer/src/components/recording/master-artwork-controller.js')).artworkImageSha256(image); await g.ctl.refresh(); await g.ctl.select(id(86)); g.api.exportRecordingPrint = async () => ({ state: 'exported', artifactId: id(90), pdfSha256: hash, size: 100 }); await g.ctl.exportPdf(); assert.equal(g.ctl.state.exportPhase, 'unknown'); assert.equal(g.ctl.canClose(), true); });
test('真实Print保存框pending关闭禁用；移焦不抢回、未知不成功', async (t) => { const f = fixture(), wait = deferred<c.ExportRecordingPrintResult>(); f.result.artifact.previewSha256 = await (await import('../src/renderer/src/components/recording/master-artwork-controller.js')).artworkImageSha256(image); f.api.exportRecordingPrint = r => { f.calls.push({ name: 'export', request: r }); return wait.promise; }; const p = await mounted(t, 'RecordingPrintPanel.vue', f.api, { detail: f.detail }); await p.click('查看印刷文件 ' + id(86)); const work = p.click('导出 PDF'); await p.tick(); assert.equal(p.button('关闭印刷文件').props.disabled, true); const heading = p.all().find(n => n.tag === 'h3')!; heading.focus(); wait.reject(new Error('/private/path')); await work; assert.equal(p.focused(), heading); assert.match(p.text(), /导出结果未确认/); assert.doesNotMatch(p.text(), /PDF 已导出|private/); assert.equal(f.calls.filter(x => x.name === 'export').length, 1); assert.equal(p.button('关闭印刷文件').props.disabled, false); });
test('真实Print读取失败可重试，成功导出核对三字段但不称已打印', async (t) => { const f = fixture(); f.result.artifact.previewSha256 = await (await import('../src/renderer/src/components/recording/master-artwork-controller.js')).artworkImageSha256(image); let reads = 0; f.api.getRecordingPrint = async () => { if (++reads === 1)
    throw new Error('合成读取故障'); return f.result; }; f.api.exportRecordingPrint = async () => ({ state: 'exported', artifactId: id(86), pdfSha256: hash, size: 100 }); const p = await mounted(t, 'RecordingPrintPanel.vue', f.api, { detail: f.detail }); await p.click('查看印刷文件 ' + id(86)); assert.equal(p.all().some(n => n.tag === 'button' && p.text(n) === '导出 PDF'), false); await p.click('重试此印刷文件'); await p.click('导出 PDF'); assert.match(p.text(), /PDF 已导出；这不表示纸张已打印或已装盒/); assert.equal((p.focused() as {
    tag: string;
}).tag, 'h2'); });
test('真实Print v2自动pending只展示和刷新，不手工补建或自动读取Artifact', async (t) => { const f = fixture(); f.detail.record = { ...f.detail.record, schemaVersion: 2, printRequestId: id(82) }; f.job = { ...f.job, state: 'pending', artifactId: null, revision: 1 }; f.api.listRecordingPrints = async () => ({ items: [f.job], offset: 0, limit: 25, total: 1, hasMore: false }); const p = await mounted(t, 'RecordingPrintPanel.vue', f.api, { detail: f.detail }); assert.match(p.text(), /等待自动生成/); assert.match(p.text(), /基础卡片在录音完成时自动排队/); assert.equal(p.all().some(n => n.tag === 'button' && /依据现有历史事实补建/.test(p.text(n))), false); assert.equal(f.calls.length, 0); });
