import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import {copyFile,lstat,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import * as dto from '@music-bridge/contracts';
import {sourceServiceFixture,owned,hash,type SourceServiceFixture} from './service-fixture.js';
import {sourceArtwork} from './artwork-fixture.js';

for(const file of ['owned-stereo-fixed-tags.flac','owned-stereo-id3v240.mp3'] as const)test(`012 ${file} 真实原件JPEG→私有port attach→内嵌publisher→独立backup/完整撤销`,async t=>{
  const f=await sourceServiceFixture(t,{files:[file]});f.enable();const ref=await sourceArtwork(f,'owned-cover-16.jpg'),before=await readFile(path.join(f.media,file)),beforeAsset=f.repository.localCatalog.asset(f.tracks[0]!.assetId);
  const plan=await f.ready({kind:'embedded-cover',target:f.target(),artwork:ref,slot:'front'});assert.equal(plan.items[0]!.artwork!.mime,'image/jpeg');assert.equal(plan.items[0]!.artwork!.contentRef,ref.contentRef);
  const completed=await f.complete(plan),after=await f.retain('jpeg-published'),backup=path.join(f.directory,'source-writes','safety',plan.items[0]!.operationId,'backup');assert.deepEqual(await readFile(backup),before);assert.notEqual(hash(await readFile(after)),hash(before));
  assert.equal(completed.items[0]!.currentFileRevision,(BigInt(beforeAsset.fileRevision)+1n).toString());assert.deepEqual(completed.items[0]!.verification,{audio:'verified',unselectedMetadata:'verified',content:'verified',reread:'verified'});
  const undone=await f.undo(completed),undo=await f.retain('jpeg-restored');assert.deepEqual(await readFile(undo),before);assert.equal(undone.items[0]!.artwork,null);assert.equal(undone.items[0]!.restoration!.kind,'restore-audio-file');
  const actualBackup=await lstat(backup,{bigint:true}),original=f.beforeOperations.get(plan.items[0]!.operationId);assert.ok(original?.file&&original.originalStat);assert.deepEqual(await readFile(original.file),before);assert.notEqual(`${actualBackup.dev}:${actualBackup.ino}`,`${original.originalStat.dev}:${original.originalStat.ino}`);
  const manifest=path.join(f.directory,'jpeg-source-evidence.json');await writeFile(manifest,JSON.stringify({owned:true,input:file,sourceRoot:f.media,safetyRoot:path.join(f.directory,'source-writes','safety'),before:original.file,originalStat:original.originalStat,originalAttributes:original.originalAttributes,after,undo,restored:undo,target:path.join(f.media,file),backup,originalImageSha256:ref.originalSha256,selectionRevision:ref.expectedSelectionRevision,contentRef:ref.contentRef},null,2)+'\n',{flag:'wx',mode:0o600});t.diagnostic(`Source JPEG真实发布/备份/撤销材料：${manifest}`);
});

test('012 目录cover-only真实创建与absence撤销，全部共享音频预览且AudioAsset修订保持',async t=>{
  const f=await sourceServiceFixture(t);f.enable();const ref=await sourceArtwork(f,'owned-cover-16.png'),before=await Promise.all(f.tracks.map(track=>readFile(path.join(f.media,f.relative(track))))),assets=f.tracks.map(track=>f.repository.localCatalog.asset(track.assetId));
  const target=path.join(f.media,'cover.png');await assert.rejects(lstat(target),{code:'ENOENT'});const p=await f.ready({kind:'directory-cover',target:f.target(),fileName:'cover.png',artwork:ref});assert.equal(p.resourceSummary.sharedTargets,2);assert.ok(p.resourceSummary.resources>=3);
  const completed=await f.complete(p),image=await owned('owned-cover-16.png');assert.deepEqual(await readFile(target),image.bytes);assert.equal(completed.items[0]!.currentFileRevision,assets[0]!.fileRevision);assert.equal(completed.items[0]!.verification.audio,'not-applicable');assert.equal(completed.items[0]!.verification.unselectedMetadata,'not-applicable');
  const output=path.join(f.directory,'directory-cover-created.png');await copyFile(target,output);const backup=path.join(f.directory,'source-writes','safety',completed.items[0]!.operationId,'backup');assert.equal((await lstat(backup)).size,0);
  const removed=await f.undo(completed);assert.equal(removed.items[0]!.restoration!.kind,'remove-new-directory-cover');assert.equal(removed.items[0]!.restoration!.material,'verified-absence');assert.equal(removed.items[0]!.restoration!.expectedOutputSha256,null);assert.equal(removed.items[0]!.artwork,null);await assert.rejects(lstat(target),{code:'ENOENT'});
  for(let i=0;i<f.tracks.length;i++){assert.deepEqual(await readFile(path.join(f.media,f.relative(f.tracks[i]!))),before[i]);assert.deepEqual(f.repository.localCatalog.asset(f.tracks[i]!.assetId),assets[i]);}
  const manifest=path.join(f.directory,'directory-cover-evidence.json');await writeFile(manifest,JSON.stringify({owned:true,sourceRoot:f.media,safetyRoot:path.join(f.directory,'source-writes','safety'),before:null,originalStat:null,originalAttributes:null,after:output,target,targetAbsent:true,absenceRestored:true,backup,assetRevisions:assets.map(a=>a.fileRevision),actualCoverSha256:hash(image.bytes)},null,2)+'\n',{flag:'wx',mode:0o600});t.diagnostic(`Source目录封面原缺失/发布/撤销材料：${manifest}`);
});

test('012 原图ref在标签修订及完整undo后仍可明确新预览；selection同ID换candidate必须旧context失效',async t=>{
  const f=await sourceServiceFixture(t,{files:['owned-stereo-fixed-tags.flac']});f.enable();const ref=await sourceArtwork(f,'owned-cover-16.jpg'),tags=await f.complete(await f.ready({kind:'tags',target:f.target(),fields:{title:{action:'set',value:'保留原图材料的标题'}}}));await f.undo(tags);
  const materials=f.api.get({datasetId:f.datasetId,selector:{kind:'context',target:f.target()}});assert.ok(materials.kind==='context');assert.equal(materials.context.materials[0]!.availability,'available');assert.equal(materials.context.materials[0]!.contentRef,ref.contentRef);
  const p=await f.ready({kind:'embedded-cover',target:f.target(),artwork:ref,slot:'front'}),grant=f.grant(p),track=f.tracks[0]!,context=f.repository.localArtwork.context({trackId:track.id,editionId:ref.editionId});assert.ok(context.target);
  const replacement=await owned('owned-cover-32.jpg'),original={mime:'image/jpeg' as const,bytes:replacement.bytes.length,sha256:replacement.entry.sha256,width:32,height:32};const staged=f.repository.localArtwork.stage({target:context.target,origin:'manual',sourceIdentity:original.sha256,sourceLabel:'新的明确自有图',image:{original,display:{...original,dataUrl:`data:image/jpeg;base64,${replacement.bytes.toString('base64')}`}}}),candidate=staged.candidates.find(v=>v.original.sha256===original.sha256);assert.ok(candidate);
  const selected=f.repository.localArtwork.apply({commandId:randomUUID(),target:context.target,candidateId:candidate.id,expectedSelectionRevision:ref.expectedSelectionRevision});assert.equal(selected.id,ref.selectionId);assert.notEqual(selected.revision,ref.expectedSelectionRevision);
  const accepted=f.api.executeGranted({datasetId:f.datasetId,confirm:grant.request,grant:grant.challenge.grant},f.actor);assert.equal(accepted.outcome,'accepted');const blocked=await f.waitPlan(p.planId,v=>['FAILED','BLOCKED','RECOVERY_REQUIRED','COMPLETED'].includes(v.state));assert.equal(blocked.state,'FAILED');assert.deepEqual(blocked.issues,['ARTWORK_CHANGED']);assert.equal(f.facts.filter(v=>v.operationId===p.items[0]!.operationId).length,0);
});

test('012 原目录JPEG mode0640在CAPTURED后路径gap：恢复READY绑定R原cover属性与独立backup，不借audio mode或当前candidate',async t=>{
  let captured=false;
  const f:SourceServiceFixture=await sourceServiceFixture(t,{files:['owned-stereo-fixed-tags.flac'],phase(fact){if(fact.phase==='CAPTURED'&&!captured){captured=true;throw new Error('自有旧cover被捕获后目标暂缺，必须以R真实原属性恢复。');}}});f.enable();
  const oldImage=await owned('owned-cover-32.jpg'),target=path.join(f.media,'cover.jpg');await writeFile(target,oldImage.bytes,{flag:'wx',mode:0o640});const originalInfo=await lstat(target,{bigint:true});assert.equal(originalInfo.mode&0o777n,0o640n);
  const audioFile=path.join(f.media,f.relative(f.tracks[0]!)),audioBytes=await readFile(audioFile),asset=f.repository.localCatalog.asset(f.tracks[0]!.assetId),ref=await sourceArtwork(f,'owned-cover-16.jpg'),plan=await f.ready({kind:'directory-cover',target:f.target(),fileName:'cover.jpg',artwork:ref});f.execute(plan);
  const origin=await f.waitPlan(plan.planId,p=>['RECOVERY_REQUIRED','FAILED','COMPLETED'].includes(p.state));assert.equal(origin.state,'RECOVERY_REQUIRED');assert.equal(captured,true);await assert.rejects(lstat(target),{code:'ENOENT'});
  const operationId=plan.items[0]!.operationId,backup=path.join(f.directory,'source-writes','safety',operationId,'backup'),quarantine=path.join(f.directory,'source-writes','safety',operationId,'quarantine');assert.deepEqual(await readFile(backup),oldImage.bytes);assert.equal((await lstat(backup)).mode&0o777,0o600);assert.deepEqual(await readFile(quarantine),oldImage.bytes);assert.equal((await lstat(quarantine)).mode&0o777,0o640);assert.deepEqual(f.repository.localCatalog.asset(asset.id),asset);
  const choice=origin.recoveryChoices[0];assert.ok(choice);const accepted=f.api.preview({datasetId:f.datasetId,commandId:randomUUID(),intent:{kind:'recovery',originPlanId:origin.planId,expectedOriginViewRevision:origin.viewRevision,choiceId:choice.choiceId,recoveryFingerprint:choice.recoveryFingerprint}});assert.equal(accepted.outcome,'accepted');assert.ok(accepted.planId);const ready=await f.waitPlan(accepted.planId,p=>p.state!=='PREVIEWING');assert.equal(ready.state,'READY',ready.issues.join(','));assert.equal(ready.items[0]!.artwork,null);assert.equal(ready.items[0]!.restoration!.kind,'restore-directory-cover');assert.equal(ready.items[0]!.restoration!.expectedOutputSha256,hash(oldImage.bytes));
  const restored=await f.complete(ready);assert.equal(restored.state,'COMPLETED');assert.equal(restored.items[0]!.currentFileRevision,asset.fileRevision);assert.deepEqual(await readFile(target),oldImage.bytes);const actual=await lstat(target,{bigint:true});assert.equal(actual.mode&0o777n,0o640n);assert.equal(actual.uid,originalInfo.uid);assert.equal(actual.gid,originalInfo.gid);assert.deepEqual(f.repository.localCatalog.asset(asset.id),asset);assert.deepEqual(await readFile(audioFile),audioBytes);
  const retained=path.join(f.directory,'directory-cover-original0640-restored.jpg');await copyFile(target,retained);const original=f.beforeOperations.get(operationId);assert.ok(original?.file&&original.originalStat&&original.originalAttributes);assert.equal(original.originalAttributes.mode,String(0o640));const manifest=path.join(f.directory,'directory-cover-gap-original-attributes-evidence.json');await writeFile(manifest,JSON.stringify({owned:true,sourceRoot:f.media,safetyRoot:path.join(f.directory,'source-writes','safety'),before:original.file,originalStat:original.originalStat,originalAttributes:original.originalAttributes,backup,target,quarantine,restored:retained,originPlanId:origin.planId,recoveryPlanId:restored.planId,originalImageSha256:hash(oldImage.bytes),actualRestoredMode:String(actual.mode&0o7777n),audioAssetRevision:asset.fileRevision,audioBytesUnchanged:true},null,2)+'\n',{flag:'wx',mode:0o600});t.diagnostic(`Source原cover非0644/路径gap/真实原属性恢复材料：${manifest}`);
});
