import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import {copyFile,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import * as dto from '@music-bridge/contracts';
import {physicalResourceLocks} from '../../src/stream/physical-resource-locks.js';
import {sourceServiceFixture,hash,type SourceServiceFixture} from './service-fixture.js';

const active=(p:dto.LocalSourceWritesPlan)=>!['PREVIEWING','READY','QUEUED','RUNNING','CANCEL_REQUESTED'].includes(p.state);
async function drained(f:SourceServiceFixture):Promise<void>{const end=Date.now()+30000;while(f.policy().draining){if(Date.now()>=end)assert.fail('策略排空未核实');await new Promise<void>(resolve=>setTimeout(resolve,10));}}

test('012 OFF在首项CAPTURED之后：本项独立核验/facts/quiet完成，后续项不准入；I/O未join时ON拒绝',async t=>{
  let fixture:SourceServiceFixture|undefined,switched=false,off:dto.LocalSourceWritesReceipt|undefined,rejectedOn:dto.LocalSourceWritesReceipt|undefined;
  const f=await sourceServiceFixture(t,{phase(fact){if(fact.phase==='CAPTURED'&&!switched){switched=true;assert.ok(fixture);off=fixture.api.setPolicy({datasetId:fixture.datasetId,commandId:randomUUID(),expectedPolicyRevision:fixture.policy().revision,enabled:false});assert.equal(off.outcome,'accepted');rejectedOn=fixture.api.setPolicy({datasetId:fixture.datasetId,commandId:randomUUID(),expectedPolicyRevision:fixture.policy().revision,enabled:true});}}});fixture=f;f.enable();
  const before=await Promise.all(f.tracks.map(track=>readFile(path.join(f.media,f.relative(track))))),assets=f.tracks.map(track=>f.repository.localCatalog.asset(track.assetId)),p=await f.ready({kind:'tags',target:{mode:'batch',trackIds:f.tracks.map(track=>track.id)},fields:{title:{action:'set',value:'OFF只关闭后续项准入'}}});
  f.execute(p);const result=await f.waitPlan(p.planId,active);assert.equal(switched,true);assert.equal(rejectedOn?.outcome,'rejected');assert.equal(rejectedOn?.issue,'POLICY_DRAINING');assert.equal(result.state,'PARTIAL');assert.equal(result.items.filter(i=>i.state==='applied').length,1);assert.equal(result.items.filter(i=>i.state==='not-written').length,1);
  for(let i=0;i<f.tracks.length;i++){const item=result.items.find(v=>v.trackId===f.tracks[i]!.id);assert.ok(item);const bytes=await readFile(path.join(f.media,f.relative(f.tracks[i]!)));if(item.state==='applied'){assert.notDeepEqual(bytes,before[i]);assert.equal(f.repository.localCatalog.asset(item.assetId).fileRevision,(BigInt(assets[i]!.fileRevision)+1n).toString());assert.ok(f.facts.some(v=>v.operationId===item.operationId&&v.phase==='QUIET'));}else{assert.deepEqual(bytes,before[i]);assert.deepEqual(f.repository.localCatalog.asset(item.assetId),assets[i]);assert.equal(f.facts.some(v=>v.operationId===item.operationId&&v.phase==='CAPTURE_INTENT'),false);}}
  const actualApplied=result.items.filter(i=>i.state==='applied'),writtenFiles=await Promise.all(actualApplied.map(async item=>{const index=f.tracks.findIndex(track=>track.id===item.trackId);assert.ok(index>=0);return {item,after:await f.retain(`off-batch-written-${item.operationId}`,index)};}));
  await drained(f);assert.equal(f.policy().enabled,false);assert.equal(physicalResourceLocks.combinedSnapshot().resources,0);f.enable(true);const inverse=await f.undo(result);assert.equal(inverse.state,'COMPLETED');for(let i=0;i<f.tracks.length;i++)assert.deepEqual(await readFile(path.join(f.media,f.relative(f.tracks[i]!))),before[i]);
  const cases=await Promise.all(writtenFiles.map(async({item,after})=>{const previous=f.beforeOperations.get(item.operationId),index=f.tracks.findIndex(track=>track.id===item.trackId);assert.ok(previous?.file&&previous.originalStat&&index>=0);return {sourceRoot:f.media,safetyRoot:path.join(f.directory,'source-writes','safety'),before:previous.file,originalStat:previous.originalStat,originalAttributes:previous.originalAttributes,backup:path.join(f.directory,'source-writes','safety',item.operationId,'backup'),target:previous.target,after,restored:await f.retain(`off-batch-restored-${item.operationId}`,index),selectedFields:{title:'OFF只关闭后续项准入'}};}));const manifest=path.join(f.directory,'off-batch-publication-evidence.json');await writeFile(manifest,JSON.stringify({owned:true,planId:p.planId,undoPlanId:inverse.planId,cases},null,2)+'\n',{flag:'wx',mode:0o600});t.diagnostic(`Source真实OFF批量收口/备份/撤销材料：${manifest}`);
});

test('012 OFF加CAPTURED故障→真实I/Ojoin后允许ON，但普通入口仍拒；指定恢复新READY/grant后保全quiet',async t=>{
  let fixture:SourceServiceFixture|undefined,faulted=false,onDuringIO:dto.LocalSourceWritesReceipt|undefined;
  const f=await sourceServiceFixture(t,{files:['owned-stereo-fixed-tags.flac'],phase(fact){if(fact.phase==='CAPTURED'&&!faulted){faulted=true;assert.ok(fixture);fixture.enable(false);onDuringIO=fixture.api.setPolicy({datasetId:fixture.datasetId,commandId:randomUUID(),expectedPolicyRevision:fixture.policy().revision,enabled:true});throw new Error('自建OFF后已捕获故障，必须保留全部材料。');}}});fixture=f;f.enable();const file=path.join(f.media,f.relative(f.tracks[0]!)),original=await readFile(file),p=await f.ready({kind:'tags',target:f.target(),fields:{title:{action:'set',value:'捕获后未知恢复'}}});f.execute(p);
  const origin=await f.waitPlan(p.planId,v=>v.state==='RECOVERY_REQUIRED');assert.equal(onDuringIO?.issue,'POLICY_DRAINING');assert.equal(f.policy().enabled,false);assert.equal(f.policy().draining,true);assert.ok(physicalResourceLocks.combinedSnapshot().writers>0);
  const end=Date.now()+30000;let enabled:dto.LocalSourceWritesReceipt;for(;;){enabled=f.api.setPolicy({datasetId:f.datasetId,commandId:randomUUID(),expectedPolicyRevision:f.policy().revision,enabled:true});if(enabled.outcome==='accepted')break;assert.equal(enabled.issue,'POLICY_DRAINING');if(Date.now()>=end)assert.fail('ON不能在真实排空后到达');await new Promise<void>(resolve=>setTimeout(resolve,10));}assert.equal(enabled.policy?.draining,false);assert.ok(physicalResourceLocks.combinedSnapshot().writers>0);
  const ordinary=f.api.preview({datasetId:f.datasetId,commandId:randomUUID(),intent:{kind:'tags',target:f.target(),fields:{title:{action:'set',value:'未知尚未解除'}}}});assert.equal(ordinary.issue,'RECOVERY_REQUIRED');
  const choice=origin.recoveryChoices[0];assert.ok(choice);const receipt=f.api.preview({datasetId:f.datasetId,commandId:randomUUID(),intent:{kind:'recovery',originPlanId:origin.planId,expectedOriginViewRevision:origin.viewRevision,choiceId:choice.choiceId,recoveryFingerprint:choice.recoveryFingerprint}});assert.equal(receipt.outcome,'accepted');assert.ok(receipt.planId);const ready=await f.waitPlan(receipt.planId,v=>v.state!=='PREVIEWING');assert.equal(ready.state,'READY',ready.issues.join(','));assert.equal(ready.recoveryOf,origin.planId);
  const complete=await f.complete(ready);assert.deepEqual(await readFile(file),original);assert.equal(complete.items[0]!.restoration!.material,'verified-backup');assert.equal(f.plan(origin.planId).state,'FAILED');assert.equal(physicalResourceLocks.combinedSnapshot().resources,0);
  const previous=f.beforeOperations.get(p.items[0]!.operationId);assert.ok(previous?.file&&previous.originalStat);const restored=path.join(f.directory,'off-explicit-restored.flac');await copyFile(file,restored);const manifest=path.join(f.directory,'off-recovery-evidence.json');await writeFile(manifest,JSON.stringify({owned:true,sourceRoot:f.media,safetyRoot:path.join(f.directory,'source-writes','safety'),before:previous.file,originalStat:previous.originalStat,originalAttributes:previous.originalAttributes,backup:path.join(f.directory,'source-writes','safety',p.items[0]!.operationId,'backup'),target:file,originPlanId:origin.planId,recoveryPlanId:complete.planId,restored,restoredSha256:hash(original),policyRevision:enabled.policy?.revision,actualProtectionQuiet:true},null,2)+'\n',{flag:'wx',mode:0o600});t.diagnostic(`Source真实OFF后UNKNOWN/明确恢复材料：${manifest}`);
});

for(const phase of ['BACKUP','CAPTURED'] as const)test(`012 ${phase}窗口按当前view取消：移动前零写，关键阶段只做必要收口且不伪称回滚`,async t=>{
  let fixture:SourceServiceFixture|undefined,cancelled=false;
  const f=await sourceServiceFixture(t,{files:['owned-stereo-fixed-tags.flac'],phase(fact){if(fact.phase===phase&&!cancelled){cancelled=true;assert.ok(fixture);const origin=fixture.plan(planId),result=fixture.api.cancel({datasetId:fixture.datasetId,commandId:randomUUID(),planId,expectedViewRevision:origin.viewRevision});assert.equal(result.outcome,'accepted');}}});fixture=f;f.enable();let planId='';const file=path.join(f.media,f.relative(f.tracks[0]!)),original=await readFile(file),before=f.repository.localCatalog.asset(f.tracks[0]!.assetId),p=await f.ready({kind:'tags',target:f.target(),fields:{title:{action:'set',value:'取消窗口的必要收口'}}});planId=p.planId;f.execute(p);const result=await f.waitPlan(p.planId,active);assert.equal(cancelled,true);assert.equal(physicalResourceLocks.combinedSnapshot().resources,0);
  if(phase==='BACKUP'){assert.equal(result.state,'CANCELLED');assert.deepEqual(await readFile(file),original);assert.deepEqual(f.repository.localCatalog.asset(before.id),before);assert.equal(f.facts.some(v=>v.phase==='CAPTURE_INTENT'),false);}else{assert.equal(result.state,'COMPLETED');assert.notDeepEqual(await readFile(file),original);assert.equal(f.repository.localCatalog.asset(before.id).fileRevision,(BigInt(before.fileRevision)+1n).toString());assert.ok(f.facts.some(v=>v.phase==='FACTS_COMMITTED'));assert.ok(f.facts.some(v=>v.phase==='QUIET'));}
});
