import assert from 'node:assert/strict';
import test from 'node:test';
import {randomUUID} from 'node:crypto';
import {lstat,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import * as dto from '@music-bridge/contracts';
import {physicalResourceLocks,PhysicalResourceBusy} from '../../src/stream/physical-resource-locks.js';
import {sourceServiceFixture} from './service-fixture.js';
import {sourceOwner} from './owner-fixture.js';

test('012 真Owner七公共命令与独立物理Main端口，generic confirm拒grant，持久受理/读取/history/undo/cancel闭环',async t=>{
  const f=await sourceServiceFixture(t,{files:['owned-stereo-fixed-tags.flac']}),before=await readFile(path.join(f.media,f.relative(f.tracks[0]!)));await f.close();const o=sourceOwner(f,{sharedLocks:true});
  try{await o.boot();const context=await o.request('localSourceWrites.get',{datasetId:f.datasetId,selector:{kind:'context',target:null}});assert.ok(context.kind==='context');assert.equal(context.context.policy.enabled,false);
    const policy=await o.request('localSourceWrites.setPolicy',{datasetId:f.datasetId,commandId:randomUUID(),expectedPolicyRevision:context.context.policy.revision,enabled:true});assert.equal(policy.outcome,'accepted');
    const accepted=await o.request('localSourceWrites.preview',{datasetId:f.datasetId,commandId:randomUUID(),intent:{kind:'tags',target:f.target(),fields:{title:{action:'set',value:'真实物理端口线程写回'}}}});assert.equal(accepted.outcome,'accepted');assert.ok(accepted.planId);const p=await o.waitPlan(accepted.planId,v=>v.state!=='PREVIEWING');assert.equal(p.state,'READY',p.issues.join(','));assert.ok(p.planHash&&p.contextFingerprint);
    const invalid:dto.ConfirmLocalSourceWrites={datasetId:f.datasetId,commandId:randomUUID(),planId:p.planId,expectedViewRevision:p.viewRevision,scope:'SOURCE_FILES',range:p.range,planHash:p.planHash,contextFingerprint:p.contextFingerprint};const rejected=await o.request('localSourceWrites.confirm',invalid);assert.equal(rejected.outcome,'rejected');assert.equal(rejected.issue,'GRANT_REQUIRED');assert.deepEqual(await readFile(path.join(f.media,f.relative(f.tracks[0]!))),before);
    const written=await o.confirm(p);assert.equal(written.accepted.outcome,'accepted');const complete=await o.waitPlan(p.planId,v=>['COMPLETED','FAILED','RECOVERY_REQUIRED'].includes(v.state));assert.equal(complete.state,'COMPLETED',complete.issues.join(','));assert.notDeepEqual(await readFile(path.join(f.media,f.relative(f.tracks[0]!))),before);
    const after=await f.retain('owner-port-written');
    const receipt=await o.request('localSourceWrites.get',{datasetId:f.datasetId,selector:{kind:'command',commandId:written.confirm.commandId,expectedCommand:'localSourceWrites.confirm',requestFingerprint:written.accepted.requestFingerprint}});assert.ok(receipt.kind==='command');assert.deepEqual(receipt.receipt,structuredClone(written.accepted));
    const history=await o.request('localSourceWrites.history',{datasetId:f.datasetId,selector:{kind:'events',planId:p.planId},cursor:null,limit:100});assert.ok(history.kind==='events');assert.ok(history.items.some(v=>v.phase==='FACTS_COMMITTED'));assert.equal(JSON.stringify(history).includes(f.directory),false);
    const inverse=await o.request('localSourceWrites.undo',{datasetId:f.datasetId,commandId:randomUUID(),planId:p.planId,expectedViewRevision:complete.viewRevision,operationIds:complete.items.map(v=>v.operationId),journalFingerprint:complete.journalFingerprint});assert.equal(inverse.outcome,'accepted');assert.ok(inverse.planId);const ready=await o.waitPlan(inverse.planId,v=>v.state!=='PREVIEWING');assert.equal(ready.state,'READY');assert.equal(ready.items[0]!.restoration!.originPlanId,p.planId);await o.confirm(ready);const undone=await o.waitPlan(ready.planId,v=>['COMPLETED','FAILED','RECOVERY_REQUIRED'].includes(v.state));assert.equal(undone.state,'COMPLETED');assert.deepEqual(await readFile(path.join(f.media,f.relative(f.tracks[0]!))),before);
    const restored=await f.retain('owner-port-restored'),previous=f.preWriteSources.get(f.tracks[0]!.id);assert.ok(previous?.file&&previous.originalStat);const manifest=path.join(f.directory,'owner-port-source-evidence.json');await writeFile(manifest,JSON.stringify({owned:true,sourceRoot:f.media,safetyRoot:path.join(f.directory,'source-writes','safety'),before:previous.file,originalStat:previous.originalStat,originalAttributes:previous.originalAttributes,backup:path.join(f.directory,'source-writes','safety',p.items[0]!.operationId,'backup'),target:previous.target,after,restored,planId:p.planId,undoPlanId:undone.planId,selectedFields:{title:'真实物理端口线程写回'}},null,2)+'\n',{flag:'wx',mode:0o600});t.diagnostic(`Source真实Owner端口写后/独立备份/撤销材料：${manifest}`);
    const another=await o.request('localSourceWrites.preview',{datasetId:f.datasetId,commandId:randomUUID(),intent:{kind:'tags',target:f.target(),fields:{title:{action:'set',value:'明确取消的预览'}}}});assert.ok(another.planId);const current=await o.waitPlan(another.planId,v=>v.state!=='PREVIEWING');assert.equal(current.state,'READY');const cancel=await o.request('localSourceWrites.cancel',{datasetId:f.datasetId,commandId:randomUUID(),planId:current.planId,expectedViewRevision:current.viewRevision});assert.equal(cancel.outcome,'accepted');assert.equal((await o.plan(current.planId)).state,'CANCELLED');assert.deepEqual(await readFile(path.join(f.media,f.relative(f.tracks[0]!))),before);
  }finally{await o.close();}assert.equal(physicalResourceLocks.combinedSnapshot().resources,0);
});

test('012 同SAB真实跨线程CAPTURED窗口保护原inode/目录，Reader与冻结publication不能取得读claim',async t=>{
  const f=await sourceServiceFixture(t,{files:['owned-stereo-fixed-tags.flac']}),file=path.join(f.media,f.relative(f.tracks[0]!)),before=await lstat(file,{bigint:true}),physical={dev:String(before.dev),ino:String(before.ino)},parentInfo=await lstat(f.media,{bigint:true}),parent={dev:String(parentInfo.dev),ino:String(parentInfo.ino)};await f.close();
  const publicationGate=new SharedArrayBuffer(8),gate=new Int32Array(publicationGate),o=sourceOwner(f,{sharedLocks:true,publicationGate});
  try{await o.boot();await o.request('localSourceWrites.setPolicy',{datasetId:f.datasetId,commandId:randomUUID(),expectedPolicyRevision:'1',enabled:true});const accepted=await o.request('localSourceWrites.preview',{datasetId:f.datasetId,commandId:randomUUID(),intent:{kind:'tags',target:f.target(),fields:{title:{action:'set',value:'同物理协调器持锁'}}}});assert.ok(accepted.planId);const p=await o.waitPlan(accepted.planId,v=>v.state!=='PREVIEWING');assert.equal(p.state,'READY');await o.confirm(p);
    const deadline=Date.now()+10000;while(Atomics.load(gate,0)===0){if(Date.now()>=deadline)assert.fail('没有进入真实CAPTURED窗口');await new Promise<void>(resolve=>setTimeout(resolve,10));}
    assert.equal(physicalResourceLocks.inspect([physical]).writers,1);assert.equal(physicalResourceLocks.inspect([parent]).writers,1);assert.throws(()=>physicalResourceLocks.acquireRead([physical]),PhysicalResourceBusy);assert.throws(()=>physicalResourceLocks.acquireRead([parent]),PhysicalResourceBusy);await assert.rejects(lstat(file),{code:'ENOENT'});
    Atomics.store(gate,1,1);Atomics.notify(gate,1);const completed=await o.waitPlan(p.planId,v=>['COMPLETED','RECOVERY_REQUIRED','FAILED'].includes(v.state));assert.equal(completed.state,'COMPLETED',completed.issues.join(','));assert.equal(physicalResourceLocks.inspect([physical]).writers,0);const current=await lstat(file,{bigint:true});assert.notEqual(current.ino,before.ino);
  }finally{Atomics.store(gate,1,1);Atomics.notify(gate,1);await o.close();}assert.equal(physicalResourceLocks.combinedSnapshot().resources,0);
});
