import assert from 'node:assert/strict';
import test from 'node:test';
import {chmodSync,mkdirSync,renameSync,writeFileSync} from 'node:fs';
import {chmod,copyFile,lstat,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {physicalResourceLocks} from '../../src/stream/physical-resource-locks.js';
import {sourceServiceFixture,hash,type SourceServiceFixture} from './service-fixture.js';

const input='owned-stereo-fixed-tags.flac';
test('012 STAGED后真实父目录名称替换：held旧FD不能授权新目录，移动前拒绝且两边原件/catalog均不改',async t=>{
  let fixture:SourceServiceFixture|undefined,changed=false,oldParent='',external:Buffer|undefined;
  const f=await sourceServiceFixture(t,{files:[input],phase(fact){if(fact.phase==='STAGED'&&!changed){assert.ok(fixture);changed=true;oldParent=path.join(fixture.directory,'external-retained-original-parent');renameSync(fixture.media,oldParent);mkdirSync(fixture.media,{mode:0o700});assert.ok(external);writeFileSync(path.join(fixture.media,input),external,{flag:'wx',mode:0o600});}}});fixture=f;f.enable();
  const file=path.join(f.media,input),before=await readFile(file),beforeStat=await lstat(f.media,{bigint:true}),asset=f.repository.localCatalog.asset(f.tracks[0]!.assetId),scan=f.repository.localScan.privateCurrentFileState(f.root.id,input);external=Buffer.from(before);external[external.length-1]=external[external.length-1]!^1;
  const ready=await f.ready({kind:'tags',target:f.target(),fields:{title:{action:'set',value:'不得写进换名后的新目录'}}});f.execute(ready);const result=await f.waitPlan(ready.planId,v=>['FAILED','RECOVERY_REQUIRED','COMPLETED'].includes(v.state));
  assert.equal(changed,true);assert.equal(result.state,'FAILED',result.issues.join(','));assert.ok(result.issues.some(v=>v==='SOURCE_CHANGED'||v==='UNKNOWN_PROTECTION'||v==='SOURCE_REVOKED'));assert.equal(f.facts.some(v=>v.phase==='CAPTURED'||v.phase==='PUBLISHED'),false);
  assert.notEqual((await lstat(f.media,{bigint:true})).ino,beforeStat.ino);assert.deepEqual(await readFile(path.join(oldParent,input)),before);assert.deepEqual(await readFile(file),external);assert.deepEqual(f.repository.localCatalog.asset(asset.id),asset);assert.deepEqual(f.repository.localScan.privateCurrentFileState(f.root.id,input),scan);assert.equal(physicalResourceLocks.combinedSnapshot().resources,0);
  const operationId=ready.items[0]!.operationId,backup=path.join(f.directory,'source-writes','safety',operationId,'backup'),preWrite=f.beforeOperations.get(operationId);assert.ok(preWrite?.file&&preWrite.originalStat);assert.deepEqual(await readFile(backup),before);
  const manifest=path.join(f.directory,'parent-name-replacement-evidence.json');await writeFile(manifest,JSON.stringify({owned:true,sourceRoot:oldParent,safetyRoot:path.join(f.directory,'source-writes','safety'),before:preWrite.file,originalStat:preWrite.originalStat,originalAttributes:preWrite.originalAttributes,backup,target:path.join(oldParent,input),externalNamedParent:f.media,externalTarget:file,externalTargetSha256:hash(external),fileMutationPerformed:false},null,2)+'\n',{flag:'wx',mode:0o600});t.diagnostic(`Source真实父目录替换拒绝材料：${manifest}`);
});

test('012 CAPTURE_INTENT后自有原件真实chmod：捕获者属性不等即UNKNOWN保全，明确恢复不能沿修改属性伪写成功',async t=>{
  let fixture:SourceServiceFixture|undefined,changed=false;
  const f=await sourceServiceFixture(t,{files:[input],phase(fact){if(fact.phase==='CAPTURE_INTENT'&&!changed){assert.ok(fixture);changed=true;chmodSync(path.join(fixture.media,input),0o640);}}});fixture=f;f.enable();
  const file=path.join(f.media,input),before=await readFile(file),asset=f.repository.localCatalog.asset(f.tracks[0]!.assetId),ready=await f.ready({kind:'tags',target:f.target(),fields:{title:{action:'set',value:'捕获后不能把外部chmod当干净'}}});f.execute(ready);const unknown=await f.waitPlan(ready.planId,v=>['RECOVERY_REQUIRED','FAILED','COMPLETED'].includes(v.state));assert.equal(changed,true);assert.equal(unknown.state,'RECOVERY_REQUIRED');assert.ok(physicalResourceLocks.combinedSnapshot().writers>0);assert.deepEqual(f.repository.localCatalog.asset(asset.id),asset);
  const operationId=ready.items[0]!.operationId,privateDirectory=path.join(f.directory,'source-writes','safety',operationId),backup=path.join(privateDirectory,'backup'),quarantine=path.join(privateDirectory,'quarantine');assert.deepEqual(await readFile(backup),before);assert.deepEqual(await readFile(quarantine),before);assert.equal((await lstat(quarantine)).mode&0o777,0o640);await assert.rejects(lstat(file),{code:'ENOENT'});assert.equal(f.facts.some(v=>v.phase==='PUBLISHED'),false);
  const choice=unknown.recoveryChoices[0];assert.ok(choice);const refused=f.api.preview({datasetId:f.datasetId,commandId:randomUUID(),intent:{kind:'recovery',originPlanId:unknown.planId,expectedOriginViewRevision:unknown.viewRevision,choiceId:choice.choiceId,recoveryFingerprint:choice.recoveryFingerprint}});assert.equal(refused.outcome,'accepted');assert.ok(refused.planId);const blocked=await f.waitPlan(refused.planId,v=>v.state!=='PREVIEWING');assert.equal(blocked.state,'BLOCKED');assert.ok(blocked.issues.includes('FILE_ATTRIBUTES_UNPROVEN')||blocked.issues.includes('BACKUP_INVALID'));assert.equal(physicalResourceLocks.combinedSnapshot().resources>0,true);
  // 只恢复本测试自行改变的权限，不改变产品资格allowlist、不删除任何xattr。
  await chmod(quarantine,0o600);const origin=f.plan(unknown.planId),nextChoice=origin.recoveryChoices[0];assert.ok(nextChoice);const retry=f.api.preview({datasetId:f.datasetId,commandId:randomUUID(),intent:{kind:'recovery',originPlanId:origin.planId,expectedOriginViewRevision:origin.viewRevision,choiceId:nextChoice.choiceId,recoveryFingerprint:nextChoice.recoveryFingerprint}});assert.equal(retry.outcome,'accepted');assert.ok(retry.planId);const recovery=await f.waitPlan(retry.planId,v=>v.state!=='PREVIEWING');assert.equal(recovery.state,'READY',recovery.issues.join(','));const restored=await f.complete(recovery);assert.deepEqual(await readFile(file),before);assert.equal(physicalResourceLocks.combinedSnapshot().resources,0);
  const retained=path.join(f.directory,'chmod-explicit-restored.flac');await copyFile(file,retained);const preWrite=f.beforeOperations.get(operationId);assert.ok(preWrite?.file&&preWrite.originalStat);const manifest=path.join(f.directory,'capture-attributes-evidence.json');await writeFile(manifest,JSON.stringify({owned:true,sourceRoot:f.media,safetyRoot:path.join(f.directory,'source-writes','safety'),before:preWrite.file,originalStat:preWrite.originalStat,originalAttributes:preWrite.originalAttributes,backup,target:file,quarantine,restored:retained,originPlanId:origin.planId,recoveryPlanId:restored.planId,changedByTest:'仅原件mode0600→0640，之后在自有隔离原件恢复0600；未清xattr',expectedSha256:hash(before)},null,2)+'\n',{flag:'wx',mode:0o600});t.diagnostic(`Source实际属性变化/UNKNOWN/明确恢复材料：${manifest}`);
});
